package models

// This file was generated by the swagger tool.
// Editing this file might prove futile when you re-run the swagger generate command

import (
	strfmt "github.com/go-openapi/strfmt"

	"github.com/go-openapi/errors"
	"github.com/go-openapi/validate"
)

// HttpstatusRange httpstatus range
// swagger:model HTTPStatusRange
type HttpstatusRange struct {

	// Starting HTTP response status code.
	// Required: true
	Begin *int32 `json:"begin"`

	// Ending HTTP response status code.
	// Required: true
	End *int32 `json:"end"`
}

// Validate validates this httpstatus range
func (m *HttpstatusRange) Validate(formats strfmt.Registry) error {
	var res []error

	if err := m.validateBegin(formats); err != nil {
		// prop
		res = append(res, err)
	}

	if err := m.validateEnd(formats); err != nil {
		// prop
		res = append(res, err)
	}

	if len(res) > 0 {
		return errors.CompositeValidationError(res...)
	}
	return nil
}

func (m *HttpstatusRange) validateBegin(formats strfmt.Registry) error {

	if err := validate.Required("begin", "body", m.Begin); err != nil {
		return err
	}

	return nil
}

func (m *HttpstatusRange) validateEnd(formats strfmt.Registry) error {

	if err := validate.Required("end", "body", m.End); err != nil {
		return err
	}

	return nil
}
