---
- hosts: localhost
  connection: local
  vars:
    controller: "{{ controller }}"
    username: "{{ username }}"
    password: "{{ password }}"
    pool_name: "{{ pool_name }}"
    pool_servers_ip: "{{ pool_servers }}"
  tasks:
  - name: build server list
    set_fact: 
      servers: "{{servers|default([]) + [{'ip': {'addr': item, 'type': 'V4'}}] }}"
    with_items: "{{pool_servers_ip.split(',')}}"
    # each server_list item has ansible fact as server
  - avi_api_session:
      # get pool information
      controller: "{{ controller }}"
      username: "{{ username }}"
      password: "{{ password }}"
      http_method: get
      path: pool
      params:
        name: "{{ pool_name }}"
    register: pool_results
  - name: get_pool_path
    set_fact:
      pool_path: pool/{{ pool_results.obj.results[0].uuid }}
  - avi_api_session:
      controller: "{{ controller }}"
      username: "{{ username }}"
      password: "{{ password }}"
      http_method: patch
      path: "{{ pool_path }}"
      data:
        delete:
          servers: "{{ servers }}"
