#
# @author: Gaurav Rastogi grastogi@avinetworks.com
# Simple playbook to create virtualservice
# ansible-playbook -M <location of avi ansible modules> vs.yml

---
- hosts: localhost
  connection: local
  tasks:
  - avi_pool:
      controller: 10.10.25.42
      username: admin
      password: avi123
      name: testpool
      description: woadfder pool
      state: present
      health_monitor_refs:
         - '/api/healthmonitor?name=System-HTTP'
      servers:
         - ip:
             addr: '10.10.25.35'
             type: 'V4'
    register: mypool
  - avi_virtualservice:
      controller: 10.10.25.42
      username: admin
      password: avi123
      name: testvs
      state: present
      services:
         - port: 80
      pool_ref: '/api/pool?name=testpool'
      performance_limits:
         max_concurrent_connections: 1000
         #state: absent
      ip_address:
         addr: '10.90.64.252'
         type: 'V4'
    register: testvs
  - avi_api_session:
      controller: 10.10.25.42
      username: admin
      password: avi123
      tenant: admin
      path: virtualservice
      http_method: get
      params:
        name: testvs
  - debug:
      var: testvs
      verbosity: 2