/*
 * Avi avi_global_spec Object API
 * No description provided (generated by Swagger Codegen https://github.com/swagger-api/swagger-codegen)
 *
 * OpenAPI spec version: 20.1.1
 * Contact: support@avinetworks.com
 *
 * NOTE: This class is auto generated by the swagger code generator program.
 * https://github.com/swagger-api/swagger-codegen.git
 * Do not edit the class manually.
 */

package com.vmware.avi.sdk.model;

import java.util.Objects;
import java.util.Arrays;
import com.fasterxml.jackson.annotation.JsonProperty;
import com.fasterxml.jackson.annotation.JsonCreator;
import com.fasterxml.jackson.annotation.JsonValue;
import io.swagger.v3.oas.annotations.media.Schema;
/**
 * ActionGroupConfig
 */

@javax.annotation.Generated(value = "io.swagger.codegen.v3.generators.java.JavaClientCodegen", date = "2020-03-12T12:27:26.755+05:30[Asia/Kolkata]")
public class ActionGroupConfig {
  @JsonProperty("_last_modified")
  private String _lastModified = null;

  @JsonProperty("action_script_config_ref")
  private String actionScriptConfigRef = null;

  @JsonProperty("autoscale_trigger_notification")
  private Boolean autoscaleTriggerNotification = null;

  @JsonProperty("description")
  private String description = null;

  @JsonProperty("email_config_ref")
  private String emailConfigRef = null;

  @JsonProperty("external_only")
  private Boolean externalOnly = null;

  @JsonProperty("level")
  private String level = "ALERT_LOW";

  @JsonProperty("name")
  private String name = null;

  @JsonProperty("snmp_trap_profile_ref")
  private String snmpTrapProfileRef = null;

  @JsonProperty("syslog_config_ref")
  private String syslogConfigRef = null;

  @JsonProperty("tenant_ref")
  private String tenantRef = null;

  @JsonProperty("url")
  private String url = null;

  @JsonProperty("uuid")
  private String uuid = null;

   /**
   * UNIX time since epoch in microseconds. Units(MICROSECONDS).
   * @return _lastModified
  **/
  @Schema(description = "UNIX time since epoch in microseconds. Units(MICROSECONDS).")
  public String getLastModified() {
    return _lastModified;
  }

  public ActionGroupConfig actionScriptConfigRef(String actionScriptConfigRef) {
    this.actionScriptConfigRef = actionScriptConfigRef;
    return this;
  }

   /**
   * reference of the action script configuration to be used. It is a reference to an object of type AlertScriptConfig.
   * @return actionScriptConfigRef
  **/
  @Schema(description = "reference of the action script configuration to be used. It is a reference to an object of type AlertScriptConfig.")
  public String getActionScriptConfigRef() {
    return actionScriptConfigRef;
  }

  public void setActionScriptConfigRef(String actionScriptConfigRef) {
    this.actionScriptConfigRef = actionScriptConfigRef;
  }

  public ActionGroupConfig autoscaleTriggerNotification(Boolean autoscaleTriggerNotification) {
    this.autoscaleTriggerNotification = autoscaleTriggerNotification;
    return this;
  }

   /**
   * Trigger Notification to AutoScale Manager.
   * @return autoscaleTriggerNotification
  **/
  @Schema(description = "Trigger Notification to AutoScale Manager.")
  public Boolean isAutoscaleTriggerNotification() {
    return autoscaleTriggerNotification;
  }

  public void setAutoscaleTriggerNotification(Boolean autoscaleTriggerNotification) {
    this.autoscaleTriggerNotification = autoscaleTriggerNotification;
  }

  public ActionGroupConfig description(String description) {
    this.description = description;
    return this;
  }

   /**
   * User defined description for the object.
   * @return description
  **/
  @Schema(description = "User defined description for the object.")
  public String getDescription() {
    return description;
  }

  public void setDescription(String description) {
    this.description = description;
  }

  public ActionGroupConfig emailConfigRef(String emailConfigRef) {
    this.emailConfigRef = emailConfigRef;
    return this;
  }

   /**
   * Select the Email Notification configuration to use when sending alerts via email. It is a reference to an object of type AlertEmailConfig.
   * @return emailConfigRef
  **/
  @Schema(description = "Select the Email Notification configuration to use when sending alerts via email. It is a reference to an object of type AlertEmailConfig.")
  public String getEmailConfigRef() {
    return emailConfigRef;
  }

  public void setEmailConfigRef(String emailConfigRef) {
    this.emailConfigRef = emailConfigRef;
  }

  public ActionGroupConfig externalOnly(Boolean externalOnly) {
    this.externalOnly = externalOnly;
    return this;
  }

   /**
   * Generate Alert only to external destinations.
   * @return externalOnly
  **/
  @Schema(required = true, description = "Generate Alert only to external destinations.")
  public Boolean isExternalOnly() {
    return externalOnly;
  }

  public void setExternalOnly(Boolean externalOnly) {
    this.externalOnly = externalOnly;
  }

  public ActionGroupConfig level(String level) {
    this.level = level;
    return this;
  }

   /**
   * When an alert is generated, mark its priority via the Alert Level. Enum options - ALERT_LOW, ALERT_MEDIUM, ALERT_HIGH.
   * @return level
  **/
  @Schema(required = true, description = "When an alert is generated, mark its priority via the Alert Level. Enum options - ALERT_LOW, ALERT_MEDIUM, ALERT_HIGH.")
  public String getLevel() {
    return level;
  }

  public void setLevel(String level) {
    this.level = level;
  }

  public ActionGroupConfig name(String name) {
    this.name = name;
    return this;
  }

   /**
   * Name of the object.
   * @return name
  **/
  @Schema(required = true, description = "Name of the object.")
  public String getName() {
    return name;
  }

  public void setName(String name) {
    this.name = name;
  }

  public ActionGroupConfig snmpTrapProfileRef(String snmpTrapProfileRef) {
    this.snmpTrapProfileRef = snmpTrapProfileRef;
    return this;
  }

   /**
   * Select the SNMP Trap Notification to use when sending alerts via SNMP Trap. It is a reference to an object of type SnmpTrapProfile.
   * @return snmpTrapProfileRef
  **/
  @Schema(description = "Select the SNMP Trap Notification to use when sending alerts via SNMP Trap. It is a reference to an object of type SnmpTrapProfile.")
  public String getSnmpTrapProfileRef() {
    return snmpTrapProfileRef;
  }

  public void setSnmpTrapProfileRef(String snmpTrapProfileRef) {
    this.snmpTrapProfileRef = snmpTrapProfileRef;
  }

  public ActionGroupConfig syslogConfigRef(String syslogConfigRef) {
    this.syslogConfigRef = syslogConfigRef;
    return this;
  }

   /**
   * Select the Syslog Notification configuration to use when sending alerts via Syslog. It is a reference to an object of type AlertSyslogConfig.
   * @return syslogConfigRef
  **/
  @Schema(description = "Select the Syslog Notification configuration to use when sending alerts via Syslog. It is a reference to an object of type AlertSyslogConfig.")
  public String getSyslogConfigRef() {
    return syslogConfigRef;
  }

  public void setSyslogConfigRef(String syslogConfigRef) {
    this.syslogConfigRef = syslogConfigRef;
  }

  public ActionGroupConfig tenantRef(String tenantRef) {
    this.tenantRef = tenantRef;
    return this;
  }

   /**
   *  It is a reference to an object of type Tenant.
   * @return tenantRef
  **/
  @Schema(description = " It is a reference to an object of type Tenant.")
  public String getTenantRef() {
    return tenantRef;
  }

  public void setTenantRef(String tenantRef) {
    this.tenantRef = tenantRef;
  }

   /**
   * url
   * @return url
  **/
  @Schema(description = "url")
  public String getUrl() {
    return url;
  }

  public ActionGroupConfig uuid(String uuid) {
    this.uuid = uuid;
    return this;
  }

   /**
   * Unique object identifier of the object.
   * @return uuid
  **/
  @Schema(description = "Unique object identifier of the object.")
  public String getUuid() {
    return uuid;
  }

  public void setUuid(String uuid) {
    this.uuid = uuid;
  }


  @Override
  public boolean equals(java.lang.Object o) {
    if (this == o) {
      return true;
    }
    if (o == null || getClass() != o.getClass()) {
      return false;
    }
    ActionGroupConfig actionGroupConfig = (ActionGroupConfig) o;
    return Objects.equals(this._lastModified, actionGroupConfig._lastModified) &&
        Objects.equals(this.actionScriptConfigRef, actionGroupConfig.actionScriptConfigRef) &&
        Objects.equals(this.autoscaleTriggerNotification, actionGroupConfig.autoscaleTriggerNotification) &&
        Objects.equals(this.description, actionGroupConfig.description) &&
        Objects.equals(this.emailConfigRef, actionGroupConfig.emailConfigRef) &&
        Objects.equals(this.externalOnly, actionGroupConfig.externalOnly) &&
        Objects.equals(this.level, actionGroupConfig.level) &&
        Objects.equals(this.name, actionGroupConfig.name) &&
        Objects.equals(this.snmpTrapProfileRef, actionGroupConfig.snmpTrapProfileRef) &&
        Objects.equals(this.syslogConfigRef, actionGroupConfig.syslogConfigRef) &&
        Objects.equals(this.tenantRef, actionGroupConfig.tenantRef) &&
        Objects.equals(this.url, actionGroupConfig.url) &&
        Objects.equals(this.uuid, actionGroupConfig.uuid);
  }

  @Override
  public int hashCode() {
    return Objects.hash(_lastModified, actionScriptConfigRef, autoscaleTriggerNotification, description, emailConfigRef, externalOnly, level, name, snmpTrapProfileRef, syslogConfigRef, tenantRef, url, uuid);
  }


  @Override
  public String toString() {
    StringBuilder sb = new StringBuilder();
    sb.append("class ActionGroupConfig {\n");
    
    sb.append("    _lastModified: ").append(toIndentedString(_lastModified)).append("\n");
    sb.append("    actionScriptConfigRef: ").append(toIndentedString(actionScriptConfigRef)).append("\n");
    sb.append("    autoscaleTriggerNotification: ").append(toIndentedString(autoscaleTriggerNotification)).append("\n");
    sb.append("    description: ").append(toIndentedString(description)).append("\n");
    sb.append("    emailConfigRef: ").append(toIndentedString(emailConfigRef)).append("\n");
    sb.append("    externalOnly: ").append(toIndentedString(externalOnly)).append("\n");
    sb.append("    level: ").append(toIndentedString(level)).append("\n");
    sb.append("    name: ").append(toIndentedString(name)).append("\n");
    sb.append("    snmpTrapProfileRef: ").append(toIndentedString(snmpTrapProfileRef)).append("\n");
    sb.append("    syslogConfigRef: ").append(toIndentedString(syslogConfigRef)).append("\n");
    sb.append("    tenantRef: ").append(toIndentedString(tenantRef)).append("\n");
    sb.append("    url: ").append(toIndentedString(url)).append("\n");
    sb.append("    uuid: ").append(toIndentedString(uuid)).append("\n");
    sb.append("}");
    return sb.toString();
  }

  /**
   * Convert the given object to string with each line indented by 4 spaces
   * (except the first line).
   */
  private String toIndentedString(java.lang.Object o) {
    if (o == null) {
      return "null";
    }
    return o.toString().replace("\n", "\n    ");
  }

}
