/*
 * Avi avi_global_spec Object API
 * No description provided (generated by Swagger Codegen https://github.com/swagger-api/swagger-codegen)
 *
 * OpenAPI spec version: 20.1.1
 * Contact: support@avinetworks.com
 *
 * NOTE: This class is auto generated by the swagger code generator program.
 * https://github.com/swagger-api/swagger-codegen.git
 * Do not edit the class manually.
 */

package com.vmware.avi.sdk.model;

import java.util.Objects;
import java.util.Arrays;
import com.fasterxml.jackson.annotation.JsonProperty;
import com.fasterxml.jackson.annotation.JsonCreator;
import com.fasterxml.jackson.annotation.JsonValue;
import io.swagger.v3.oas.annotations.media.Schema;
/**
 * AlertTestEmailParams
 */

@javax.annotation.Generated(value = "io.swagger.codegen.v3.generators.java.JavaClientCodegen", date = "2020-03-12T12:27:26.755+05:30[Asia/Kolkata]")
public class AlertTestEmailParams {
  @JsonProperty("subject")
  private String subject = null;

  @JsonProperty("text")
  private String text = null;

  @JsonProperty("uuid")
  private String uuid = null;

  public AlertTestEmailParams subject(String subject) {
    this.subject = subject;
    return this;
  }

   /**
   * The Subject line of the originating email from  Avi Controller.
   * @return subject
  **/
  @Schema(required = true, description = "The Subject line of the originating email from  Avi Controller.")
  public String getSubject() {
    return subject;
  }

  public void setSubject(String subject) {
    this.subject = subject;
  }

  public AlertTestEmailParams text(String text) {
    this.text = text;
    return this;
  }

   /**
   * The email context.
   * @return text
  **/
  @Schema(required = true, description = "The email context.")
  public String getText() {
    return text;
  }

  public void setText(String text) {
    this.text = text;
  }

  public AlertTestEmailParams uuid(String uuid) {
    this.uuid = uuid;
    return this;
  }

   /**
   * Unique object identifier of the object.
   * @return uuid
  **/
  @Schema(description = "Unique object identifier of the object.")
  public String getUuid() {
    return uuid;
  }

  public void setUuid(String uuid) {
    this.uuid = uuid;
  }


  @Override
  public boolean equals(java.lang.Object o) {
    if (this == o) {
      return true;
    }
    if (o == null || getClass() != o.getClass()) {
      return false;
    }
    AlertTestEmailParams alertTestEmailParams = (AlertTestEmailParams) o;
    return Objects.equals(this.subject, alertTestEmailParams.subject) &&
        Objects.equals(this.text, alertTestEmailParams.text) &&
        Objects.equals(this.uuid, alertTestEmailParams.uuid);
  }

  @Override
  public int hashCode() {
    return Objects.hash(subject, text, uuid);
  }


  @Override
  public String toString() {
    StringBuilder sb = new StringBuilder();
    sb.append("class AlertTestEmailParams {\n");
    
    sb.append("    subject: ").append(toIndentedString(subject)).append("\n");
    sb.append("    text: ").append(toIndentedString(text)).append("\n");
    sb.append("    uuid: ").append(toIndentedString(uuid)).append("\n");
    sb.append("}");
    return sb.toString();
  }

  /**
   * Convert the given object to string with each line indented by 4 spaces
   * (except the first line).
   */
  private String toIndentedString(java.lang.Object o) {
    if (o == null) {
      return "null";
    }
    return o.toString().replace("\n", "\n    ");
  }

}
