/*
 * Avi avi_global_spec Object API
 * No description provided (generated by Swagger Codegen https://github.com/swagger-api/swagger-codegen)
 *
 * OpenAPI spec version: 20.1.1
 * Contact: support@avinetworks.com
 *
 * NOTE: This class is auto generated by the swagger code generator program.
 * https://github.com/swagger-api/swagger-codegen.git
 * Do not edit the class manually.
 */

package com.vmware.avi.sdk.model;

import java.util.Objects;
import java.util.Arrays;
import com.fasterxml.jackson.annotation.JsonProperty;
import com.fasterxml.jackson.annotation.JsonCreator;
import com.fasterxml.jackson.annotation.JsonValue;
import com.vmware.avi.sdk.model.AppCookiePersistenceProfile;
import com.vmware.avi.sdk.model.HdrPersistenceProfile;
import com.vmware.avi.sdk.model.HttpCookiePersistenceProfile;
import com.vmware.avi.sdk.model.IPPersistenceProfile;
import io.swagger.v3.oas.annotations.media.Schema;
/**
 * ApplicationPersistenceProfile
 */

@javax.annotation.Generated(value = "io.swagger.codegen.v3.generators.java.JavaClientCodegen", date = "2020-03-12T12:27:26.755+05:30[Asia/Kolkata]")
public class ApplicationPersistenceProfile {
  @JsonProperty("_last_modified")
  private String _lastModified = null;

  @JsonProperty("app_cookie_persistence_profile")
  private AppCookiePersistenceProfile appCookiePersistenceProfile = null;

  @JsonProperty("description")
  private String description = null;

  @JsonProperty("hdr_persistence_profile")
  private HdrPersistenceProfile hdrPersistenceProfile = null;

  @JsonProperty("http_cookie_persistence_profile")
  private HttpCookiePersistenceProfile httpCookiePersistenceProfile = null;

  @JsonProperty("ip_persistence_profile")
  private IPPersistenceProfile ipPersistenceProfile = null;

  @JsonProperty("is_federated")
  private Boolean isFederated = null;

  @JsonProperty("name")
  private String name = null;

  @JsonProperty("persistence_type")
  private String persistenceType = "PERSISTENCE_TYPE_CLIENT_IP_ADDRESS";

  @JsonProperty("server_hm_down_recovery")
  private String serverHmDownRecovery = "HM_DOWN_PICK_NEW_SERVER";

  @JsonProperty("tenant_ref")
  private String tenantRef = null;

  @JsonProperty("url")
  private String url = null;

  @JsonProperty("uuid")
  private String uuid = null;

   /**
   * UNIX time since epoch in microseconds. Units(MICROSECONDS).
   * @return _lastModified
  **/
  @Schema(description = "UNIX time since epoch in microseconds. Units(MICROSECONDS).")
  public String getLastModified() {
    return _lastModified;
  }

  public ApplicationPersistenceProfile appCookiePersistenceProfile(AppCookiePersistenceProfile appCookiePersistenceProfile) {
    this.appCookiePersistenceProfile = appCookiePersistenceProfile;
    return this;
  }

   /**
   * Get appCookiePersistenceProfile
   * @return appCookiePersistenceProfile
  **/
  @Schema(description = "")
  public AppCookiePersistenceProfile getAppCookiePersistenceProfile() {
    return appCookiePersistenceProfile;
  }

  public void setAppCookiePersistenceProfile(AppCookiePersistenceProfile appCookiePersistenceProfile) {
    this.appCookiePersistenceProfile = appCookiePersistenceProfile;
  }

  public ApplicationPersistenceProfile description(String description) {
    this.description = description;
    return this;
  }

   /**
   * User defined description for the object.
   * @return description
  **/
  @Schema(description = "User defined description for the object.")
  public String getDescription() {
    return description;
  }

  public void setDescription(String description) {
    this.description = description;
  }

  public ApplicationPersistenceProfile hdrPersistenceProfile(HdrPersistenceProfile hdrPersistenceProfile) {
    this.hdrPersistenceProfile = hdrPersistenceProfile;
    return this;
  }

   /**
   * Get hdrPersistenceProfile
   * @return hdrPersistenceProfile
  **/
  @Schema(description = "")
  public HdrPersistenceProfile getHdrPersistenceProfile() {
    return hdrPersistenceProfile;
  }

  public void setHdrPersistenceProfile(HdrPersistenceProfile hdrPersistenceProfile) {
    this.hdrPersistenceProfile = hdrPersistenceProfile;
  }

  public ApplicationPersistenceProfile httpCookiePersistenceProfile(HttpCookiePersistenceProfile httpCookiePersistenceProfile) {
    this.httpCookiePersistenceProfile = httpCookiePersistenceProfile;
    return this;
  }

   /**
   * Get httpCookiePersistenceProfile
   * @return httpCookiePersistenceProfile
  **/
  @Schema(description = "")
  public HttpCookiePersistenceProfile getHttpCookiePersistenceProfile() {
    return httpCookiePersistenceProfile;
  }

  public void setHttpCookiePersistenceProfile(HttpCookiePersistenceProfile httpCookiePersistenceProfile) {
    this.httpCookiePersistenceProfile = httpCookiePersistenceProfile;
  }

  public ApplicationPersistenceProfile ipPersistenceProfile(IPPersistenceProfile ipPersistenceProfile) {
    this.ipPersistenceProfile = ipPersistenceProfile;
    return this;
  }

   /**
   * Get ipPersistenceProfile
   * @return ipPersistenceProfile
  **/
  @Schema(description = "")
  public IPPersistenceProfile getIpPersistenceProfile() {
    return ipPersistenceProfile;
  }

  public void setIpPersistenceProfile(IPPersistenceProfile ipPersistenceProfile) {
    this.ipPersistenceProfile = ipPersistenceProfile;
  }

  public ApplicationPersistenceProfile isFederated(Boolean isFederated) {
    this.isFederated = isFederated;
    return this;
  }

   /**
   * This field describes the object&#x27;s replication scope. If the field is set to false, then the object is visible within the controller-cluster and its associated service-engines.  If the field is set to true, then the object is replicated across the federation.  . Field introduced in 17.1.3.
   * @return isFederated
  **/
  @Schema(description = "This field describes the object's replication scope. If the field is set to false, then the object is visible within the controller-cluster and its associated service-engines.  If the field is set to true, then the object is replicated across the federation.  . Field introduced in 17.1.3.")
  public Boolean isIsFederated() {
    return isFederated;
  }

  public void setIsFederated(Boolean isFederated) {
    this.isFederated = isFederated;
  }

  public ApplicationPersistenceProfile name(String name) {
    this.name = name;
    return this;
  }

   /**
   * A user-friendly name for the persistence profile.
   * @return name
  **/
  @Schema(required = true, description = "A user-friendly name for the persistence profile.")
  public String getName() {
    return name;
  }

  public void setName(String name) {
    this.name = name;
  }

  public ApplicationPersistenceProfile persistenceType(String persistenceType) {
    this.persistenceType = persistenceType;
    return this;
  }

   /**
   * Method used to persist clients to the same server for a duration of time or a session. Enum options - PERSISTENCE_TYPE_CLIENT_IP_ADDRESS, PERSISTENCE_TYPE_HTTP_COOKIE, PERSISTENCE_TYPE_TLS, PERSISTENCE_TYPE_CLIENT_IPV6_ADDRESS, PERSISTENCE_TYPE_CUSTOM_HTTP_HEADER, PERSISTENCE_TYPE_APP_COOKIE, PERSISTENCE_TYPE_GSLB_SITE.
   * @return persistenceType
  **/
  @Schema(required = true, description = "Method used to persist clients to the same server for a duration of time or a session. Enum options - PERSISTENCE_TYPE_CLIENT_IP_ADDRESS, PERSISTENCE_TYPE_HTTP_COOKIE, PERSISTENCE_TYPE_TLS, PERSISTENCE_TYPE_CLIENT_IPV6_ADDRESS, PERSISTENCE_TYPE_CUSTOM_HTTP_HEADER, PERSISTENCE_TYPE_APP_COOKIE, PERSISTENCE_TYPE_GSLB_SITE.")
  public String getPersistenceType() {
    return persistenceType;
  }

  public void setPersistenceType(String persistenceType) {
    this.persistenceType = persistenceType;
  }

  public ApplicationPersistenceProfile serverHmDownRecovery(String serverHmDownRecovery) {
    this.serverHmDownRecovery = serverHmDownRecovery;
    return this;
  }

   /**
   * Specifies behavior when a persistent server has been marked down by a health monitor. Enum options - HM_DOWN_PICK_NEW_SERVER, HM_DOWN_ABORT_CONNECTION, HM_DOWN_CONTINUE_PERSISTENT_SERVER.
   * @return serverHmDownRecovery
  **/
  @Schema(description = "Specifies behavior when a persistent server has been marked down by a health monitor. Enum options - HM_DOWN_PICK_NEW_SERVER, HM_DOWN_ABORT_CONNECTION, HM_DOWN_CONTINUE_PERSISTENT_SERVER.")
  public String getServerHmDownRecovery() {
    return serverHmDownRecovery;
  }

  public void setServerHmDownRecovery(String serverHmDownRecovery) {
    this.serverHmDownRecovery = serverHmDownRecovery;
  }

  public ApplicationPersistenceProfile tenantRef(String tenantRef) {
    this.tenantRef = tenantRef;
    return this;
  }

   /**
   *  It is a reference to an object of type Tenant.
   * @return tenantRef
  **/
  @Schema(description = " It is a reference to an object of type Tenant.")
  public String getTenantRef() {
    return tenantRef;
  }

  public void setTenantRef(String tenantRef) {
    this.tenantRef = tenantRef;
  }

   /**
   * url
   * @return url
  **/
  @Schema(description = "url")
  public String getUrl() {
    return url;
  }

  public ApplicationPersistenceProfile uuid(String uuid) {
    this.uuid = uuid;
    return this;
  }

   /**
   * UUID of the persistence profile.
   * @return uuid
  **/
  @Schema(description = "UUID of the persistence profile.")
  public String getUuid() {
    return uuid;
  }

  public void setUuid(String uuid) {
    this.uuid = uuid;
  }


  @Override
  public boolean equals(java.lang.Object o) {
    if (this == o) {
      return true;
    }
    if (o == null || getClass() != o.getClass()) {
      return false;
    }
    ApplicationPersistenceProfile applicationPersistenceProfile = (ApplicationPersistenceProfile) o;
    return Objects.equals(this._lastModified, applicationPersistenceProfile._lastModified) &&
        Objects.equals(this.appCookiePersistenceProfile, applicationPersistenceProfile.appCookiePersistenceProfile) &&
        Objects.equals(this.description, applicationPersistenceProfile.description) &&
        Objects.equals(this.hdrPersistenceProfile, applicationPersistenceProfile.hdrPersistenceProfile) &&
        Objects.equals(this.httpCookiePersistenceProfile, applicationPersistenceProfile.httpCookiePersistenceProfile) &&
        Objects.equals(this.ipPersistenceProfile, applicationPersistenceProfile.ipPersistenceProfile) &&
        Objects.equals(this.isFederated, applicationPersistenceProfile.isFederated) &&
        Objects.equals(this.name, applicationPersistenceProfile.name) &&
        Objects.equals(this.persistenceType, applicationPersistenceProfile.persistenceType) &&
        Objects.equals(this.serverHmDownRecovery, applicationPersistenceProfile.serverHmDownRecovery) &&
        Objects.equals(this.tenantRef, applicationPersistenceProfile.tenantRef) &&
        Objects.equals(this.url, applicationPersistenceProfile.url) &&
        Objects.equals(this.uuid, applicationPersistenceProfile.uuid);
  }

  @Override
  public int hashCode() {
    return Objects.hash(_lastModified, appCookiePersistenceProfile, description, hdrPersistenceProfile, httpCookiePersistenceProfile, ipPersistenceProfile, isFederated, name, persistenceType, serverHmDownRecovery, tenantRef, url, uuid);
  }


  @Override
  public String toString() {
    StringBuilder sb = new StringBuilder();
    sb.append("class ApplicationPersistenceProfile {\n");
    
    sb.append("    _lastModified: ").append(toIndentedString(_lastModified)).append("\n");
    sb.append("    appCookiePersistenceProfile: ").append(toIndentedString(appCookiePersistenceProfile)).append("\n");
    sb.append("    description: ").append(toIndentedString(description)).append("\n");
    sb.append("    hdrPersistenceProfile: ").append(toIndentedString(hdrPersistenceProfile)).append("\n");
    sb.append("    httpCookiePersistenceProfile: ").append(toIndentedString(httpCookiePersistenceProfile)).append("\n");
    sb.append("    ipPersistenceProfile: ").append(toIndentedString(ipPersistenceProfile)).append("\n");
    sb.append("    isFederated: ").append(toIndentedString(isFederated)).append("\n");
    sb.append("    name: ").append(toIndentedString(name)).append("\n");
    sb.append("    persistenceType: ").append(toIndentedString(persistenceType)).append("\n");
    sb.append("    serverHmDownRecovery: ").append(toIndentedString(serverHmDownRecovery)).append("\n");
    sb.append("    tenantRef: ").append(toIndentedString(tenantRef)).append("\n");
    sb.append("    url: ").append(toIndentedString(url)).append("\n");
    sb.append("    uuid: ").append(toIndentedString(uuid)).append("\n");
    sb.append("}");
    return sb.toString();
  }

  /**
   * Convert the given object to string with each line indented by 4 spaces
   * (except the first line).
   */
  private String toIndentedString(java.lang.Object o) {
    if (o == null) {
      return "null";
    }
    return o.toString().replace("\n", "\n    ");
  }

}
