/*
 * Avi avi_global_spec Object API
 * No description provided (generated by Swagger Codegen https://github.com/swagger-api/swagger-codegen)
 *
 * OpenAPI spec version: 20.1.1
 * Contact: support@avinetworks.com
 *
 * NOTE: This class is auto generated by the swagger code generator program.
 * https://github.com/swagger-api/swagger-codegen.git
 * Do not edit the class manually.
 */

package com.vmware.avi.sdk.model;

import java.util.Objects;
import java.util.Arrays;
import com.fasterxml.jackson.annotation.JsonProperty;
import com.fasterxml.jackson.annotation.JsonCreator;
import com.fasterxml.jackson.annotation.JsonValue;
import io.swagger.v3.oas.annotations.media.Schema;
/**
 * BackupConfiguration
 */

@javax.annotation.Generated(value = "io.swagger.codegen.v3.generators.java.JavaClientCodegen", date = "2020-03-12T12:27:26.755+05:30[Asia/Kolkata]")
public class BackupConfiguration {
  @JsonProperty("_last_modified")
  private String _lastModified = null;

  @JsonProperty("aws_access_key")
  private String awsAccessKey = null;

  @JsonProperty("aws_bucket_id")
  private String awsBucketId = null;

  @JsonProperty("aws_secret_access")
  private String awsSecretAccess = null;

  @JsonProperty("backup_file_prefix")
  private String backupFilePrefix = null;

  @JsonProperty("backup_passphrase")
  private String backupPassphrase = null;

  @JsonProperty("maximum_backups_stored")
  private Integer maximumBackupsStored = 4;

  @JsonProperty("name")
  private String name = null;

  @JsonProperty("remote_directory")
  private String remoteDirectory = null;

  @JsonProperty("remote_hostname")
  private String remoteHostname = null;

  @JsonProperty("save_local")
  private Boolean saveLocal = null;

  @JsonProperty("ssh_user_ref")
  private String sshUserRef = null;

  @JsonProperty("tenant_ref")
  private String tenantRef = null;

  @JsonProperty("upload_to_remote_host")
  private Boolean uploadToRemoteHost = null;

  @JsonProperty("upload_to_s3")
  private Boolean uploadToS3 = null;

  @JsonProperty("url")
  private String url = null;

  @JsonProperty("uuid")
  private String uuid = null;

   /**
   * UNIX time since epoch in microseconds. Units(MICROSECONDS).
   * @return _lastModified
  **/
  @Schema(description = "UNIX time since epoch in microseconds. Units(MICROSECONDS).")
  public String getLastModified() {
    return _lastModified;
  }

  public BackupConfiguration awsAccessKey(String awsAccessKey) {
    this.awsAccessKey = awsAccessKey;
    return this;
  }

   /**
   * AWS Access Key ID. Field introduced in 18.2.3.
   * @return awsAccessKey
  **/
  @Schema(description = "AWS Access Key ID. Field introduced in 18.2.3.")
  public String getAwsAccessKey() {
    return awsAccessKey;
  }

  public void setAwsAccessKey(String awsAccessKey) {
    this.awsAccessKey = awsAccessKey;
  }

  public BackupConfiguration awsBucketId(String awsBucketId) {
    this.awsBucketId = awsBucketId;
    return this;
  }

   /**
   * AWS bucket. Field introduced in 18.2.3.
   * @return awsBucketId
  **/
  @Schema(description = "AWS bucket. Field introduced in 18.2.3.")
  public String getAwsBucketId() {
    return awsBucketId;
  }

  public void setAwsBucketId(String awsBucketId) {
    this.awsBucketId = awsBucketId;
  }

  public BackupConfiguration awsSecretAccess(String awsSecretAccess) {
    this.awsSecretAccess = awsSecretAccess;
    return this;
  }

   /**
   * AWS Secret Access Key. Field introduced in 18.2.3.
   * @return awsSecretAccess
  **/
  @Schema(description = "AWS Secret Access Key. Field introduced in 18.2.3.")
  public String getAwsSecretAccess() {
    return awsSecretAccess;
  }

  public void setAwsSecretAccess(String awsSecretAccess) {
    this.awsSecretAccess = awsSecretAccess;
  }

  public BackupConfiguration backupFilePrefix(String backupFilePrefix) {
    this.backupFilePrefix = backupFilePrefix;
    return this;
  }

   /**
   * Prefix of the exported configuration file. Field introduced in 17.1.1.
   * @return backupFilePrefix
  **/
  @Schema(description = "Prefix of the exported configuration file. Field introduced in 17.1.1.")
  public String getBackupFilePrefix() {
    return backupFilePrefix;
  }

  public void setBackupFilePrefix(String backupFilePrefix) {
    this.backupFilePrefix = backupFilePrefix;
  }

  public BackupConfiguration backupPassphrase(String backupPassphrase) {
    this.backupPassphrase = backupPassphrase;
    return this;
  }

   /**
   * Passphrase of backup configuration.
   * @return backupPassphrase
  **/
  @Schema(description = "Passphrase of backup configuration.")
  public String getBackupPassphrase() {
    return backupPassphrase;
  }

  public void setBackupPassphrase(String backupPassphrase) {
    this.backupPassphrase = backupPassphrase;
  }

  public BackupConfiguration maximumBackupsStored(Integer maximumBackupsStored) {
    this.maximumBackupsStored = maximumBackupsStored;
    return this;
  }

   /**
   * Rotate the backup files based on this count. Allowed values are 1-20.
   * @return maximumBackupsStored
  **/
  @Schema(description = "Rotate the backup files based on this count. Allowed values are 1-20.")
  public Integer getMaximumBackupsStored() {
    return maximumBackupsStored;
  }

  public void setMaximumBackupsStored(Integer maximumBackupsStored) {
    this.maximumBackupsStored = maximumBackupsStored;
  }

  public BackupConfiguration name(String name) {
    this.name = name;
    return this;
  }

   /**
   * Name of backup configuration.
   * @return name
  **/
  @Schema(required = true, description = "Name of backup configuration.")
  public String getName() {
    return name;
  }

  public void setName(String name) {
    this.name = name;
  }

  public BackupConfiguration remoteDirectory(String remoteDirectory) {
    this.remoteDirectory = remoteDirectory;
    return this;
  }

   /**
   * Directory at remote destination with write permission for ssh user.
   * @return remoteDirectory
  **/
  @Schema(description = "Directory at remote destination with write permission for ssh user.")
  public String getRemoteDirectory() {
    return remoteDirectory;
  }

  public void setRemoteDirectory(String remoteDirectory) {
    this.remoteDirectory = remoteDirectory;
  }

  public BackupConfiguration remoteHostname(String remoteHostname) {
    this.remoteHostname = remoteHostname;
    return this;
  }

   /**
   * Remote Destination.
   * @return remoteHostname
  **/
  @Schema(description = "Remote Destination.")
  public String getRemoteHostname() {
    return remoteHostname;
  }

  public void setRemoteHostname(String remoteHostname) {
    this.remoteHostname = remoteHostname;
  }

  public BackupConfiguration saveLocal(Boolean saveLocal) {
    this.saveLocal = saveLocal;
    return this;
  }

   /**
   * Local Backup.
   * @return saveLocal
  **/
  @Schema(description = "Local Backup.")
  public Boolean isSaveLocal() {
    return saveLocal;
  }

  public void setSaveLocal(Boolean saveLocal) {
    this.saveLocal = saveLocal;
  }

  public BackupConfiguration sshUserRef(String sshUserRef) {
    this.sshUserRef = sshUserRef;
    return this;
  }

   /**
   * Access Credentials for remote destination. It is a reference to an object of type CloudConnectorUser.
   * @return sshUserRef
  **/
  @Schema(description = "Access Credentials for remote destination. It is a reference to an object of type CloudConnectorUser.")
  public String getSshUserRef() {
    return sshUserRef;
  }

  public void setSshUserRef(String sshUserRef) {
    this.sshUserRef = sshUserRef;
  }

  public BackupConfiguration tenantRef(String tenantRef) {
    this.tenantRef = tenantRef;
    return this;
  }

   /**
   *  It is a reference to an object of type Tenant.
   * @return tenantRef
  **/
  @Schema(description = " It is a reference to an object of type Tenant.")
  public String getTenantRef() {
    return tenantRef;
  }

  public void setTenantRef(String tenantRef) {
    this.tenantRef = tenantRef;
  }

  public BackupConfiguration uploadToRemoteHost(Boolean uploadToRemoteHost) {
    this.uploadToRemoteHost = uploadToRemoteHost;
    return this;
  }

   /**
   * Remote Backup.
   * @return uploadToRemoteHost
  **/
  @Schema(description = "Remote Backup.")
  public Boolean isUploadToRemoteHost() {
    return uploadToRemoteHost;
  }

  public void setUploadToRemoteHost(Boolean uploadToRemoteHost) {
    this.uploadToRemoteHost = uploadToRemoteHost;
  }

  public BackupConfiguration uploadToS3(Boolean uploadToS3) {
    this.uploadToS3 = uploadToS3;
    return this;
  }

   /**
   * Cloud Backup. Field introduced in 18.2.3.
   * @return uploadToS3
  **/
  @Schema(description = "Cloud Backup. Field introduced in 18.2.3.")
  public Boolean isUploadToS3() {
    return uploadToS3;
  }

  public void setUploadToS3(Boolean uploadToS3) {
    this.uploadToS3 = uploadToS3;
  }

   /**
   * url
   * @return url
  **/
  @Schema(description = "url")
  public String getUrl() {
    return url;
  }

  public BackupConfiguration uuid(String uuid) {
    this.uuid = uuid;
    return this;
  }

   /**
   * Unique object identifier of the object.
   * @return uuid
  **/
  @Schema(description = "Unique object identifier of the object.")
  public String getUuid() {
    return uuid;
  }

  public void setUuid(String uuid) {
    this.uuid = uuid;
  }


  @Override
  public boolean equals(java.lang.Object o) {
    if (this == o) {
      return true;
    }
    if (o == null || getClass() != o.getClass()) {
      return false;
    }
    BackupConfiguration backupConfiguration = (BackupConfiguration) o;
    return Objects.equals(this._lastModified, backupConfiguration._lastModified) &&
        Objects.equals(this.awsAccessKey, backupConfiguration.awsAccessKey) &&
        Objects.equals(this.awsBucketId, backupConfiguration.awsBucketId) &&
        Objects.equals(this.awsSecretAccess, backupConfiguration.awsSecretAccess) &&
        Objects.equals(this.backupFilePrefix, backupConfiguration.backupFilePrefix) &&
        Objects.equals(this.backupPassphrase, backupConfiguration.backupPassphrase) &&
        Objects.equals(this.maximumBackupsStored, backupConfiguration.maximumBackupsStored) &&
        Objects.equals(this.name, backupConfiguration.name) &&
        Objects.equals(this.remoteDirectory, backupConfiguration.remoteDirectory) &&
        Objects.equals(this.remoteHostname, backupConfiguration.remoteHostname) &&
        Objects.equals(this.saveLocal, backupConfiguration.saveLocal) &&
        Objects.equals(this.sshUserRef, backupConfiguration.sshUserRef) &&
        Objects.equals(this.tenantRef, backupConfiguration.tenantRef) &&
        Objects.equals(this.uploadToRemoteHost, backupConfiguration.uploadToRemoteHost) &&
        Objects.equals(this.uploadToS3, backupConfiguration.uploadToS3) &&
        Objects.equals(this.url, backupConfiguration.url) &&
        Objects.equals(this.uuid, backupConfiguration.uuid);
  }

  @Override
  public int hashCode() {
    return Objects.hash(_lastModified, awsAccessKey, awsBucketId, awsSecretAccess, backupFilePrefix, backupPassphrase, maximumBackupsStored, name, remoteDirectory, remoteHostname, saveLocal, sshUserRef, tenantRef, uploadToRemoteHost, uploadToS3, url, uuid);
  }


  @Override
  public String toString() {
    StringBuilder sb = new StringBuilder();
    sb.append("class BackupConfiguration {\n");
    
    sb.append("    _lastModified: ").append(toIndentedString(_lastModified)).append("\n");
    sb.append("    awsAccessKey: ").append(toIndentedString(awsAccessKey)).append("\n");
    sb.append("    awsBucketId: ").append(toIndentedString(awsBucketId)).append("\n");
    sb.append("    awsSecretAccess: ").append(toIndentedString(awsSecretAccess)).append("\n");
    sb.append("    backupFilePrefix: ").append(toIndentedString(backupFilePrefix)).append("\n");
    sb.append("    backupPassphrase: ").append(toIndentedString(backupPassphrase)).append("\n");
    sb.append("    maximumBackupsStored: ").append(toIndentedString(maximumBackupsStored)).append("\n");
    sb.append("    name: ").append(toIndentedString(name)).append("\n");
    sb.append("    remoteDirectory: ").append(toIndentedString(remoteDirectory)).append("\n");
    sb.append("    remoteHostname: ").append(toIndentedString(remoteHostname)).append("\n");
    sb.append("    saveLocal: ").append(toIndentedString(saveLocal)).append("\n");
    sb.append("    sshUserRef: ").append(toIndentedString(sshUserRef)).append("\n");
    sb.append("    tenantRef: ").append(toIndentedString(tenantRef)).append("\n");
    sb.append("    uploadToRemoteHost: ").append(toIndentedString(uploadToRemoteHost)).append("\n");
    sb.append("    uploadToS3: ").append(toIndentedString(uploadToS3)).append("\n");
    sb.append("    url: ").append(toIndentedString(url)).append("\n");
    sb.append("    uuid: ").append(toIndentedString(uuid)).append("\n");
    sb.append("}");
    return sb.toString();
  }

  /**
   * Convert the given object to string with each line indented by 4 spaces
   * (except the first line).
   */
  private String toIndentedString(java.lang.Object o) {
    if (o == null) {
      return "null";
    }
    return o.toString().replace("\n", "\n    ");
  }

}
