/*
 * Avi avi_global_spec Object API
 * No description provided (generated by Swagger Codegen https://github.com/swagger-api/swagger-codegen)
 *
 * OpenAPI spec version: 20.1.1
 * Contact: support@avinetworks.com
 *
 * NOTE: This class is auto generated by the swagger code generator program.
 * https://github.com/swagger-api/swagger-codegen.git
 * Do not edit the class manually.
 */

package com.vmware.avi.sdk.model;

import java.util.Objects;
import java.util.Arrays;
import com.fasterxml.jackson.annotation.JsonProperty;
import com.fasterxml.jackson.annotation.JsonCreator;
import com.fasterxml.jackson.annotation.JsonValue;
import io.swagger.v3.oas.annotations.media.Schema;
/**
 * BfdProfile
 */

@javax.annotation.Generated(value = "io.swagger.codegen.v3.generators.java.JavaClientCodegen", date = "2020-03-12T12:27:26.755+05:30[Asia/Kolkata]")
public class BfdProfile {
  @JsonProperty("minrx")
  private Integer minrx = 1000;

  @JsonProperty("mintx")
  private Integer mintx = 1000;

  @JsonProperty("multi")
  private Integer multi = 3;

  public BfdProfile minrx(Integer minrx) {
    this.minrx = minrx;
    return this;
  }

   /**
   * Default required minimum receive interval (in ms) used in BFD. Allowed values are 500-4000000. Field introduced in 20.1.1.
   * @return minrx
  **/
  @Schema(description = "Default required minimum receive interval (in ms) used in BFD. Allowed values are 500-4000000. Field introduced in 20.1.1.")
  public Integer getMinrx() {
    return minrx;
  }

  public void setMinrx(Integer minrx) {
    this.minrx = minrx;
  }

  public BfdProfile mintx(Integer mintx) {
    this.mintx = mintx;
    return this;
  }

   /**
   * Default desired minimum transmit interval (in ms) used in BFD. Allowed values are 500-4000000. Field introduced in 20.1.1.
   * @return mintx
  **/
  @Schema(description = "Default desired minimum transmit interval (in ms) used in BFD. Allowed values are 500-4000000. Field introduced in 20.1.1.")
  public Integer getMintx() {
    return mintx;
  }

  public void setMintx(Integer mintx) {
    this.mintx = mintx;
  }

  public BfdProfile multi(Integer multi) {
    this.multi = multi;
    return this;
  }

   /**
   * Default detection multiplier used in BFD. Allowed values are 3-255. Field introduced in 20.1.1.
   * @return multi
  **/
  @Schema(description = "Default detection multiplier used in BFD. Allowed values are 3-255. Field introduced in 20.1.1.")
  public Integer getMulti() {
    return multi;
  }

  public void setMulti(Integer multi) {
    this.multi = multi;
  }


  @Override
  public boolean equals(java.lang.Object o) {
    if (this == o) {
      return true;
    }
    if (o == null || getClass() != o.getClass()) {
      return false;
    }
    BfdProfile bfdProfile = (BfdProfile) o;
    return Objects.equals(this.minrx, bfdProfile.minrx) &&
        Objects.equals(this.mintx, bfdProfile.mintx) &&
        Objects.equals(this.multi, bfdProfile.multi);
  }

  @Override
  public int hashCode() {
    return Objects.hash(minrx, mintx, multi);
  }


  @Override
  public String toString() {
    StringBuilder sb = new StringBuilder();
    sb.append("class BfdProfile {\n");
    
    sb.append("    minrx: ").append(toIndentedString(minrx)).append("\n");
    sb.append("    mintx: ").append(toIndentedString(mintx)).append("\n");
    sb.append("    multi: ").append(toIndentedString(multi)).append("\n");
    sb.append("}");
    return sb.toString();
  }

  /**
   * Convert the given object to string with each line indented by 4 spaces
   * (except the first line).
   */
  private String toIndentedString(java.lang.Object o) {
    if (o == null) {
      return "null";
    }
    return o.toString().replace("\n", "\n    ");
  }

}
