/*
 * Avi avi_global_spec Object API
 * No description provided (generated by Swagger Codegen https://github.com/swagger-api/swagger-codegen)
 *
 * OpenAPI spec version: 20.1.1
 * Contact: support@avinetworks.com
 *
 * NOTE: This class is auto generated by the swagger code generator program.
 * https://github.com/swagger-api/swagger-codegen.git
 * Do not edit the class manually.
 */

package com.vmware.avi.sdk.model;

import java.util.Objects;
import java.util.Arrays;
import com.fasterxml.jackson.annotation.JsonProperty;
import com.fasterxml.jackson.annotation.JsonCreator;
import com.fasterxml.jackson.annotation.JsonValue;
import io.swagger.v3.oas.annotations.media.Schema;
/**
 * CaptureFileSize
 */

@javax.annotation.Generated(value = "io.swagger.codegen.v3.generators.java.JavaClientCodegen", date = "2020-03-12T12:27:26.755+05:30[Asia/Kolkata]")
public class CaptureFileSize {
  @JsonProperty("absolute_size")
  private Integer absoluteSize = null;

  @JsonProperty("percentage_size")
  private Integer percentageSize = null;

  public CaptureFileSize absoluteSize(Integer absoluteSize) {
    this.absoluteSize = absoluteSize;
    return this;
  }

   /**
   * Maximum size in MB. Set 0 for avi default size. Allowed values are 100-512000. Special values are 0 - &#x27;AVI_DEFAULT&#x27;.
   * @return absoluteSize
  **/
  @Schema(description = "Maximum size in MB. Set 0 for avi default size. Allowed values are 100-512000. Special values are 0 - 'AVI_DEFAULT'.")
  public Integer getAbsoluteSize() {
    return absoluteSize;
  }

  public void setAbsoluteSize(Integer absoluteSize) {
    this.absoluteSize = absoluteSize;
  }

  public CaptureFileSize percentageSize(Integer percentageSize) {
    this.percentageSize = percentageSize;
    return this;
  }

   /**
   * Limits capture to percentage of free disk space. Set 0 for avi default size. Allowed values are 0-75.
   * @return percentageSize
  **/
  @Schema(description = "Limits capture to percentage of free disk space. Set 0 for avi default size. Allowed values are 0-75.")
  public Integer getPercentageSize() {
    return percentageSize;
  }

  public void setPercentageSize(Integer percentageSize) {
    this.percentageSize = percentageSize;
  }


  @Override
  public boolean equals(java.lang.Object o) {
    if (this == o) {
      return true;
    }
    if (o == null || getClass() != o.getClass()) {
      return false;
    }
    CaptureFileSize captureFileSize = (CaptureFileSize) o;
    return Objects.equals(this.absoluteSize, captureFileSize.absoluteSize) &&
        Objects.equals(this.percentageSize, captureFileSize.percentageSize);
  }

  @Override
  public int hashCode() {
    return Objects.hash(absoluteSize, percentageSize);
  }


  @Override
  public String toString() {
    StringBuilder sb = new StringBuilder();
    sb.append("class CaptureFileSize {\n");
    
    sb.append("    absoluteSize: ").append(toIndentedString(absoluteSize)).append("\n");
    sb.append("    percentageSize: ").append(toIndentedString(percentageSize)).append("\n");
    sb.append("}");
    return sb.toString();
  }

  /**
   * Convert the given object to string with each line indented by 4 spaces
   * (except the first line).
   */
  private String toIndentedString(java.lang.Object o) {
    if (o == null) {
      return "null";
    }
    return o.toString().replace("\n", "\n    ");
  }

}
