/*
 * Avi avi_global_spec Object API
 * No description provided (generated by Swagger Codegen https://github.com/swagger-api/swagger-codegen)
 *
 * OpenAPI spec version: 20.1.1
 * Contact: support@avinetworks.com
 *
 * NOTE: This class is auto generated by the swagger code generator program.
 * https://github.com/swagger-api/swagger-codegen.git
 * Do not edit the class manually.
 */

package com.vmware.avi.sdk.model;

import java.util.Objects;
import java.util.Arrays;
import com.fasterxml.jackson.annotation.JsonProperty;
import com.fasterxml.jackson.annotation.JsonCreator;
import com.fasterxml.jackson.annotation.JsonValue;
import io.swagger.v3.oas.annotations.media.Schema;
/**
 * CloudStackConfiguration
 */

@javax.annotation.Generated(value = "io.swagger.codegen.v3.generators.java.JavaClientCodegen", date = "2020-03-12T12:27:26.755+05:30[Asia/Kolkata]")
public class CloudStackConfiguration {
  @JsonProperty("access_key_id")
  private String accessKeyId = null;

  @JsonProperty("api_url")
  private String apiUrl = null;

  @JsonProperty("cntr_public_ip")
  private String cntrPublicIp = null;

  @JsonProperty("hypervisor")
  private String hypervisor = "KVM";

  @JsonProperty("mgmt_network_name")
  private String mgmtNetworkName = null;

  @JsonProperty("mgmt_network_uuid")
  private String mgmtNetworkUuid = null;

  @JsonProperty("secret_access_key")
  private String secretAccessKey = null;

  public CloudStackConfiguration accessKeyId(String accessKeyId) {
    this.accessKeyId = accessKeyId;
    return this;
  }

   /**
   * CloudStack API Key.
   * @return accessKeyId
  **/
  @Schema(required = true, description = "CloudStack API Key.")
  public String getAccessKeyId() {
    return accessKeyId;
  }

  public void setAccessKeyId(String accessKeyId) {
    this.accessKeyId = accessKeyId;
  }

  public CloudStackConfiguration apiUrl(String apiUrl) {
    this.apiUrl = apiUrl;
    return this;
  }

   /**
   * CloudStack API URL.
   * @return apiUrl
  **/
  @Schema(required = true, description = "CloudStack API URL.")
  public String getApiUrl() {
    return apiUrl;
  }

  public void setApiUrl(String apiUrl) {
    this.apiUrl = apiUrl;
  }

  public CloudStackConfiguration cntrPublicIp(String cntrPublicIp) {
    this.cntrPublicIp = cntrPublicIp;
    return this;
  }

   /**
   * If controller&#x27;s management IP is in a private network, a publicly accessible IP to reach the controller.
   * @return cntrPublicIp
  **/
  @Schema(description = "If controller's management IP is in a private network, a publicly accessible IP to reach the controller.")
  public String getCntrPublicIp() {
    return cntrPublicIp;
  }

  public void setCntrPublicIp(String cntrPublicIp) {
    this.cntrPublicIp = cntrPublicIp;
  }

  public CloudStackConfiguration hypervisor(String hypervisor) {
    this.hypervisor = hypervisor;
    return this;
  }

   /**
   * Default hypervisor type. Enum options - DEFAULT, VMWARE_ESX, KVM, VMWARE_VSAN, XEN.
   * @return hypervisor
  **/
  @Schema(description = "Default hypervisor type. Enum options - DEFAULT, VMWARE_ESX, KVM, VMWARE_VSAN, XEN.")
  public String getHypervisor() {
    return hypervisor;
  }

  public void setHypervisor(String hypervisor) {
    this.hypervisor = hypervisor;
  }

  public CloudStackConfiguration mgmtNetworkName(String mgmtNetworkName) {
    this.mgmtNetworkName = mgmtNetworkName;
    return this;
  }

   /**
   * Avi Management network name.
   * @return mgmtNetworkName
  **/
  @Schema(required = true, description = "Avi Management network name.")
  public String getMgmtNetworkName() {
    return mgmtNetworkName;
  }

  public void setMgmtNetworkName(String mgmtNetworkName) {
    this.mgmtNetworkName = mgmtNetworkName;
  }

  public CloudStackConfiguration mgmtNetworkUuid(String mgmtNetworkUuid) {
    this.mgmtNetworkUuid = mgmtNetworkUuid;
    return this;
  }

   /**
   * Avi Management network name.
   * @return mgmtNetworkUuid
  **/
  @Schema(description = "Avi Management network name.")
  public String getMgmtNetworkUuid() {
    return mgmtNetworkUuid;
  }

  public void setMgmtNetworkUuid(String mgmtNetworkUuid) {
    this.mgmtNetworkUuid = mgmtNetworkUuid;
  }

  public CloudStackConfiguration secretAccessKey(String secretAccessKey) {
    this.secretAccessKey = secretAccessKey;
    return this;
  }

   /**
   * CloudStack Secret Key.
   * @return secretAccessKey
  **/
  @Schema(required = true, description = "CloudStack Secret Key.")
  public String getSecretAccessKey() {
    return secretAccessKey;
  }

  public void setSecretAccessKey(String secretAccessKey) {
    this.secretAccessKey = secretAccessKey;
  }


  @Override
  public boolean equals(java.lang.Object o) {
    if (this == o) {
      return true;
    }
    if (o == null || getClass() != o.getClass()) {
      return false;
    }
    CloudStackConfiguration cloudStackConfiguration = (CloudStackConfiguration) o;
    return Objects.equals(this.accessKeyId, cloudStackConfiguration.accessKeyId) &&
        Objects.equals(this.apiUrl, cloudStackConfiguration.apiUrl) &&
        Objects.equals(this.cntrPublicIp, cloudStackConfiguration.cntrPublicIp) &&
        Objects.equals(this.hypervisor, cloudStackConfiguration.hypervisor) &&
        Objects.equals(this.mgmtNetworkName, cloudStackConfiguration.mgmtNetworkName) &&
        Objects.equals(this.mgmtNetworkUuid, cloudStackConfiguration.mgmtNetworkUuid) &&
        Objects.equals(this.secretAccessKey, cloudStackConfiguration.secretAccessKey);
  }

  @Override
  public int hashCode() {
    return Objects.hash(accessKeyId, apiUrl, cntrPublicIp, hypervisor, mgmtNetworkName, mgmtNetworkUuid, secretAccessKey);
  }


  @Override
  public String toString() {
    StringBuilder sb = new StringBuilder();
    sb.append("class CloudStackConfiguration {\n");
    
    sb.append("    accessKeyId: ").append(toIndentedString(accessKeyId)).append("\n");
    sb.append("    apiUrl: ").append(toIndentedString(apiUrl)).append("\n");
    sb.append("    cntrPublicIp: ").append(toIndentedString(cntrPublicIp)).append("\n");
    sb.append("    hypervisor: ").append(toIndentedString(hypervisor)).append("\n");
    sb.append("    mgmtNetworkName: ").append(toIndentedString(mgmtNetworkName)).append("\n");
    sb.append("    mgmtNetworkUuid: ").append(toIndentedString(mgmtNetworkUuid)).append("\n");
    sb.append("    secretAccessKey: ").append(toIndentedString(secretAccessKey)).append("\n");
    sb.append("}");
    return sb.toString();
  }

  /**
   * Convert the given object to string with each line indented by 4 spaces
   * (except the first line).
   */
  private String toIndentedString(java.lang.Object o) {
    if (o == null) {
      return "null";
    }
    return o.toString().replace("\n", "\n    ");
  }

}
