/*
 * Avi avi_global_spec Object API
 * No description provided (generated by Swagger Codegen https://github.com/swagger-api/swagger-codegen)
 *
 * OpenAPI spec version: 20.1.1
 * Contact: support@avinetworks.com
 *
 * NOTE: This class is auto generated by the swagger code generator program.
 * https://github.com/swagger-api/swagger-codegen.git
 * Do not edit the class manually.
 */

package com.vmware.avi.sdk.model;

import java.util.Objects;
import java.util.Arrays;
import com.fasterxml.jackson.annotation.JsonProperty;
import com.fasterxml.jackson.annotation.JsonCreator;
import com.fasterxml.jackson.annotation.JsonValue;
import com.vmware.avi.sdk.model.AzureClusterInfo;
import io.swagger.v3.oas.annotations.media.Schema;
/**
 * ClusterCloudDetails
 */

@javax.annotation.Generated(value = "io.swagger.codegen.v3.generators.java.JavaClientCodegen", date = "2020-03-12T12:27:26.755+05:30[Asia/Kolkata]")
public class ClusterCloudDetails {
  @JsonProperty("_last_modified")
  private String _lastModified = null;

  @JsonProperty("azure_info")
  private AzureClusterInfo azureInfo = null;

  @JsonProperty("name")
  private String name = null;

  @JsonProperty("tenant_ref")
  private String tenantRef = null;

  @JsonProperty("url")
  private String url = null;

  @JsonProperty("uuid")
  private String uuid = null;

   /**
   * UNIX time since epoch in microseconds. Units(MICROSECONDS).
   * @return _lastModified
  **/
  @Schema(description = "UNIX time since epoch in microseconds. Units(MICROSECONDS).")
  public String getLastModified() {
    return _lastModified;
  }

  public ClusterCloudDetails azureInfo(AzureClusterInfo azureInfo) {
    this.azureInfo = azureInfo;
    return this;
  }

   /**
   * Get azureInfo
   * @return azureInfo
  **/
  @Schema(description = "")
  public AzureClusterInfo getAzureInfo() {
    return azureInfo;
  }

  public void setAzureInfo(AzureClusterInfo azureInfo) {
    this.azureInfo = azureInfo;
  }

  public ClusterCloudDetails name(String name) {
    this.name = name;
    return this;
  }

   /**
   *  Field introduced in 17.2.5.
   * @return name
  **/
  @Schema(required = true, description = " Field introduced in 17.2.5.")
  public String getName() {
    return name;
  }

  public void setName(String name) {
    this.name = name;
  }

  public ClusterCloudDetails tenantRef(String tenantRef) {
    this.tenantRef = tenantRef;
    return this;
  }

   /**
   *  It is a reference to an object of type Tenant. Field introduced in 17.2.5.
   * @return tenantRef
  **/
  @Schema(description = " It is a reference to an object of type Tenant. Field introduced in 17.2.5.")
  public String getTenantRef() {
    return tenantRef;
  }

  public void setTenantRef(String tenantRef) {
    this.tenantRef = tenantRef;
  }

   /**
   * url
   * @return url
  **/
  @Schema(description = "url")
  public String getUrl() {
    return url;
  }

  public ClusterCloudDetails uuid(String uuid) {
    this.uuid = uuid;
    return this;
  }

   /**
   *  Field introduced in 17.2.5.
   * @return uuid
  **/
  @Schema(description = " Field introduced in 17.2.5.")
  public String getUuid() {
    return uuid;
  }

  public void setUuid(String uuid) {
    this.uuid = uuid;
  }


  @Override
  public boolean equals(java.lang.Object o) {
    if (this == o) {
      return true;
    }
    if (o == null || getClass() != o.getClass()) {
      return false;
    }
    ClusterCloudDetails clusterCloudDetails = (ClusterCloudDetails) o;
    return Objects.equals(this._lastModified, clusterCloudDetails._lastModified) &&
        Objects.equals(this.azureInfo, clusterCloudDetails.azureInfo) &&
        Objects.equals(this.name, clusterCloudDetails.name) &&
        Objects.equals(this.tenantRef, clusterCloudDetails.tenantRef) &&
        Objects.equals(this.url, clusterCloudDetails.url) &&
        Objects.equals(this.uuid, clusterCloudDetails.uuid);
  }

  @Override
  public int hashCode() {
    return Objects.hash(_lastModified, azureInfo, name, tenantRef, url, uuid);
  }


  @Override
  public String toString() {
    StringBuilder sb = new StringBuilder();
    sb.append("class ClusterCloudDetails {\n");
    
    sb.append("    _lastModified: ").append(toIndentedString(_lastModified)).append("\n");
    sb.append("    azureInfo: ").append(toIndentedString(azureInfo)).append("\n");
    sb.append("    name: ").append(toIndentedString(name)).append("\n");
    sb.append("    tenantRef: ").append(toIndentedString(tenantRef)).append("\n");
    sb.append("    url: ").append(toIndentedString(url)).append("\n");
    sb.append("    uuid: ").append(toIndentedString(uuid)).append("\n");
    sb.append("}");
    return sb.toString();
  }

  /**
   * Convert the given object to string with each line indented by 4 spaces
   * (except the first line).
   */
  private String toIndentedString(java.lang.Object o) {
    if (o == null) {
      return "null";
    }
    return o.toString().replace("\n", "\n    ");
  }

}
