/*
 * Avi avi_global_spec Object API
 * No description provided (generated by Swagger Codegen https://github.com/swagger-api/swagger-codegen)
 *
 * OpenAPI spec version: 20.1.1
 * Contact: support@avinetworks.com
 *
 * NOTE: This class is auto generated by the swagger code generator program.
 * https://github.com/swagger-api/swagger-codegen.git
 * Do not edit the class manually.
 */

package com.vmware.avi.sdk.model;

import java.util.Objects;
import java.util.Arrays;
import com.fasterxml.jackson.annotation.JsonProperty;
import com.fasterxml.jackson.annotation.JsonCreator;
import com.fasterxml.jackson.annotation.JsonValue;
import com.vmware.avi.sdk.model.IpAddr;
import com.vmware.avi.sdk.model.IpAddrPrefix;
import com.vmware.avi.sdk.model.IpAddrRange;
import io.swagger.v3.oas.annotations.media.Schema;
import java.util.ArrayList;
import java.util.List;
/**
 * CompressionFilter
 */

@javax.annotation.Generated(value = "io.swagger.codegen.v3.generators.java.JavaClientCodegen", date = "2020-03-12T12:27:26.755+05:30[Asia/Kolkata]")
public class CompressionFilter {
  @JsonProperty("devices_ref")
  private String devicesRef = null;

  @JsonProperty("index")
  private Integer index = null;

  @JsonProperty("ip_addr_prefixes")
  private List<IpAddrPrefix> ipAddrPrefixes = null;

  @JsonProperty("ip_addr_ranges")
  private List<IpAddrRange> ipAddrRanges = null;

  @JsonProperty("ip_addrs")
  private List<IpAddr> ipAddrs = null;

  @JsonProperty("ip_addrs_ref")
  private String ipAddrsRef = null;

  @JsonProperty("level")
  private String level = "NORMAL_COMPRESSION";

  @JsonProperty("match")
  private String match = "IS_IN";

  @JsonProperty("name")
  private String name = null;

  @JsonProperty("user_agent")
  private List<String> userAgent = null;

  public CompressionFilter devicesRef(String devicesRef) {
    this.devicesRef = devicesRef;
    return this;
  }

   /**
   *  It is a reference to an object of type StringGroup.
   * @return devicesRef
  **/
  @Schema(description = " It is a reference to an object of type StringGroup.")
  public String getDevicesRef() {
    return devicesRef;
  }

  public void setDevicesRef(String devicesRef) {
    this.devicesRef = devicesRef;
  }

  public CompressionFilter index(Integer index) {
    this.index = index;
    return this;
  }

   /**
   * Number of index.
   * @return index
  **/
  @Schema(required = true, description = "Number of index.")
  public Integer getIndex() {
    return index;
  }

  public void setIndex(Integer index) {
    this.index = index;
  }

  public CompressionFilter ipAddrPrefixes(List<IpAddrPrefix> ipAddrPrefixes) {
    this.ipAddrPrefixes = ipAddrPrefixes;
    return this;
  }

  public CompressionFilter addIpAddrPrefixesItem(IpAddrPrefix ipAddrPrefixesItem) {
    if (this.ipAddrPrefixes == null) {
      this.ipAddrPrefixes = new ArrayList<IpAddrPrefix>();
    }
    this.ipAddrPrefixes.add(ipAddrPrefixesItem);
    return this;
  }

   /**
   * Placeholder for description of property ip_addr_prefixes of obj type CompressionFilter field type str  type object
   * @return ipAddrPrefixes
  **/
  @Schema(description = "Placeholder for description of property ip_addr_prefixes of obj type CompressionFilter field type str  type object")
  public List<IpAddrPrefix> getIpAddrPrefixes() {
    return ipAddrPrefixes;
  }

  public void setIpAddrPrefixes(List<IpAddrPrefix> ipAddrPrefixes) {
    this.ipAddrPrefixes = ipAddrPrefixes;
  }

  public CompressionFilter ipAddrRanges(List<IpAddrRange> ipAddrRanges) {
    this.ipAddrRanges = ipAddrRanges;
    return this;
  }

  public CompressionFilter addIpAddrRangesItem(IpAddrRange ipAddrRangesItem) {
    if (this.ipAddrRanges == null) {
      this.ipAddrRanges = new ArrayList<IpAddrRange>();
    }
    this.ipAddrRanges.add(ipAddrRangesItem);
    return this;
  }

   /**
   * Placeholder for description of property ip_addr_ranges of obj type CompressionFilter field type str  type object
   * @return ipAddrRanges
  **/
  @Schema(description = "Placeholder for description of property ip_addr_ranges of obj type CompressionFilter field type str  type object")
  public List<IpAddrRange> getIpAddrRanges() {
    return ipAddrRanges;
  }

  public void setIpAddrRanges(List<IpAddrRange> ipAddrRanges) {
    this.ipAddrRanges = ipAddrRanges;
  }

  public CompressionFilter ipAddrs(List<IpAddr> ipAddrs) {
    this.ipAddrs = ipAddrs;
    return this;
  }

  public CompressionFilter addIpAddrsItem(IpAddr ipAddrsItem) {
    if (this.ipAddrs == null) {
      this.ipAddrs = new ArrayList<IpAddr>();
    }
    this.ipAddrs.add(ipAddrsItem);
    return this;
  }

   /**
   * Placeholder for description of property ip_addrs of obj type CompressionFilter field type str  type object
   * @return ipAddrs
  **/
  @Schema(description = "Placeholder for description of property ip_addrs of obj type CompressionFilter field type str  type object")
  public List<IpAddr> getIpAddrs() {
    return ipAddrs;
  }

  public void setIpAddrs(List<IpAddr> ipAddrs) {
    this.ipAddrs = ipAddrs;
  }

  public CompressionFilter ipAddrsRef(String ipAddrsRef) {
    this.ipAddrsRef = ipAddrsRef;
    return this;
  }

   /**
   *  It is a reference to an object of type IpAddrGroup.
   * @return ipAddrsRef
  **/
  @Schema(description = " It is a reference to an object of type IpAddrGroup.")
  public String getIpAddrsRef() {
    return ipAddrsRef;
  }

  public void setIpAddrsRef(String ipAddrsRef) {
    this.ipAddrsRef = ipAddrsRef;
  }

  public CompressionFilter level(String level) {
    this.level = level;
    return this;
  }

   /**
   *  Enum options - AGGRESSIVE_COMPRESSION, NORMAL_COMPRESSION, NO_COMPRESSION.
   * @return level
  **/
  @Schema(required = true, description = " Enum options - AGGRESSIVE_COMPRESSION, NORMAL_COMPRESSION, NO_COMPRESSION.")
  public String getLevel() {
    return level;
  }

  public void setLevel(String level) {
    this.level = level;
  }

  public CompressionFilter match(String match) {
    this.match = match;
    return this;
  }

   /**
   * Whether to apply Filter when group criteria is matched or not. Enum options - IS_IN, IS_NOT_IN.
   * @return match
  **/
  @Schema(description = "Whether to apply Filter when group criteria is matched or not. Enum options - IS_IN, IS_NOT_IN.")
  public String getMatch() {
    return match;
  }

  public void setMatch(String match) {
    this.match = match;
  }

  public CompressionFilter name(String name) {
    this.name = name;
    return this;
  }

   /**
   * Name of the object.
   * @return name
  **/
  @Schema(required = true, description = "Name of the object.")
  public String getName() {
    return name;
  }

  public void setName(String name) {
    this.name = name;
  }

  public CompressionFilter userAgent(List<String> userAgent) {
    this.userAgent = userAgent;
    return this;
  }

  public CompressionFilter addUserAgentItem(String userAgentItem) {
    if (this.userAgent == null) {
      this.userAgent = new ArrayList<String>();
    }
    this.userAgent.add(userAgentItem);
    return this;
  }

   /**
   * user_agent of CompressionFilter.
   * @return userAgent
  **/
  @Schema(description = "user_agent of CompressionFilter.")
  public List<String> getUserAgent() {
    return userAgent;
  }

  public void setUserAgent(List<String> userAgent) {
    this.userAgent = userAgent;
  }


  @Override
  public boolean equals(java.lang.Object o) {
    if (this == o) {
      return true;
    }
    if (o == null || getClass() != o.getClass()) {
      return false;
    }
    CompressionFilter compressionFilter = (CompressionFilter) o;
    return Objects.equals(this.devicesRef, compressionFilter.devicesRef) &&
        Objects.equals(this.index, compressionFilter.index) &&
        Objects.equals(this.ipAddrPrefixes, compressionFilter.ipAddrPrefixes) &&
        Objects.equals(this.ipAddrRanges, compressionFilter.ipAddrRanges) &&
        Objects.equals(this.ipAddrs, compressionFilter.ipAddrs) &&
        Objects.equals(this.ipAddrsRef, compressionFilter.ipAddrsRef) &&
        Objects.equals(this.level, compressionFilter.level) &&
        Objects.equals(this.match, compressionFilter.match) &&
        Objects.equals(this.name, compressionFilter.name) &&
        Objects.equals(this.userAgent, compressionFilter.userAgent);
  }

  @Override
  public int hashCode() {
    return Objects.hash(devicesRef, index, ipAddrPrefixes, ipAddrRanges, ipAddrs, ipAddrsRef, level, match, name, userAgent);
  }


  @Override
  public String toString() {
    StringBuilder sb = new StringBuilder();
    sb.append("class CompressionFilter {\n");
    
    sb.append("    devicesRef: ").append(toIndentedString(devicesRef)).append("\n");
    sb.append("    index: ").append(toIndentedString(index)).append("\n");
    sb.append("    ipAddrPrefixes: ").append(toIndentedString(ipAddrPrefixes)).append("\n");
    sb.append("    ipAddrRanges: ").append(toIndentedString(ipAddrRanges)).append("\n");
    sb.append("    ipAddrs: ").append(toIndentedString(ipAddrs)).append("\n");
    sb.append("    ipAddrsRef: ").append(toIndentedString(ipAddrsRef)).append("\n");
    sb.append("    level: ").append(toIndentedString(level)).append("\n");
    sb.append("    match: ").append(toIndentedString(match)).append("\n");
    sb.append("    name: ").append(toIndentedString(name)).append("\n");
    sb.append("    userAgent: ").append(toIndentedString(userAgent)).append("\n");
    sb.append("}");
    return sb.toString();
  }

  /**
   * Convert the given object to string with each line indented by 4 spaces
   * (except the first line).
   */
  private String toIndentedString(java.lang.Object o) {
    if (o == null) {
      return "null";
    }
    return o.toString().replace("\n", "\n    ");
  }

}
