/*
 * Avi avi_global_spec Object API
 * No description provided (generated by Swagger Codegen https://github.com/swagger-api/swagger-codegen)
 *
 * OpenAPI spec version: 20.1.1
 * Contact: support@avinetworks.com
 *
 * NOTE: This class is auto generated by the swagger code generator program.
 * https://github.com/swagger-api/swagger-codegen.git
 * Do not edit the class manually.
 */

package com.vmware.avi.sdk.model;

import java.util.Objects;
import java.util.Arrays;
import com.fasterxml.jackson.annotation.JsonProperty;
import com.fasterxml.jackson.annotation.JsonCreator;
import com.fasterxml.jackson.annotation.JsonValue;
import io.swagger.v3.oas.annotations.media.Schema;
/**
 * ControllerPortalAuth
 */

@javax.annotation.Generated(value = "io.swagger.codegen.v3.generators.java.JavaClientCodegen", date = "2020-03-12T12:27:26.755+05:30[Asia/Kolkata]")
public class ControllerPortalAuth {
  @JsonProperty("access_token")
  private String accessToken = null;

  @JsonProperty("instance_url")
  private String instanceUrl = null;

  @JsonProperty("jwt_token")
  private String jwtToken = null;

  public ControllerPortalAuth accessToken(String accessToken) {
    this.accessToken = accessToken;
    return this;
  }

   /**
   * Access Token to authenticate Customer Portal REST calls. Field introduced in 18.2.6.
   * @return accessToken
  **/
  @Schema(description = "Access Token to authenticate Customer Portal REST calls. Field introduced in 18.2.6.")
  public String getAccessToken() {
    return accessToken;
  }

  public void setAccessToken(String accessToken) {
    this.accessToken = accessToken;
  }

  public ControllerPortalAuth instanceUrl(String instanceUrl) {
    this.instanceUrl = instanceUrl;
    return this;
  }

   /**
   * Salesforce instance URL. Field introduced in 18.2.6.
   * @return instanceUrl
  **/
  @Schema(description = "Salesforce instance URL. Field introduced in 18.2.6.")
  public String getInstanceUrl() {
    return instanceUrl;
  }

  public void setInstanceUrl(String instanceUrl) {
    this.instanceUrl = instanceUrl;
  }

  public ControllerPortalAuth jwtToken(String jwtToken) {
    this.jwtToken = jwtToken;
    return this;
  }

   /**
   * Signed JWT to refresh the access token. Field introduced in 18.2.6.
   * @return jwtToken
  **/
  @Schema(description = "Signed JWT to refresh the access token. Field introduced in 18.2.6.")
  public String getJwtToken() {
    return jwtToken;
  }

  public void setJwtToken(String jwtToken) {
    this.jwtToken = jwtToken;
  }


  @Override
  public boolean equals(java.lang.Object o) {
    if (this == o) {
      return true;
    }
    if (o == null || getClass() != o.getClass()) {
      return false;
    }
    ControllerPortalAuth controllerPortalAuth = (ControllerPortalAuth) o;
    return Objects.equals(this.accessToken, controllerPortalAuth.accessToken) &&
        Objects.equals(this.instanceUrl, controllerPortalAuth.instanceUrl) &&
        Objects.equals(this.jwtToken, controllerPortalAuth.jwtToken);
  }

  @Override
  public int hashCode() {
    return Objects.hash(accessToken, instanceUrl, jwtToken);
  }


  @Override
  public String toString() {
    StringBuilder sb = new StringBuilder();
    sb.append("class ControllerPortalAuth {\n");
    
    sb.append("    accessToken: ").append(toIndentedString(accessToken)).append("\n");
    sb.append("    instanceUrl: ").append(toIndentedString(instanceUrl)).append("\n");
    sb.append("    jwtToken: ").append(toIndentedString(jwtToken)).append("\n");
    sb.append("}");
    return sb.toString();
  }

  /**
   * Convert the given object to string with each line indented by 4 spaces
   * (except the first line).
   */
  private String toIndentedString(java.lang.Object o) {
    if (o == null) {
      return "null";
    }
    return o.toString().replace("\n", "\n    ");
  }

}
