/*
 * Avi avi_global_spec Object API
 * No description provided (generated by Swagger Codegen https://github.com/swagger-api/swagger-codegen)
 *
 * OpenAPI spec version: 20.1.1
 * Contact: support@avinetworks.com
 *
 * NOTE: This class is auto generated by the swagger code generator program.
 * https://github.com/swagger-api/swagger-codegen.git
 * Do not edit the class manually.
 */

package com.vmware.avi.sdk.model;

import java.util.Objects;
import java.util.Arrays;
import com.fasterxml.jackson.annotation.JsonProperty;
import com.fasterxml.jackson.annotation.JsonCreator;
import com.fasterxml.jackson.annotation.JsonValue;
import com.vmware.avi.sdk.model.DnsRuleDnsRrSet;
import io.swagger.v3.oas.annotations.media.Schema;
import java.util.ArrayList;
import java.util.List;
/**
 * DnsRuleActionResponse
 */

@javax.annotation.Generated(value = "io.swagger.codegen.v3.generators.java.JavaClientCodegen", date = "2020-03-12T12:27:26.755+05:30[Asia/Kolkata]")
public class DnsRuleActionResponse {
  @JsonProperty("authoritative")
  private Boolean authoritative = true;

  @JsonProperty("rcode")
  private String rcode = "DNS_RCODE_NOERROR";

  @JsonProperty("resource_record_sets")
  private List<DnsRuleDnsRrSet> resourceRecordSets = null;

  @JsonProperty("truncation")
  private Boolean truncation = null;

  public DnsRuleActionResponse authoritative(Boolean authoritative) {
    this.authoritative = authoritative;
    return this;
  }

   /**
   * DNS response is authoritative. Field introduced in 17.1.1.
   * @return authoritative
  **/
  @Schema(description = "DNS response is authoritative. Field introduced in 17.1.1.")
  public Boolean isAuthoritative() {
    return authoritative;
  }

  public void setAuthoritative(Boolean authoritative) {
    this.authoritative = authoritative;
  }

  public DnsRuleActionResponse rcode(String rcode) {
    this.rcode = rcode;
    return this;
  }

   /**
   * DNS response code. Enum options - DNS_RCODE_NOERROR, DNS_RCODE_FORMERR, DNS_RCODE_SERVFAIL, DNS_RCODE_NXDOMAIN, DNS_RCODE_NOTIMP, DNS_RCODE_REFUSED, DNS_RCODE_YXDOMAIN, DNS_RCODE_YXRRSET, DNS_RCODE_NXRRSET, DNS_RCODE_NOTAUTH, DNS_RCODE_NOTZONE. Field introduced in 17.1.1.
   * @return rcode
  **/
  @Schema(description = "DNS response code. Enum options - DNS_RCODE_NOERROR, DNS_RCODE_FORMERR, DNS_RCODE_SERVFAIL, DNS_RCODE_NXDOMAIN, DNS_RCODE_NOTIMP, DNS_RCODE_REFUSED, DNS_RCODE_YXDOMAIN, DNS_RCODE_YXRRSET, DNS_RCODE_NXRRSET, DNS_RCODE_NOTAUTH, DNS_RCODE_NOTZONE. Field introduced in 17.1.1.")
  public String getRcode() {
    return rcode;
  }

  public void setRcode(String rcode) {
    this.rcode = rcode;
  }

  public DnsRuleActionResponse resourceRecordSets(List<DnsRuleDnsRrSet> resourceRecordSets) {
    this.resourceRecordSets = resourceRecordSets;
    return this;
  }

  public DnsRuleActionResponse addResourceRecordSetsItem(DnsRuleDnsRrSet resourceRecordSetsItem) {
    if (this.resourceRecordSets == null) {
      this.resourceRecordSets = new ArrayList<DnsRuleDnsRrSet>();
    }
    this.resourceRecordSets.add(resourceRecordSetsItem);
    return this;
  }

   /**
   * DNS resource record sets - (resource record set share the DNS domain name, type, and class). Field introduced in 17.2.12, 18.1.2.
   * @return resourceRecordSets
  **/
  @Schema(description = "DNS resource record sets - (resource record set share the DNS domain name, type, and class). Field introduced in 17.2.12, 18.1.2.")
  public List<DnsRuleDnsRrSet> getResourceRecordSets() {
    return resourceRecordSets;
  }

  public void setResourceRecordSets(List<DnsRuleDnsRrSet> resourceRecordSets) {
    this.resourceRecordSets = resourceRecordSets;
  }

  public DnsRuleActionResponse truncation(Boolean truncation) {
    this.truncation = truncation;
    return this;
  }

   /**
   * DNS response is truncated. Field introduced in 17.1.1.
   * @return truncation
  **/
  @Schema(description = "DNS response is truncated. Field introduced in 17.1.1.")
  public Boolean isTruncation() {
    return truncation;
  }

  public void setTruncation(Boolean truncation) {
    this.truncation = truncation;
  }


  @Override
  public boolean equals(java.lang.Object o) {
    if (this == o) {
      return true;
    }
    if (o == null || getClass() != o.getClass()) {
      return false;
    }
    DnsRuleActionResponse dnsRuleActionResponse = (DnsRuleActionResponse) o;
    return Objects.equals(this.authoritative, dnsRuleActionResponse.authoritative) &&
        Objects.equals(this.rcode, dnsRuleActionResponse.rcode) &&
        Objects.equals(this.resourceRecordSets, dnsRuleActionResponse.resourceRecordSets) &&
        Objects.equals(this.truncation, dnsRuleActionResponse.truncation);
  }

  @Override
  public int hashCode() {
    return Objects.hash(authoritative, rcode, resourceRecordSets, truncation);
  }


  @Override
  public String toString() {
    StringBuilder sb = new StringBuilder();
    sb.append("class DnsRuleActionResponse {\n");
    
    sb.append("    authoritative: ").append(toIndentedString(authoritative)).append("\n");
    sb.append("    rcode: ").append(toIndentedString(rcode)).append("\n");
    sb.append("    resourceRecordSets: ").append(toIndentedString(resourceRecordSets)).append("\n");
    sb.append("    truncation: ").append(toIndentedString(truncation)).append("\n");
    sb.append("}");
    return sb.toString();
  }

  /**
   * Convert the given object to string with each line indented by 4 spaces
   * (except the first line).
   */
  private String toIndentedString(java.lang.Object o) {
    if (o == null) {
      return "null";
    }
    return o.toString().replace("\n", "\n    ");
  }

}
