/*
 * Avi avi_global_spec Object API
 * No description provided (generated by Swagger Codegen https://github.com/swagger-api/swagger-codegen)
 *
 * OpenAPI spec version: 20.1.1
 * Contact: support@avinetworks.com
 *
 * NOTE: This class is auto generated by the swagger code generator program.
 * https://github.com/swagger-api/swagger-codegen.git
 * Do not edit the class manually.
 */

package com.vmware.avi.sdk.model;

import java.util.Objects;
import java.util.Arrays;
import com.fasterxml.jackson.annotation.JsonProperty;
import com.fasterxml.jackson.annotation.JsonCreator;
import com.fasterxml.jackson.annotation.JsonValue;
import com.vmware.avi.sdk.model.IpAddrPrefix;
import io.swagger.v3.oas.annotations.media.Schema;
/**
 * FloatingIpSubnet
 */

@javax.annotation.Generated(value = "io.swagger.codegen.v3.generators.java.JavaClientCodegen", date = "2020-03-12T12:27:26.755+05:30[Asia/Kolkata]")
public class FloatingIpSubnet {
  @JsonProperty("name")
  private String name = null;

  @JsonProperty("prefix")
  private IpAddrPrefix prefix = null;

  @JsonProperty("uuid")
  private String uuid = null;

  public FloatingIpSubnet name(String name) {
    this.name = name;
    return this;
  }

   /**
   * FloatingIp subnet name if available, else uuid. Field introduced in 17.2.1.
   * @return name
  **/
  @Schema(required = true, description = "FloatingIp subnet name if available, else uuid. Field introduced in 17.2.1.")
  public String getName() {
    return name;
  }

  public void setName(String name) {
    this.name = name;
  }

  public FloatingIpSubnet prefix(IpAddrPrefix prefix) {
    this.prefix = prefix;
    return this;
  }

   /**
   * Get prefix
   * @return prefix
  **/
  @Schema(description = "")
  public IpAddrPrefix getPrefix() {
    return prefix;
  }

  public void setPrefix(IpAddrPrefix prefix) {
    this.prefix = prefix;
  }

  public FloatingIpSubnet uuid(String uuid) {
    this.uuid = uuid;
    return this;
  }

   /**
   * FloatingIp subnet uuid. Field introduced in 17.2.1.
   * @return uuid
  **/
  @Schema(description = "FloatingIp subnet uuid. Field introduced in 17.2.1.")
  public String getUuid() {
    return uuid;
  }

  public void setUuid(String uuid) {
    this.uuid = uuid;
  }


  @Override
  public boolean equals(java.lang.Object o) {
    if (this == o) {
      return true;
    }
    if (o == null || getClass() != o.getClass()) {
      return false;
    }
    FloatingIpSubnet floatingIpSubnet = (FloatingIpSubnet) o;
    return Objects.equals(this.name, floatingIpSubnet.name) &&
        Objects.equals(this.prefix, floatingIpSubnet.prefix) &&
        Objects.equals(this.uuid, floatingIpSubnet.uuid);
  }

  @Override
  public int hashCode() {
    return Objects.hash(name, prefix, uuid);
  }


  @Override
  public String toString() {
    StringBuilder sb = new StringBuilder();
    sb.append("class FloatingIpSubnet {\n");
    
    sb.append("    name: ").append(toIndentedString(name)).append("\n");
    sb.append("    prefix: ").append(toIndentedString(prefix)).append("\n");
    sb.append("    uuid: ").append(toIndentedString(uuid)).append("\n");
    sb.append("}");
    return sb.toString();
  }

  /**
   * Convert the given object to string with each line indented by 4 spaces
   * (except the first line).
   */
  private String toIndentedString(java.lang.Object o) {
    if (o == null) {
      return "null";
    }
    return o.toString().replace("\n", "\n    ");
  }

}
