/*
 * Avi avi_global_spec Object API
 * No description provided (generated by Swagger Codegen https://github.com/swagger-api/swagger-codegen)
 *
 * OpenAPI spec version: 20.1.1
 * Contact: support@avinetworks.com
 *
 * NOTE: This class is auto generated by the swagger code generator program.
 * https://github.com/swagger-api/swagger-codegen.git
 * Do not edit the class manually.
 */

package com.vmware.avi.sdk.model;

import java.util.Objects;
import java.util.Arrays;
import com.fasterxml.jackson.annotation.JsonProperty;
import com.fasterxml.jackson.annotation.JsonCreator;
import com.fasterxml.jackson.annotation.JsonValue;
import io.swagger.v3.oas.annotations.media.Schema;
/**
 * GslbGeoDbFile
 */

@javax.annotation.Generated(value = "io.swagger.codegen.v3.generators.java.JavaClientCodegen", date = "2020-03-12T12:27:26.755+05:30[Asia/Kolkata]")
public class GslbGeoDbFile {
  @JsonProperty("checksum")
  private String checksum = null;

  @JsonProperty("file_id")
  private String fileId = null;

  @JsonProperty("filename")
  private String filename = null;

  @JsonProperty("format")
  private String format = "GSLB_GEODB_FILE_FORMAT_AVI";

  @JsonProperty("timestamp")
  private Long timestamp = null;

   /**
   * File checksum is internally computed. Field introduced in 17.1.1.
   * @return checksum
  **/
  @Schema(description = "File checksum is internally computed. Field introduced in 17.1.1.")
  public String getChecksum() {
    return checksum;
  }

   /**
   * System internal identifier for the file. Field introduced in 17.1.1.
   * @return fileId
  **/
  @Schema(description = "System internal identifier for the file. Field introduced in 17.1.1.")
  public String getFileId() {
    return fileId;
  }

  public GslbGeoDbFile filename(String filename) {
    this.filename = filename;
    return this;
  }

   /**
   * Geodb Filename in the Avi supported formats. Field introduced in 17.1.1.
   * @return filename
  **/
  @Schema(description = "Geodb Filename in the Avi supported formats. Field introduced in 17.1.1.")
  public String getFilename() {
    return filename;
  }

  public void setFilename(String filename) {
    this.filename = filename;
  }

  public GslbGeoDbFile format(String format) {
    this.format = format;
    return this;
  }

   /**
   * This field indicates the file format. Enum options - GSLB_GEODB_FILE_FORMAT_AVI, GSLB_GEODB_FILE_FORMAT_MAXMIND_CITY. Field introduced in 17.1.1.
   * @return format
  **/
  @Schema(description = "This field indicates the file format. Enum options - GSLB_GEODB_FILE_FORMAT_AVI, GSLB_GEODB_FILE_FORMAT_MAXMIND_CITY. Field introduced in 17.1.1.")
  public String getFormat() {
    return format;
  }

  public void setFormat(String format) {
    this.format = format;
  }

   /**
   * Internal timestamp associated with the file. Field introduced in 17.1.1.
   * @return timestamp
  **/
  @Schema(description = "Internal timestamp associated with the file. Field introduced in 17.1.1.")
  public Long getTimestamp() {
    return timestamp;
  }


  @Override
  public boolean equals(java.lang.Object o) {
    if (this == o) {
      return true;
    }
    if (o == null || getClass() != o.getClass()) {
      return false;
    }
    GslbGeoDbFile gslbGeoDbFile = (GslbGeoDbFile) o;
    return Objects.equals(this.checksum, gslbGeoDbFile.checksum) &&
        Objects.equals(this.fileId, gslbGeoDbFile.fileId) &&
        Objects.equals(this.filename, gslbGeoDbFile.filename) &&
        Objects.equals(this.format, gslbGeoDbFile.format) &&
        Objects.equals(this.timestamp, gslbGeoDbFile.timestamp);
  }

  @Override
  public int hashCode() {
    return Objects.hash(checksum, fileId, filename, format, timestamp);
  }


  @Override
  public String toString() {
    StringBuilder sb = new StringBuilder();
    sb.append("class GslbGeoDbFile {\n");
    
    sb.append("    checksum: ").append(toIndentedString(checksum)).append("\n");
    sb.append("    fileId: ").append(toIndentedString(fileId)).append("\n");
    sb.append("    filename: ").append(toIndentedString(filename)).append("\n");
    sb.append("    format: ").append(toIndentedString(format)).append("\n");
    sb.append("    timestamp: ").append(toIndentedString(timestamp)).append("\n");
    sb.append("}");
    return sb.toString();
  }

  /**
   * Convert the given object to string with each line indented by 4 spaces
   * (except the first line).
   */
  private String toIndentedString(java.lang.Object o) {
    if (o == null) {
      return "null";
    }
    return o.toString().replace("\n", "\n    ");
  }

}
