/*
 * Avi avi_global_spec Object API
 * No description provided (generated by Swagger Codegen https://github.com/swagger-api/swagger-codegen)
 *
 * OpenAPI spec version: 20.1.1
 * Contact: support@avinetworks.com
 *
 * NOTE: This class is auto generated by the swagger code generator program.
 * https://github.com/swagger-api/swagger-codegen.git
 * Do not edit the class manually.
 */

package com.vmware.avi.sdk.model;

import java.util.Objects;
import java.util.Arrays;
import com.fasterxml.jackson.annotation.JsonProperty;
import com.fasterxml.jackson.annotation.JsonCreator;
import com.fasterxml.jackson.annotation.JsonValue;
import com.vmware.avi.sdk.model.IpAddr;
import io.swagger.v3.oas.annotations.media.Schema;
/**
 * GslbServiceDownResponse
 */

@javax.annotation.Generated(value = "io.swagger.codegen.v3.generators.java.JavaClientCodegen", date = "2020-03-12T12:27:26.755+05:30[Asia/Kolkata]")
public class GslbServiceDownResponse {
  @JsonProperty("fallback_ip")
  private IpAddr fallbackIp = null;

  @JsonProperty("type")
  private String type = "GSLB_SERVICE_DOWN_RESPONSE_NONE";

  public GslbServiceDownResponse fallbackIp(IpAddr fallbackIp) {
    this.fallbackIp = fallbackIp;
    return this;
  }

   /**
   * Get fallbackIp
   * @return fallbackIp
  **/
  @Schema(description = "")
  public IpAddr getFallbackIp() {
    return fallbackIp;
  }

  public void setFallbackIp(IpAddr fallbackIp) {
    this.fallbackIp = fallbackIp;
  }

  public GslbServiceDownResponse type(String type) {
    this.type = type;
    return this;
  }

   /**
   * Response from DNS service towards the client when the GSLB service is DOWN. Enum options - GSLB_SERVICE_DOWN_RESPONSE_NONE, GSLB_SERVICE_DOWN_RESPONSE_ALL_RECORDS, GSLB_SERVICE_DOWN_RESPONSE_FALLBACK_IP, GSLB_SERVICE_DOWN_RESPONSE_EMPTY.
   * @return type
  **/
  @Schema(required = true, description = "Response from DNS service towards the client when the GSLB service is DOWN. Enum options - GSLB_SERVICE_DOWN_RESPONSE_NONE, GSLB_SERVICE_DOWN_RESPONSE_ALL_RECORDS, GSLB_SERVICE_DOWN_RESPONSE_FALLBACK_IP, GSLB_SERVICE_DOWN_RESPONSE_EMPTY.")
  public String getType() {
    return type;
  }

  public void setType(String type) {
    this.type = type;
  }


  @Override
  public boolean equals(java.lang.Object o) {
    if (this == o) {
      return true;
    }
    if (o == null || getClass() != o.getClass()) {
      return false;
    }
    GslbServiceDownResponse gslbServiceDownResponse = (GslbServiceDownResponse) o;
    return Objects.equals(this.fallbackIp, gslbServiceDownResponse.fallbackIp) &&
        Objects.equals(this.type, gslbServiceDownResponse.type);
  }

  @Override
  public int hashCode() {
    return Objects.hash(fallbackIp, type);
  }


  @Override
  public String toString() {
    StringBuilder sb = new StringBuilder();
    sb.append("class GslbServiceDownResponse {\n");
    
    sb.append("    fallbackIp: ").append(toIndentedString(fallbackIp)).append("\n");
    sb.append("    type: ").append(toIndentedString(type)).append("\n");
    sb.append("}");
    return sb.toString();
  }

  /**
   * Convert the given object to string with each line indented by 4 spaces
   * (except the first line).
   */
  private String toIndentedString(java.lang.Object o) {
    if (o == null) {
      return "null";
    }
    return o.toString().replace("\n", "\n    ");
  }

}
