/*
 * Avi avi_global_spec Object API
 * No description provided (generated by Swagger Codegen https://github.com/swagger-api/swagger-codegen)
 *
 * OpenAPI spec version: 20.1.1
 * Contact: support@avinetworks.com
 *
 * NOTE: This class is auto generated by the swagger code generator program.
 * https://github.com/swagger-api/swagger-codegen.git
 * Do not edit the class manually.
 */

package com.vmware.avi.sdk.model;

import java.util.Objects;
import java.util.Arrays;
import com.fasterxml.jackson.annotation.JsonProperty;
import com.fasterxml.jackson.annotation.JsonCreator;
import com.fasterxml.jackson.annotation.JsonValue;
import io.swagger.v3.oas.annotations.media.Schema;
/**
 * HealthMonitorRadius
 */

@javax.annotation.Generated(value = "io.swagger.codegen.v3.generators.java.JavaClientCodegen", date = "2020-03-12T12:27:26.755+05:30[Asia/Kolkata]")
public class HealthMonitorRadius {
  @JsonProperty("password")
  private String password = null;

  @JsonProperty("shared_secret")
  private String sharedSecret = null;

  @JsonProperty("username")
  private String username = null;

  public HealthMonitorRadius password(String password) {
    this.password = password;
    return this;
  }

   /**
   * Radius monitor will query Radius server with this password. Field introduced in 18.2.3.
   * @return password
  **/
  @Schema(required = true, description = "Radius monitor will query Radius server with this password. Field introduced in 18.2.3.")
  public String getPassword() {
    return password;
  }

  public void setPassword(String password) {
    this.password = password;
  }

  public HealthMonitorRadius sharedSecret(String sharedSecret) {
    this.sharedSecret = sharedSecret;
    return this;
  }

   /**
   * Radius monitor will query Radius server with this shared secret. Field introduced in 18.2.3.
   * @return sharedSecret
  **/
  @Schema(required = true, description = "Radius monitor will query Radius server with this shared secret. Field introduced in 18.2.3.")
  public String getSharedSecret() {
    return sharedSecret;
  }

  public void setSharedSecret(String sharedSecret) {
    this.sharedSecret = sharedSecret;
  }

  public HealthMonitorRadius username(String username) {
    this.username = username;
    return this;
  }

   /**
   * Radius monitor will query Radius server with this username. Field introduced in 18.2.3.
   * @return username
  **/
  @Schema(required = true, description = "Radius monitor will query Radius server with this username. Field introduced in 18.2.3.")
  public String getUsername() {
    return username;
  }

  public void setUsername(String username) {
    this.username = username;
  }


  @Override
  public boolean equals(java.lang.Object o) {
    if (this == o) {
      return true;
    }
    if (o == null || getClass() != o.getClass()) {
      return false;
    }
    HealthMonitorRadius healthMonitorRadius = (HealthMonitorRadius) o;
    return Objects.equals(this.password, healthMonitorRadius.password) &&
        Objects.equals(this.sharedSecret, healthMonitorRadius.sharedSecret) &&
        Objects.equals(this.username, healthMonitorRadius.username);
  }

  @Override
  public int hashCode() {
    return Objects.hash(password, sharedSecret, username);
  }


  @Override
  public String toString() {
    StringBuilder sb = new StringBuilder();
    sb.append("class HealthMonitorRadius {\n");
    
    sb.append("    password: ").append(toIndentedString(password)).append("\n");
    sb.append("    sharedSecret: ").append(toIndentedString(sharedSecret)).append("\n");
    sb.append("    username: ").append(toIndentedString(username)).append("\n");
    sb.append("}");
    return sb.toString();
  }

  /**
   * Convert the given object to string with each line indented by 4 spaces
   * (except the first line).
   */
  private String toIndentedString(java.lang.Object o) {
    if (o == null) {
      return "null";
    }
    return o.toString().replace("\n", "\n    ");
  }

}
