/*
 * Avi avi_global_spec Object API
 * No description provided (generated by Swagger Codegen https://github.com/swagger-api/swagger-codegen)
 *
 * OpenAPI spec version: 20.1.1
 * Contact: support@avinetworks.com
 *
 * NOTE: This class is auto generated by the swagger code generator program.
 * https://github.com/swagger-api/swagger-codegen.git
 * Do not edit the class manually.
 */

package com.vmware.avi.sdk.model;

import java.util.Objects;
import java.util.Arrays;
import com.fasterxml.jackson.annotation.JsonProperty;
import com.fasterxml.jackson.annotation.JsonCreator;
import com.fasterxml.jackson.annotation.JsonValue;
import com.vmware.avi.sdk.model.HTTPSecurityAction;
import com.vmware.avi.sdk.model.MatchTarget;
import io.swagger.v3.oas.annotations.media.Schema;
/**
 * HTTPSecurityRule
 */

@javax.annotation.Generated(value = "io.swagger.codegen.v3.generators.java.JavaClientCodegen", date = "2020-03-12T12:27:26.755+05:30[Asia/Kolkata]")
public class HTTPSecurityRule {
  @JsonProperty("action")
  private HTTPSecurityAction action = null;

  @JsonProperty("enable")
  private Boolean enable = true;

  @JsonProperty("index")
  private Integer index = null;

  @JsonProperty("log")
  private Boolean log = null;

  @JsonProperty("match")
  private MatchTarget match = null;

  @JsonProperty("name")
  private String name = null;

  public HTTPSecurityRule action(HTTPSecurityAction action) {
    this.action = action;
    return this;
  }

   /**
   * Get action
   * @return action
  **/
  @Schema(description = "")
  public HTTPSecurityAction getAction() {
    return action;
  }

  public void setAction(HTTPSecurityAction action) {
    this.action = action;
  }

  public HTTPSecurityRule enable(Boolean enable) {
    this.enable = enable;
    return this;
  }

   /**
   * Enable or disable the rule.
   * @return enable
  **/
  @Schema(required = true, description = "Enable or disable the rule.")
  public Boolean isEnable() {
    return enable;
  }

  public void setEnable(Boolean enable) {
    this.enable = enable;
  }

  public HTTPSecurityRule index(Integer index) {
    this.index = index;
    return this;
  }

   /**
   * Index of the rule.
   * @return index
  **/
  @Schema(required = true, description = "Index of the rule.")
  public Integer getIndex() {
    return index;
  }

  public void setIndex(Integer index) {
    this.index = index;
  }

  public HTTPSecurityRule log(Boolean log) {
    this.log = log;
    return this;
  }

   /**
   * Log HTTP request upon rule match.
   * @return log
  **/
  @Schema(description = "Log HTTP request upon rule match.")
  public Boolean isLog() {
    return log;
  }

  public void setLog(Boolean log) {
    this.log = log;
  }

  public HTTPSecurityRule match(MatchTarget match) {
    this.match = match;
    return this;
  }

   /**
   * Get match
   * @return match
  **/
  @Schema(description = "")
  public MatchTarget getMatch() {
    return match;
  }

  public void setMatch(MatchTarget match) {
    this.match = match;
  }

  public HTTPSecurityRule name(String name) {
    this.name = name;
    return this;
  }

   /**
   * Name of the rule.
   * @return name
  **/
  @Schema(required = true, description = "Name of the rule.")
  public String getName() {
    return name;
  }

  public void setName(String name) {
    this.name = name;
  }


  @Override
  public boolean equals(java.lang.Object o) {
    if (this == o) {
      return true;
    }
    if (o == null || getClass() != o.getClass()) {
      return false;
    }
    HTTPSecurityRule htTPSecurityRule = (HTTPSecurityRule) o;
    return Objects.equals(this.action, htTPSecurityRule.action) &&
        Objects.equals(this.enable, htTPSecurityRule.enable) &&
        Objects.equals(this.index, htTPSecurityRule.index) &&
        Objects.equals(this.log, htTPSecurityRule.log) &&
        Objects.equals(this.match, htTPSecurityRule.match) &&
        Objects.equals(this.name, htTPSecurityRule.name);
  }

  @Override
  public int hashCode() {
    return Objects.hash(action, enable, index, log, match, name);
  }


  @Override
  public String toString() {
    StringBuilder sb = new StringBuilder();
    sb.append("class HTTPSecurityRule {\n");
    
    sb.append("    action: ").append(toIndentedString(action)).append("\n");
    sb.append("    enable: ").append(toIndentedString(enable)).append("\n");
    sb.append("    index: ").append(toIndentedString(index)).append("\n");
    sb.append("    log: ").append(toIndentedString(log)).append("\n");
    sb.append("    match: ").append(toIndentedString(match)).append("\n");
    sb.append("    name: ").append(toIndentedString(name)).append("\n");
    sb.append("}");
    return sb.toString();
  }

  /**
   * Convert the given object to string with each line indented by 4 spaces
   * (except the first line).
   */
  private String toIndentedString(java.lang.Object o) {
    if (o == null) {
      return "null";
    }
    return o.toString().replace("\n", "\n    ");
  }

}
