/*
 * Avi avi_global_spec Object API
 * No description provided (generated by Swagger Codegen https://github.com/swagger-api/swagger-codegen)
 *
 * OpenAPI spec version: 20.1.1
 * Contact: support@avinetworks.com
 *
 * NOTE: This class is auto generated by the swagger code generator program.
 * https://github.com/swagger-api/swagger-codegen.git
 * Do not edit the class manually.
 */

package com.vmware.avi.sdk.model;

import java.util.Objects;
import java.util.Arrays;
import com.fasterxml.jackson.annotation.JsonProperty;
import com.fasterxml.jackson.annotation.JsonCreator;
import com.fasterxml.jackson.annotation.JsonValue;
import com.vmware.avi.sdk.model.HTTPRequestPolicy;
import com.vmware.avi.sdk.model.HTTPResponsePolicy;
import com.vmware.avi.sdk.model.HTTPSecurityPolicy;
import io.swagger.v3.oas.annotations.media.Schema;
/**
 * HTTPPolicySet
 */

@javax.annotation.Generated(value = "io.swagger.codegen.v3.generators.java.JavaClientCodegen", date = "2020-03-12T12:27:26.755+05:30[Asia/Kolkata]")
public class HTTPPolicySet {
  @JsonProperty("_last_modified")
  private String _lastModified = null;

  @JsonProperty("cloud_config_cksum")
  private String cloudConfigCksum = null;

  @JsonProperty("created_by")
  private String createdBy = null;

  @JsonProperty("description")
  private String description = null;

  @JsonProperty("http_request_policy")
  private HTTPRequestPolicy httpRequestPolicy = null;

  @JsonProperty("http_response_policy")
  private HTTPResponsePolicy httpResponsePolicy = null;

  @JsonProperty("http_security_policy")
  private HTTPSecurityPolicy httpSecurityPolicy = null;

  @JsonProperty("is_internal_policy")
  private Boolean isInternalPolicy = null;

  @JsonProperty("name")
  private String name = null;

  @JsonProperty("tenant_ref")
  private String tenantRef = null;

  @JsonProperty("url")
  private String url = null;

  @JsonProperty("uuid")
  private String uuid = null;

   /**
   * UNIX time since epoch in microseconds. Units(MICROSECONDS).
   * @return _lastModified
  **/
  @Schema(description = "UNIX time since epoch in microseconds. Units(MICROSECONDS).")
  public String getLastModified() {
    return _lastModified;
  }

  public HTTPPolicySet cloudConfigCksum(String cloudConfigCksum) {
    this.cloudConfigCksum = cloudConfigCksum;
    return this;
  }

   /**
   * Checksum of cloud configuration for Pool. Internally set by cloud connector.
   * @return cloudConfigCksum
  **/
  @Schema(description = "Checksum of cloud configuration for Pool. Internally set by cloud connector.")
  public String getCloudConfigCksum() {
    return cloudConfigCksum;
  }

  public void setCloudConfigCksum(String cloudConfigCksum) {
    this.cloudConfigCksum = cloudConfigCksum;
  }

  public HTTPPolicySet createdBy(String createdBy) {
    this.createdBy = createdBy;
    return this;
  }

   /**
   * Creator name.
   * @return createdBy
  **/
  @Schema(description = "Creator name.")
  public String getCreatedBy() {
    return createdBy;
  }

  public void setCreatedBy(String createdBy) {
    this.createdBy = createdBy;
  }

  public HTTPPolicySet description(String description) {
    this.description = description;
    return this;
  }

   /**
   * User defined description for the object.
   * @return description
  **/
  @Schema(description = "User defined description for the object.")
  public String getDescription() {
    return description;
  }

  public void setDescription(String description) {
    this.description = description;
  }

  public HTTPPolicySet httpRequestPolicy(HTTPRequestPolicy httpRequestPolicy) {
    this.httpRequestPolicy = httpRequestPolicy;
    return this;
  }

   /**
   * Get httpRequestPolicy
   * @return httpRequestPolicy
  **/
  @Schema(description = "")
  public HTTPRequestPolicy getHttpRequestPolicy() {
    return httpRequestPolicy;
  }

  public void setHttpRequestPolicy(HTTPRequestPolicy httpRequestPolicy) {
    this.httpRequestPolicy = httpRequestPolicy;
  }

  public HTTPPolicySet httpResponsePolicy(HTTPResponsePolicy httpResponsePolicy) {
    this.httpResponsePolicy = httpResponsePolicy;
    return this;
  }

   /**
   * Get httpResponsePolicy
   * @return httpResponsePolicy
  **/
  @Schema(description = "")
  public HTTPResponsePolicy getHttpResponsePolicy() {
    return httpResponsePolicy;
  }

  public void setHttpResponsePolicy(HTTPResponsePolicy httpResponsePolicy) {
    this.httpResponsePolicy = httpResponsePolicy;
  }

  public HTTPPolicySet httpSecurityPolicy(HTTPSecurityPolicy httpSecurityPolicy) {
    this.httpSecurityPolicy = httpSecurityPolicy;
    return this;
  }

   /**
   * Get httpSecurityPolicy
   * @return httpSecurityPolicy
  **/
  @Schema(description = "")
  public HTTPSecurityPolicy getHttpSecurityPolicy() {
    return httpSecurityPolicy;
  }

  public void setHttpSecurityPolicy(HTTPSecurityPolicy httpSecurityPolicy) {
    this.httpSecurityPolicy = httpSecurityPolicy;
  }

  public HTTPPolicySet isInternalPolicy(Boolean isInternalPolicy) {
    this.isInternalPolicy = isInternalPolicy;
    return this;
  }

   /**
   * Placeholder for description of property is_internal_policy of obj type HTTPPolicySet field type str  type boolean
   * @return isInternalPolicy
  **/
  @Schema(description = "Placeholder for description of property is_internal_policy of obj type HTTPPolicySet field type str  type boolean")
  public Boolean isIsInternalPolicy() {
    return isInternalPolicy;
  }

  public void setIsInternalPolicy(Boolean isInternalPolicy) {
    this.isInternalPolicy = isInternalPolicy;
  }

  public HTTPPolicySet name(String name) {
    this.name = name;
    return this;
  }

   /**
   * Name of the HTTP Policy Set.
   * @return name
  **/
  @Schema(required = true, description = "Name of the HTTP Policy Set.")
  public String getName() {
    return name;
  }

  public void setName(String name) {
    this.name = name;
  }

  public HTTPPolicySet tenantRef(String tenantRef) {
    this.tenantRef = tenantRef;
    return this;
  }

   /**
   *  It is a reference to an object of type Tenant.
   * @return tenantRef
  **/
  @Schema(description = " It is a reference to an object of type Tenant.")
  public String getTenantRef() {
    return tenantRef;
  }

  public void setTenantRef(String tenantRef) {
    this.tenantRef = tenantRef;
  }

   /**
   * url
   * @return url
  **/
  @Schema(description = "url")
  public String getUrl() {
    return url;
  }

  public HTTPPolicySet uuid(String uuid) {
    this.uuid = uuid;
    return this;
  }

   /**
   * UUID of the HTTP Policy Set.
   * @return uuid
  **/
  @Schema(description = "UUID of the HTTP Policy Set.")
  public String getUuid() {
    return uuid;
  }

  public void setUuid(String uuid) {
    this.uuid = uuid;
  }


  @Override
  public boolean equals(java.lang.Object o) {
    if (this == o) {
      return true;
    }
    if (o == null || getClass() != o.getClass()) {
      return false;
    }
    HTTPPolicySet htTPPolicySet = (HTTPPolicySet) o;
    return Objects.equals(this._lastModified, htTPPolicySet._lastModified) &&
        Objects.equals(this.cloudConfigCksum, htTPPolicySet.cloudConfigCksum) &&
        Objects.equals(this.createdBy, htTPPolicySet.createdBy) &&
        Objects.equals(this.description, htTPPolicySet.description) &&
        Objects.equals(this.httpRequestPolicy, htTPPolicySet.httpRequestPolicy) &&
        Objects.equals(this.httpResponsePolicy, htTPPolicySet.httpResponsePolicy) &&
        Objects.equals(this.httpSecurityPolicy, htTPPolicySet.httpSecurityPolicy) &&
        Objects.equals(this.isInternalPolicy, htTPPolicySet.isInternalPolicy) &&
        Objects.equals(this.name, htTPPolicySet.name) &&
        Objects.equals(this.tenantRef, htTPPolicySet.tenantRef) &&
        Objects.equals(this.url, htTPPolicySet.url) &&
        Objects.equals(this.uuid, htTPPolicySet.uuid);
  }

  @Override
  public int hashCode() {
    return Objects.hash(_lastModified, cloudConfigCksum, createdBy, description, httpRequestPolicy, httpResponsePolicy, httpSecurityPolicy, isInternalPolicy, name, tenantRef, url, uuid);
  }


  @Override
  public String toString() {
    StringBuilder sb = new StringBuilder();
    sb.append("class HTTPPolicySet {\n");
    
    sb.append("    _lastModified: ").append(toIndentedString(_lastModified)).append("\n");
    sb.append("    cloudConfigCksum: ").append(toIndentedString(cloudConfigCksum)).append("\n");
    sb.append("    createdBy: ").append(toIndentedString(createdBy)).append("\n");
    sb.append("    description: ").append(toIndentedString(description)).append("\n");
    sb.append("    httpRequestPolicy: ").append(toIndentedString(httpRequestPolicy)).append("\n");
    sb.append("    httpResponsePolicy: ").append(toIndentedString(httpResponsePolicy)).append("\n");
    sb.append("    httpSecurityPolicy: ").append(toIndentedString(httpSecurityPolicy)).append("\n");
    sb.append("    isInternalPolicy: ").append(toIndentedString(isInternalPolicy)).append("\n");
    sb.append("    name: ").append(toIndentedString(name)).append("\n");
    sb.append("    tenantRef: ").append(toIndentedString(tenantRef)).append("\n");
    sb.append("    url: ").append(toIndentedString(url)).append("\n");
    sb.append("    uuid: ").append(toIndentedString(uuid)).append("\n");
    sb.append("}");
    return sb.toString();
  }

  /**
   * Convert the given object to string with each line indented by 4 spaces
   * (except the first line).
   */
  private String toIndentedString(java.lang.Object o) {
    if (o == null) {
      return "null";
    }
    return o.toString().replace("\n", "\n    ");
  }

}
