/*
 * Avi avi_global_spec Object API
 * No description provided (generated by Swagger Codegen https://github.com/swagger-api/swagger-codegen)
 *
 * OpenAPI spec version: 20.1.1
 * Contact: support@avinetworks.com
 *
 * NOTE: This class is auto generated by the swagger code generator program.
 * https://github.com/swagger-api/swagger-codegen.git
 * Do not edit the class manually.
 */

package com.vmware.avi.sdk.model;

import java.util.Objects;
import java.util.Arrays;
import com.fasterxml.jackson.annotation.JsonProperty;
import com.fasterxml.jackson.annotation.JsonCreator;
import com.fasterxml.jackson.annotation.JsonValue;
import com.vmware.avi.sdk.model.HTTPHdrAction;
import com.vmware.avi.sdk.model.HTTPRewriteLocHdrAction;
import com.vmware.avi.sdk.model.ResponseMatchTarget;
import io.swagger.v3.oas.annotations.media.Schema;
import java.util.ArrayList;
import java.util.List;
/**
 * HTTPResponseRule
 */

@javax.annotation.Generated(value = "io.swagger.codegen.v3.generators.java.JavaClientCodegen", date = "2020-03-12T12:27:26.755+05:30[Asia/Kolkata]")
public class HTTPResponseRule {
  @JsonProperty("all_headers")
  private Boolean allHeaders = null;

  @JsonProperty("enable")
  private Boolean enable = true;

  @JsonProperty("hdr_action")
  private List<HTTPHdrAction> hdrAction = null;

  @JsonProperty("index")
  private Integer index = null;

  @JsonProperty("loc_hdr_action")
  private HTTPRewriteLocHdrAction locHdrAction = null;

  @JsonProperty("log")
  private Boolean log = null;

  @JsonProperty("match")
  private ResponseMatchTarget match = null;

  @JsonProperty("name")
  private String name = null;

  public HTTPResponseRule allHeaders(Boolean allHeaders) {
    this.allHeaders = allHeaders;
    return this;
  }

   /**
   * Log all HTTP headers upon rule match.
   * @return allHeaders
  **/
  @Schema(description = "Log all HTTP headers upon rule match.")
  public Boolean isAllHeaders() {
    return allHeaders;
  }

  public void setAllHeaders(Boolean allHeaders) {
    this.allHeaders = allHeaders;
  }

  public HTTPResponseRule enable(Boolean enable) {
    this.enable = enable;
    return this;
  }

   /**
   * Enable or disable the rule.
   * @return enable
  **/
  @Schema(required = true, description = "Enable or disable the rule.")
  public Boolean isEnable() {
    return enable;
  }

  public void setEnable(Boolean enable) {
    this.enable = enable;
  }

  public HTTPResponseRule hdrAction(List<HTTPHdrAction> hdrAction) {
    this.hdrAction = hdrAction;
    return this;
  }

  public HTTPResponseRule addHdrActionItem(HTTPHdrAction hdrActionItem) {
    if (this.hdrAction == null) {
      this.hdrAction = new ArrayList<HTTPHdrAction>();
    }
    this.hdrAction.add(hdrActionItem);
    return this;
  }

   /**
   * HTTP header rewrite action.
   * @return hdrAction
  **/
  @Schema(description = "HTTP header rewrite action.")
  public List<HTTPHdrAction> getHdrAction() {
    return hdrAction;
  }

  public void setHdrAction(List<HTTPHdrAction> hdrAction) {
    this.hdrAction = hdrAction;
  }

  public HTTPResponseRule index(Integer index) {
    this.index = index;
    return this;
  }

   /**
   * Index of the rule.
   * @return index
  **/
  @Schema(required = true, description = "Index of the rule.")
  public Integer getIndex() {
    return index;
  }

  public void setIndex(Integer index) {
    this.index = index;
  }

  public HTTPResponseRule locHdrAction(HTTPRewriteLocHdrAction locHdrAction) {
    this.locHdrAction = locHdrAction;
    return this;
  }

   /**
   * Get locHdrAction
   * @return locHdrAction
  **/
  @Schema(description = "")
  public HTTPRewriteLocHdrAction getLocHdrAction() {
    return locHdrAction;
  }

  public void setLocHdrAction(HTTPRewriteLocHdrAction locHdrAction) {
    this.locHdrAction = locHdrAction;
  }

  public HTTPResponseRule log(Boolean log) {
    this.log = log;
    return this;
  }

   /**
   * Log HTTP request upon rule match.
   * @return log
  **/
  @Schema(description = "Log HTTP request upon rule match.")
  public Boolean isLog() {
    return log;
  }

  public void setLog(Boolean log) {
    this.log = log;
  }

  public HTTPResponseRule match(ResponseMatchTarget match) {
    this.match = match;
    return this;
  }

   /**
   * Get match
   * @return match
  **/
  @Schema(description = "")
  public ResponseMatchTarget getMatch() {
    return match;
  }

  public void setMatch(ResponseMatchTarget match) {
    this.match = match;
  }

  public HTTPResponseRule name(String name) {
    this.name = name;
    return this;
  }

   /**
   * Name of the rule.
   * @return name
  **/
  @Schema(required = true, description = "Name of the rule.")
  public String getName() {
    return name;
  }

  public void setName(String name) {
    this.name = name;
  }


  @Override
  public boolean equals(java.lang.Object o) {
    if (this == o) {
      return true;
    }
    if (o == null || getClass() != o.getClass()) {
      return false;
    }
    HTTPResponseRule htTPResponseRule = (HTTPResponseRule) o;
    return Objects.equals(this.allHeaders, htTPResponseRule.allHeaders) &&
        Objects.equals(this.enable, htTPResponseRule.enable) &&
        Objects.equals(this.hdrAction, htTPResponseRule.hdrAction) &&
        Objects.equals(this.index, htTPResponseRule.index) &&
        Objects.equals(this.locHdrAction, htTPResponseRule.locHdrAction) &&
        Objects.equals(this.log, htTPResponseRule.log) &&
        Objects.equals(this.match, htTPResponseRule.match) &&
        Objects.equals(this.name, htTPResponseRule.name);
  }

  @Override
  public int hashCode() {
    return Objects.hash(allHeaders, enable, hdrAction, index, locHdrAction, log, match, name);
  }


  @Override
  public String toString() {
    StringBuilder sb = new StringBuilder();
    sb.append("class HTTPResponseRule {\n");
    
    sb.append("    allHeaders: ").append(toIndentedString(allHeaders)).append("\n");
    sb.append("    enable: ").append(toIndentedString(enable)).append("\n");
    sb.append("    hdrAction: ").append(toIndentedString(hdrAction)).append("\n");
    sb.append("    index: ").append(toIndentedString(index)).append("\n");
    sb.append("    locHdrAction: ").append(toIndentedString(locHdrAction)).append("\n");
    sb.append("    log: ").append(toIndentedString(log)).append("\n");
    sb.append("    match: ").append(toIndentedString(match)).append("\n");
    sb.append("    name: ").append(toIndentedString(name)).append("\n");
    sb.append("}");
    return sb.toString();
  }

  /**
   * Convert the given object to string with each line indented by 4 spaces
   * (except the first line).
   */
  private String toIndentedString(java.lang.Object o) {
    if (o == null) {
      return "null";
    }
    return o.toString().replace("\n", "\n    ");
  }

}
