/*
 * Avi avi_global_spec Object API
 * No description provided (generated by Swagger Codegen https://github.com/swagger-api/swagger-codegen)
 *
 * OpenAPI spec version: 20.1.1
 * Contact: support@avinetworks.com
 *
 * NOTE: This class is auto generated by the swagger code generator program.
 * https://github.com/swagger-api/swagger-codegen.git
 * Do not edit the class manually.
 */

package com.vmware.avi.sdk.model;

import java.util.Objects;
import java.util.Arrays;
import com.fasterxml.jackson.annotation.JsonProperty;
import com.fasterxml.jackson.annotation.JsonCreator;
import com.fasterxml.jackson.annotation.JsonValue;
import com.vmware.avi.sdk.model.IpAddr;
import com.vmware.avi.sdk.model.IpAddrPrefix;
import com.vmware.avi.sdk.model.IpAddrRange;
import io.swagger.v3.oas.annotations.media.Schema;
import java.util.ArrayList;
import java.util.List;
/**
 * IpAddrMatch
 */

@javax.annotation.Generated(value = "io.swagger.codegen.v3.generators.java.JavaClientCodegen", date = "2020-03-12T12:27:26.755+05:30[Asia/Kolkata]")
public class IpAddrMatch {
  @JsonProperty("addrs")
  private List<IpAddr> addrs = null;

  @JsonProperty("group_refs")
  private List<String> groupRefs = null;

  @JsonProperty("match_criteria")
  private String matchCriteria = null;

  @JsonProperty("prefixes")
  private List<IpAddrPrefix> prefixes = null;

  @JsonProperty("ranges")
  private List<IpAddrRange> ranges = null;

  public IpAddrMatch addrs(List<IpAddr> addrs) {
    this.addrs = addrs;
    return this;
  }

  public IpAddrMatch addAddrsItem(IpAddr addrsItem) {
    if (this.addrs == null) {
      this.addrs = new ArrayList<IpAddr>();
    }
    this.addrs.add(addrsItem);
    return this;
  }

   /**
   * IP address(es).
   * @return addrs
  **/
  @Schema(description = "IP address(es).")
  public List<IpAddr> getAddrs() {
    return addrs;
  }

  public void setAddrs(List<IpAddr> addrs) {
    this.addrs = addrs;
  }

  public IpAddrMatch groupRefs(List<String> groupRefs) {
    this.groupRefs = groupRefs;
    return this;
  }

  public IpAddrMatch addGroupRefsItem(String groupRefsItem) {
    if (this.groupRefs == null) {
      this.groupRefs = new ArrayList<String>();
    }
    this.groupRefs.add(groupRefsItem);
    return this;
  }

   /**
   * UUID of IP address group(s). It is a reference to an object of type IpAddrGroup.
   * @return groupRefs
  **/
  @Schema(description = "UUID of IP address group(s). It is a reference to an object of type IpAddrGroup.")
  public List<String> getGroupRefs() {
    return groupRefs;
  }

  public void setGroupRefs(List<String> groupRefs) {
    this.groupRefs = groupRefs;
  }

  public IpAddrMatch matchCriteria(String matchCriteria) {
    this.matchCriteria = matchCriteria;
    return this;
  }

   /**
   * Criterion to use for IP address matching the HTTP request. Enum options - IS_IN, IS_NOT_IN.
   * @return matchCriteria
  **/
  @Schema(required = true, description = "Criterion to use for IP address matching the HTTP request. Enum options - IS_IN, IS_NOT_IN.")
  public String getMatchCriteria() {
    return matchCriteria;
  }

  public void setMatchCriteria(String matchCriteria) {
    this.matchCriteria = matchCriteria;
  }

  public IpAddrMatch prefixes(List<IpAddrPrefix> prefixes) {
    this.prefixes = prefixes;
    return this;
  }

  public IpAddrMatch addPrefixesItem(IpAddrPrefix prefixesItem) {
    if (this.prefixes == null) {
      this.prefixes = new ArrayList<IpAddrPrefix>();
    }
    this.prefixes.add(prefixesItem);
    return this;
  }

   /**
   * IP address prefix(es).
   * @return prefixes
  **/
  @Schema(description = "IP address prefix(es).")
  public List<IpAddrPrefix> getPrefixes() {
    return prefixes;
  }

  public void setPrefixes(List<IpAddrPrefix> prefixes) {
    this.prefixes = prefixes;
  }

  public IpAddrMatch ranges(List<IpAddrRange> ranges) {
    this.ranges = ranges;
    return this;
  }

  public IpAddrMatch addRangesItem(IpAddrRange rangesItem) {
    if (this.ranges == null) {
      this.ranges = new ArrayList<IpAddrRange>();
    }
    this.ranges.add(rangesItem);
    return this;
  }

   /**
   * IP address range(s).
   * @return ranges
  **/
  @Schema(description = "IP address range(s).")
  public List<IpAddrRange> getRanges() {
    return ranges;
  }

  public void setRanges(List<IpAddrRange> ranges) {
    this.ranges = ranges;
  }


  @Override
  public boolean equals(java.lang.Object o) {
    if (this == o) {
      return true;
    }
    if (o == null || getClass() != o.getClass()) {
      return false;
    }
    IpAddrMatch ipAddrMatch = (IpAddrMatch) o;
    return Objects.equals(this.addrs, ipAddrMatch.addrs) &&
        Objects.equals(this.groupRefs, ipAddrMatch.groupRefs) &&
        Objects.equals(this.matchCriteria, ipAddrMatch.matchCriteria) &&
        Objects.equals(this.prefixes, ipAddrMatch.prefixes) &&
        Objects.equals(this.ranges, ipAddrMatch.ranges);
  }

  @Override
  public int hashCode() {
    return Objects.hash(addrs, groupRefs, matchCriteria, prefixes, ranges);
  }


  @Override
  public String toString() {
    StringBuilder sb = new StringBuilder();
    sb.append("class IpAddrMatch {\n");
    
    sb.append("    addrs: ").append(toIndentedString(addrs)).append("\n");
    sb.append("    groupRefs: ").append(toIndentedString(groupRefs)).append("\n");
    sb.append("    matchCriteria: ").append(toIndentedString(matchCriteria)).append("\n");
    sb.append("    prefixes: ").append(toIndentedString(prefixes)).append("\n");
    sb.append("    ranges: ").append(toIndentedString(ranges)).append("\n");
    sb.append("}");
    return sb.toString();
  }

  /**
   * Convert the given object to string with each line indented by 4 spaces
   * (except the first line).
   */
  private String toIndentedString(java.lang.Object o) {
    if (o == null) {
      return "null";
    }
    return o.toString().replace("\n", "\n    ");
  }

}
