/*
 * Avi avi_global_spec Object API
 * No description provided (generated by Swagger Codegen https://github.com/swagger-api/swagger-codegen)
 *
 * OpenAPI spec version: 20.1.1
 * Contact: support@avinetworks.com
 *
 * NOTE: This class is auto generated by the swagger code generator program.
 * https://github.com/swagger-api/swagger-codegen.git
 * Do not edit the class manually.
 */

package com.vmware.avi.sdk.model;

import java.util.Objects;
import java.util.Arrays;
import com.fasterxml.jackson.annotation.JsonProperty;
import com.fasterxml.jackson.annotation.JsonCreator;
import com.fasterxml.jackson.annotation.JsonValue;
import com.vmware.avi.sdk.model.TencentZoneNetwork;
import io.swagger.v3.oas.annotations.media.Schema;
import java.util.ArrayList;
import java.util.List;
/**
 * IpamDnsTencentProfile
 */

@javax.annotation.Generated(value = "io.swagger.codegen.v3.generators.java.JavaClientCodegen", date = "2020-03-12T12:27:26.755+05:30[Asia/Kolkata]")
public class IpamDnsTencentProfile {
  @JsonProperty("cloud_credentials_ref")
  private String cloudCredentialsRef = null;

  @JsonProperty("region")
  private String region = null;

  @JsonProperty("usable_subnet_ids")
  private List<String> usableSubnetIds = null;

  @JsonProperty("vpc_id")
  private String vpcId = null;

  @JsonProperty("zones")
  private List<TencentZoneNetwork> zones = null;

  public IpamDnsTencentProfile cloudCredentialsRef(String cloudCredentialsRef) {
    this.cloudCredentialsRef = cloudCredentialsRef;
    return this;
  }

   /**
   * Credentials to access Tencent cloud. It is a reference to an object of type CloudConnectorUser. Field introduced in 18.2.3.
   * @return cloudCredentialsRef
  **/
  @Schema(description = "Credentials to access Tencent cloud. It is a reference to an object of type CloudConnectorUser. Field introduced in 18.2.3.")
  public String getCloudCredentialsRef() {
    return cloudCredentialsRef;
  }

  public void setCloudCredentialsRef(String cloudCredentialsRef) {
    this.cloudCredentialsRef = cloudCredentialsRef;
  }

  public IpamDnsTencentProfile region(String region) {
    this.region = region;
    return this;
  }

   /**
   * VPC region. Field introduced in 18.2.3.
   * @return region
  **/
  @Schema(required = true, description = "VPC region. Field introduced in 18.2.3.")
  public String getRegion() {
    return region;
  }

  public void setRegion(String region) {
    this.region = region;
  }

  public IpamDnsTencentProfile usableSubnetIds(List<String> usableSubnetIds) {
    this.usableSubnetIds = usableSubnetIds;
    return this;
  }

  public IpamDnsTencentProfile addUsableSubnetIdsItem(String usableSubnetIdsItem) {
    if (this.usableSubnetIds == null) {
      this.usableSubnetIds = new ArrayList<String>();
    }
    this.usableSubnetIds.add(usableSubnetIdsItem);
    return this;
  }

   /**
   * Usable networks for Virtual IP. If VirtualService does not specify a network and auto_allocate_ip is set, then the first available network from this list will be chosen for IP allocation. Field introduced in 18.2.3.
   * @return usableSubnetIds
  **/
  @Schema(description = "Usable networks for Virtual IP. If VirtualService does not specify a network and auto_allocate_ip is set, then the first available network from this list will be chosen for IP allocation. Field introduced in 18.2.3.")
  public List<String> getUsableSubnetIds() {
    return usableSubnetIds;
  }

  public void setUsableSubnetIds(List<String> usableSubnetIds) {
    this.usableSubnetIds = usableSubnetIds;
  }

  public IpamDnsTencentProfile vpcId(String vpcId) {
    this.vpcId = vpcId;
    return this;
  }

   /**
   * VPC ID. Field introduced in 18.2.3.
   * @return vpcId
  **/
  @Schema(required = true, description = "VPC ID. Field introduced in 18.2.3.")
  public String getVpcId() {
    return vpcId;
  }

  public void setVpcId(String vpcId) {
    this.vpcId = vpcId;
  }

  public IpamDnsTencentProfile zones(List<TencentZoneNetwork> zones) {
    this.zones = zones;
    return this;
  }

  public IpamDnsTencentProfile addZonesItem(TencentZoneNetwork zonesItem) {
    if (this.zones == null) {
      this.zones = new ArrayList<TencentZoneNetwork>();
    }
    this.zones.add(zonesItem);
    return this;
  }

   /**
   * Network configuration for Virtual IP per AZ. Field introduced in 18.2.3.
   * @return zones
  **/
  @Schema(description = "Network configuration for Virtual IP per AZ. Field introduced in 18.2.3.")
  public List<TencentZoneNetwork> getZones() {
    return zones;
  }

  public void setZones(List<TencentZoneNetwork> zones) {
    this.zones = zones;
  }


  @Override
  public boolean equals(java.lang.Object o) {
    if (this == o) {
      return true;
    }
    if (o == null || getClass() != o.getClass()) {
      return false;
    }
    IpamDnsTencentProfile ipamDnsTencentProfile = (IpamDnsTencentProfile) o;
    return Objects.equals(this.cloudCredentialsRef, ipamDnsTencentProfile.cloudCredentialsRef) &&
        Objects.equals(this.region, ipamDnsTencentProfile.region) &&
        Objects.equals(this.usableSubnetIds, ipamDnsTencentProfile.usableSubnetIds) &&
        Objects.equals(this.vpcId, ipamDnsTencentProfile.vpcId) &&
        Objects.equals(this.zones, ipamDnsTencentProfile.zones);
  }

  @Override
  public int hashCode() {
    return Objects.hash(cloudCredentialsRef, region, usableSubnetIds, vpcId, zones);
  }


  @Override
  public String toString() {
    StringBuilder sb = new StringBuilder();
    sb.append("class IpamDnsTencentProfile {\n");
    
    sb.append("    cloudCredentialsRef: ").append(toIndentedString(cloudCredentialsRef)).append("\n");
    sb.append("    region: ").append(toIndentedString(region)).append("\n");
    sb.append("    usableSubnetIds: ").append(toIndentedString(usableSubnetIds)).append("\n");
    sb.append("    vpcId: ").append(toIndentedString(vpcId)).append("\n");
    sb.append("    zones: ").append(toIndentedString(zones)).append("\n");
    sb.append("}");
    return sb.toString();
  }

  /**
   * Convert the given object to string with each line indented by 4 spaces
   * (except the first line).
   */
  private String toIndentedString(java.lang.Object o) {
    if (o == null) {
      return "null";
    }
    return o.toString().replace("\n", "\n    ");
  }

}
