/*
 * Avi avi_global_spec Object API
 * No description provided (generated by Swagger Codegen https://github.com/swagger-api/swagger-codegen)
 *
 * OpenAPI spec version: 20.1.1
 * Contact: support@avinetworks.com
 *
 * NOTE: This class is auto generated by the swagger code generator program.
 * https://github.com/swagger-api/swagger-codegen.git
 * Do not edit the class manually.
 */

package com.vmware.avi.sdk.model;

import java.util.Objects;
import java.util.Arrays;
import com.fasterxml.jackson.annotation.JsonProperty;
import com.fasterxml.jackson.annotation.JsonCreator;
import com.fasterxml.jackson.annotation.JsonValue;
import io.swagger.v3.oas.annotations.media.Schema;
import java.util.ArrayList;
import java.util.List;
/**
 * IPReputationDB
 */

@javax.annotation.Generated(value = "io.swagger.codegen.v3.generators.java.JavaClientCodegen", date = "2020-03-12T12:27:26.755+05:30[Asia/Kolkata]")
public class IPReputationDB {
  @JsonProperty("_last_modified")
  private String _lastModified = null;

  @JsonProperty("base_file_ref")
  private String baseFileRef = null;

  @JsonProperty("description")
  private String description = null;

  @JsonProperty("incremental_file_refs")
  private List<String> incrementalFileRefs = null;

  @JsonProperty("last_modified")
  private Long lastModified = null;

  @JsonProperty("name")
  private String name = null;

  @JsonProperty("tenant_ref")
  private String tenantRef = null;

  @JsonProperty("url")
  private String url = null;

  @JsonProperty("uuid")
  private String uuid = null;

  @JsonProperty("vendor")
  private String vendor = null;

   /**
   * UNIX time since epoch in microseconds. Units(MICROSECONDS).
   * @return _lastModified
  **/
  @Schema(description = "UNIX time since epoch in microseconds. Units(MICROSECONDS).")
  public String _getLastModified() {
    return _lastModified;
  }

  public IPReputationDB baseFileRef(String baseFileRef) {
    this.baseFileRef = baseFileRef;
    return this;
  }

   /**
   * IP reputation DB base file. It is a reference to an object of type FileObject. Field introduced in 20.1.1.
   * @return baseFileRef
  **/
  @Schema(description = "IP reputation DB base file. It is a reference to an object of type FileObject. Field introduced in 20.1.1.")
  public String getBaseFileRef() {
    return baseFileRef;
  }

  public void setBaseFileRef(String baseFileRef) {
    this.baseFileRef = baseFileRef;
  }

  public IPReputationDB description(String description) {
    this.description = description;
    return this;
  }

   /**
   * Description. Field introduced in 20.1.1.
   * @return description
  **/
  @Schema(description = "Description. Field introduced in 20.1.1.")
  public String getDescription() {
    return description;
  }

  public void setDescription(String description) {
    this.description = description;
  }

  public IPReputationDB incrementalFileRefs(List<String> incrementalFileRefs) {
    this.incrementalFileRefs = incrementalFileRefs;
    return this;
  }

  public IPReputationDB addIncrementalFileRefsItem(String incrementalFileRefsItem) {
    if (this.incrementalFileRefs == null) {
      this.incrementalFileRefs = new ArrayList<String>();
    }
    this.incrementalFileRefs.add(incrementalFileRefsItem);
    return this;
  }

   /**
   * IP reputation DB incremental update files. It is a reference to an object of type FileObject. Field introduced in 20.1.1.
   * @return incrementalFileRefs
  **/
  @Schema(description = "IP reputation DB incremental update files. It is a reference to an object of type FileObject. Field introduced in 20.1.1.")
  public List<String> getIncrementalFileRefs() {
    return incrementalFileRefs;
  }

  public void setIncrementalFileRefs(List<String> incrementalFileRefs) {
    this.incrementalFileRefs = incrementalFileRefs;
  }

  public IPReputationDB lastModified(Long lastModified) {
    this.lastModified = lastModified;
    return this;
  }

   /**
   * Timestamp of the last change made to this IP reputation DB. Field introduced in 20.1.1.
   * @return lastModified
  **/
  @Schema(required = true, description = "Timestamp of the last change made to this IP reputation DB. Field introduced in 20.1.1.")
  public Long getLastModified() {
    return lastModified;
  }

  public void setLastModified(Long lastModified) {
    this.lastModified = lastModified;
  }

  public IPReputationDB name(String name) {
    this.name = name;
    return this;
  }

   /**
   * IP reputation DB name. Field introduced in 20.1.1.
   * @return name
  **/
  @Schema(required = true, description = "IP reputation DB name. Field introduced in 20.1.1.")
  public String getName() {
    return name;
  }

  public void setName(String name) {
    this.name = name;
  }

  public IPReputationDB tenantRef(String tenantRef) {
    this.tenantRef = tenantRef;
    return this;
  }

   /**
   * Tenant that this object belongs to. It is a reference to an object of type Tenant. Field introduced in 20.1.1.
   * @return tenantRef
  **/
  @Schema(description = "Tenant that this object belongs to. It is a reference to an object of type Tenant. Field introduced in 20.1.1.")
  public String getTenantRef() {
    return tenantRef;
  }

  public void setTenantRef(String tenantRef) {
    this.tenantRef = tenantRef;
  }

   /**
   * url
   * @return url
  **/
  @Schema(description = "url")
  public String getUrl() {
    return url;
  }

  public IPReputationDB uuid(String uuid) {
    this.uuid = uuid;
    return this;
  }

   /**
   * UUID of this object. Field introduced in 20.1.1.
   * @return uuid
  **/
  @Schema(description = "UUID of this object. Field introduced in 20.1.1.")
  public String getUuid() {
    return uuid;
  }

  public void setUuid(String uuid) {
    this.uuid = uuid;
  }

  public IPReputationDB vendor(String vendor) {
    this.vendor = vendor;
    return this;
  }

   /**
   * Organization providing IP reputation data. Enum options - IP_REPUTATION_VENDOR_WEBROOT. Field introduced in 20.1.1.
   * @return vendor
  **/
  @Schema(required = true, description = "Organization providing IP reputation data. Enum options - IP_REPUTATION_VENDOR_WEBROOT. Field introduced in 20.1.1.")
  public String getVendor() {
    return vendor;
  }

  public void setVendor(String vendor) {
    this.vendor = vendor;
  }


  @Override
  public boolean equals(java.lang.Object o) {
    if (this == o) {
      return true;
    }
    if (o == null || getClass() != o.getClass()) {
      return false;
    }
    IPReputationDB ipReputationDB = (IPReputationDB) o;
    return Objects.equals(this._lastModified, ipReputationDB._lastModified) &&
        Objects.equals(this.baseFileRef, ipReputationDB.baseFileRef) &&
        Objects.equals(this.description, ipReputationDB.description) &&
        Objects.equals(this.incrementalFileRefs, ipReputationDB.incrementalFileRefs) &&
        Objects.equals(this.lastModified, ipReputationDB.lastModified) &&
        Objects.equals(this.name, ipReputationDB.name) &&
        Objects.equals(this.tenantRef, ipReputationDB.tenantRef) &&
        Objects.equals(this.url, ipReputationDB.url) &&
        Objects.equals(this.uuid, ipReputationDB.uuid) &&
        Objects.equals(this.vendor, ipReputationDB.vendor);
  }

  @Override
  public int hashCode() {
    return Objects.hash(_lastModified, baseFileRef, description, incrementalFileRefs, lastModified, name, tenantRef, url, uuid, vendor);
  }


  @Override
  public String toString() {
    StringBuilder sb = new StringBuilder();
    sb.append("class IPReputationDB {\n");
    
    sb.append("    _lastModified: ").append(toIndentedString(_lastModified)).append("\n");
    sb.append("    baseFileRef: ").append(toIndentedString(baseFileRef)).append("\n");
    sb.append("    description: ").append(toIndentedString(description)).append("\n");
    sb.append("    incrementalFileRefs: ").append(toIndentedString(incrementalFileRefs)).append("\n");
    sb.append("    lastModified: ").append(toIndentedString(lastModified)).append("\n");
    sb.append("    name: ").append(toIndentedString(name)).append("\n");
    sb.append("    tenantRef: ").append(toIndentedString(tenantRef)).append("\n");
    sb.append("    url: ").append(toIndentedString(url)).append("\n");
    sb.append("    uuid: ").append(toIndentedString(uuid)).append("\n");
    sb.append("    vendor: ").append(toIndentedString(vendor)).append("\n");
    sb.append("}");
    return sb.toString();
  }

  /**
   * Convert the given object to string with each line indented by 4 spaces
   * (except the first line).
   */
  private String toIndentedString(java.lang.Object o) {
    if (o == null) {
      return "null";
    }
    return o.toString().replace("\n", "\n    ");
  }

}
