/*
 * Avi avi_global_spec Object API
 * No description provided (generated by Swagger Codegen https://github.com/swagger-api/swagger-codegen)
 *
 * OpenAPI spec version: 20.1.1
 * Contact: support@avinetworks.com
 *
 * NOTE: This class is auto generated by the swagger code generator program.
 * https://github.com/swagger-api/swagger-codegen.git
 * Do not edit the class manually.
 */

package com.vmware.avi.sdk.model;

import java.util.Objects;
import java.util.Arrays;
import com.fasterxml.jackson.annotation.JsonProperty;
import com.fasterxml.jackson.annotation.JsonCreator;
import com.fasterxml.jackson.annotation.JsonValue;
import com.vmware.avi.sdk.model.L4RuleAction;
import com.vmware.avi.sdk.model.L4RuleMatchTarget;
import io.swagger.v3.oas.annotations.media.Schema;
/**
 * L4Rule
 */

@javax.annotation.Generated(value = "io.swagger.codegen.v3.generators.java.JavaClientCodegen", date = "2020-03-12T12:27:26.755+05:30[Asia/Kolkata]")
public class L4Rule {
  @JsonProperty("action")
  private L4RuleAction action = null;

  @JsonProperty("enable")
  private Boolean enable = true;

  @JsonProperty("index")
  private Integer index = null;

  @JsonProperty("match")
  private L4RuleMatchTarget match = null;

  @JsonProperty("name")
  private String name = null;

  public L4Rule action(L4RuleAction action) {
    this.action = action;
    return this;
  }

   /**
   * Get action
   * @return action
  **/
  @Schema(description = "")
  public L4RuleAction getAction() {
    return action;
  }

  public void setAction(L4RuleAction action) {
    this.action = action;
  }

  public L4Rule enable(Boolean enable) {
    this.enable = enable;
    return this;
  }

   /**
   * Enable or disable the rule. Field introduced in 17.2.7.
   * @return enable
  **/
  @Schema(description = "Enable or disable the rule. Field introduced in 17.2.7.")
  public Boolean isEnable() {
    return enable;
  }

  public void setEnable(Boolean enable) {
    this.enable = enable;
  }

  public L4Rule index(Integer index) {
    this.index = index;
    return this;
  }

   /**
   * Index of the rule. Field introduced in 17.2.7.
   * @return index
  **/
  @Schema(required = true, description = "Index of the rule. Field introduced in 17.2.7.")
  public Integer getIndex() {
    return index;
  }

  public void setIndex(Integer index) {
    this.index = index;
  }

  public L4Rule match(L4RuleMatchTarget match) {
    this.match = match;
    return this;
  }

   /**
   * Get match
   * @return match
  **/
  @Schema(description = "")
  public L4RuleMatchTarget getMatch() {
    return match;
  }

  public void setMatch(L4RuleMatchTarget match) {
    this.match = match;
  }

  public L4Rule name(String name) {
    this.name = name;
    return this;
  }

   /**
   * Name of the rule. Field introduced in 17.2.7.
   * @return name
  **/
  @Schema(required = true, description = "Name of the rule. Field introduced in 17.2.7.")
  public String getName() {
    return name;
  }

  public void setName(String name) {
    this.name = name;
  }


  @Override
  public boolean equals(java.lang.Object o) {
    if (this == o) {
      return true;
    }
    if (o == null || getClass() != o.getClass()) {
      return false;
    }
    L4Rule l4Rule = (L4Rule) o;
    return Objects.equals(this.action, l4Rule.action) &&
        Objects.equals(this.enable, l4Rule.enable) &&
        Objects.equals(this.index, l4Rule.index) &&
        Objects.equals(this.match, l4Rule.match) &&
        Objects.equals(this.name, l4Rule.name);
  }

  @Override
  public int hashCode() {
    return Objects.hash(action, enable, index, match, name);
  }


  @Override
  public String toString() {
    StringBuilder sb = new StringBuilder();
    sb.append("class L4Rule {\n");
    
    sb.append("    action: ").append(toIndentedString(action)).append("\n");
    sb.append("    enable: ").append(toIndentedString(enable)).append("\n");
    sb.append("    index: ").append(toIndentedString(index)).append("\n");
    sb.append("    match: ").append(toIndentedString(match)).append("\n");
    sb.append("    name: ").append(toIndentedString(name)).append("\n");
    sb.append("}");
    return sb.toString();
  }

  /**
   * Convert the given object to string with each line indented by 4 spaces
   * (except the first line).
   */
  private String toIndentedString(java.lang.Object o) {
    if (o == null) {
      return "null";
    }
    return o.toString().replace("\n", "\n    ");
  }

}
