/*
 * Avi avi_global_spec Object API
 * No description provided (generated by Swagger Codegen https://github.com/swagger-api/swagger-codegen)
 *
 * OpenAPI spec version: 20.1.1
 * Contact: support@avinetworks.com
 *
 * NOTE: This class is auto generated by the swagger code generator program.
 * https://github.com/swagger-api/swagger-codegen.git
 * Do not edit the class manually.
 */

package com.vmware.avi.sdk.model;

import java.util.Objects;
import java.util.Arrays;
import com.fasterxml.jackson.annotation.JsonProperty;
import com.fasterxml.jackson.annotation.JsonCreator;
import com.fasterxml.jackson.annotation.JsonValue;
import com.vmware.avi.sdk.model.CookieMatch;
import com.vmware.avi.sdk.model.HTTPVersionMatch;
import com.vmware.avi.sdk.model.HdrMatch;
import com.vmware.avi.sdk.model.HostHdrMatch;
import com.vmware.avi.sdk.model.IpAddrMatch;
import com.vmware.avi.sdk.model.MethodMatch;
import com.vmware.avi.sdk.model.PathMatch;
import com.vmware.avi.sdk.model.PortMatch;
import com.vmware.avi.sdk.model.ProtocolMatch;
import com.vmware.avi.sdk.model.QueryMatch;
import io.swagger.v3.oas.annotations.media.Schema;
import java.util.ArrayList;
import java.util.List;
/**
 * MatchTarget
 */

@javax.annotation.Generated(value = "io.swagger.codegen.v3.generators.java.JavaClientCodegen", date = "2020-03-12T12:27:26.755+05:30[Asia/Kolkata]")
public class MatchTarget {
  @JsonProperty("client_ip")
  private IpAddrMatch clientIp = null;

  @JsonProperty("cookie")
  private CookieMatch cookie = null;

  @JsonProperty("hdrs")
  private List<HdrMatch> hdrs = null;

  @JsonProperty("host_hdr")
  private HostHdrMatch hostHdr = null;

  @JsonProperty("method")
  private MethodMatch method = null;

  @JsonProperty("path")
  private PathMatch path = null;

  @JsonProperty("protocol")
  private ProtocolMatch protocol = null;

  @JsonProperty("query")
  private QueryMatch query = null;

  @JsonProperty("version")
  private HTTPVersionMatch version = null;

  @JsonProperty("vs_port")
  private PortMatch vsPort = null;

  public MatchTarget clientIp(IpAddrMatch clientIp) {
    this.clientIp = clientIp;
    return this;
  }

   /**
   * Get clientIp
   * @return clientIp
  **/
  @Schema(description = "")
  public IpAddrMatch getClientIp() {
    return clientIp;
  }

  public void setClientIp(IpAddrMatch clientIp) {
    this.clientIp = clientIp;
  }

  public MatchTarget cookie(CookieMatch cookie) {
    this.cookie = cookie;
    return this;
  }

   /**
   * Get cookie
   * @return cookie
  **/
  @Schema(description = "")
  public CookieMatch getCookie() {
    return cookie;
  }

  public void setCookie(CookieMatch cookie) {
    this.cookie = cookie;
  }

  public MatchTarget hdrs(List<HdrMatch> hdrs) {
    this.hdrs = hdrs;
    return this;
  }

  public MatchTarget addHdrsItem(HdrMatch hdrsItem) {
    if (this.hdrs == null) {
      this.hdrs = new ArrayList<HdrMatch>();
    }
    this.hdrs.add(hdrsItem);
    return this;
  }

   /**
   * Configure HTTP header(s).
   * @return hdrs
  **/
  @Schema(description = "Configure HTTP header(s).")
  public List<HdrMatch> getHdrs() {
    return hdrs;
  }

  public void setHdrs(List<HdrMatch> hdrs) {
    this.hdrs = hdrs;
  }

  public MatchTarget hostHdr(HostHdrMatch hostHdr) {
    this.hostHdr = hostHdr;
    return this;
  }

   /**
   * Get hostHdr
   * @return hostHdr
  **/
  @Schema(description = "")
  public HostHdrMatch getHostHdr() {
    return hostHdr;
  }

  public void setHostHdr(HostHdrMatch hostHdr) {
    this.hostHdr = hostHdr;
  }

  public MatchTarget method(MethodMatch method) {
    this.method = method;
    return this;
  }

   /**
   * Get method
   * @return method
  **/
  @Schema(description = "")
  public MethodMatch getMethod() {
    return method;
  }

  public void setMethod(MethodMatch method) {
    this.method = method;
  }

  public MatchTarget path(PathMatch path) {
    this.path = path;
    return this;
  }

   /**
   * Get path
   * @return path
  **/
  @Schema(description = "")
  public PathMatch getPath() {
    return path;
  }

  public void setPath(PathMatch path) {
    this.path = path;
  }

  public MatchTarget protocol(ProtocolMatch protocol) {
    this.protocol = protocol;
    return this;
  }

   /**
   * Get protocol
   * @return protocol
  **/
  @Schema(description = "")
  public ProtocolMatch getProtocol() {
    return protocol;
  }

  public void setProtocol(ProtocolMatch protocol) {
    this.protocol = protocol;
  }

  public MatchTarget query(QueryMatch query) {
    this.query = query;
    return this;
  }

   /**
   * Get query
   * @return query
  **/
  @Schema(description = "")
  public QueryMatch getQuery() {
    return query;
  }

  public void setQuery(QueryMatch query) {
    this.query = query;
  }

  public MatchTarget version(HTTPVersionMatch version) {
    this.version = version;
    return this;
  }

   /**
   * Get version
   * @return version
  **/
  @Schema(description = "")
  public HTTPVersionMatch getVersion() {
    return version;
  }

  public void setVersion(HTTPVersionMatch version) {
    this.version = version;
  }

  public MatchTarget vsPort(PortMatch vsPort) {
    this.vsPort = vsPort;
    return this;
  }

   /**
   * Get vsPort
   * @return vsPort
  **/
  @Schema(description = "")
  public PortMatch getVsPort() {
    return vsPort;
  }

  public void setVsPort(PortMatch vsPort) {
    this.vsPort = vsPort;
  }


  @Override
  public boolean equals(java.lang.Object o) {
    if (this == o) {
      return true;
    }
    if (o == null || getClass() != o.getClass()) {
      return false;
    }
    MatchTarget matchTarget = (MatchTarget) o;
    return Objects.equals(this.clientIp, matchTarget.clientIp) &&
        Objects.equals(this.cookie, matchTarget.cookie) &&
        Objects.equals(this.hdrs, matchTarget.hdrs) &&
        Objects.equals(this.hostHdr, matchTarget.hostHdr) &&
        Objects.equals(this.method, matchTarget.method) &&
        Objects.equals(this.path, matchTarget.path) &&
        Objects.equals(this.protocol, matchTarget.protocol) &&
        Objects.equals(this.query, matchTarget.query) &&
        Objects.equals(this.version, matchTarget.version) &&
        Objects.equals(this.vsPort, matchTarget.vsPort);
  }

  @Override
  public int hashCode() {
    return Objects.hash(clientIp, cookie, hdrs, hostHdr, method, path, protocol, query, version, vsPort);
  }


  @Override
  public String toString() {
    StringBuilder sb = new StringBuilder();
    sb.append("class MatchTarget {\n");
    
    sb.append("    clientIp: ").append(toIndentedString(clientIp)).append("\n");
    sb.append("    cookie: ").append(toIndentedString(cookie)).append("\n");
    sb.append("    hdrs: ").append(toIndentedString(hdrs)).append("\n");
    sb.append("    hostHdr: ").append(toIndentedString(hostHdr)).append("\n");
    sb.append("    method: ").append(toIndentedString(method)).append("\n");
    sb.append("    path: ").append(toIndentedString(path)).append("\n");
    sb.append("    protocol: ").append(toIndentedString(protocol)).append("\n");
    sb.append("    query: ").append(toIndentedString(query)).append("\n");
    sb.append("    version: ").append(toIndentedString(version)).append("\n");
    sb.append("    vsPort: ").append(toIndentedString(vsPort)).append("\n");
    sb.append("}");
    return sb.toString();
  }

  /**
   * Convert the given object to string with each line indented by 4 spaces
   * (except the first line).
   */
  private String toIndentedString(java.lang.Object o) {
    if (o == null) {
      return "null";
    }
    return o.toString().replace("\n", "\n    ");
  }

}
