/*
 * Avi avi_global_spec Object API
 * No description provided (generated by Swagger Codegen https://github.com/swagger-api/swagger-codegen)
 *
 * OpenAPI spec version: 20.1.1
 * Contact: support@avinetworks.com
 *
 * NOTE: This class is auto generated by the swagger code generator program.
 * https://github.com/swagger-api/swagger-codegen.git
 * Do not edit the class manually.
 */

package com.vmware.avi.sdk.model;

import java.util.Objects;
import java.util.Arrays;
import com.fasterxml.jackson.annotation.JsonProperty;
import com.fasterxml.jackson.annotation.JsonCreator;
import com.fasterxml.jackson.annotation.JsonValue;
import io.swagger.v3.oas.annotations.media.Schema;
/**
 * MesosSeResources
 */

@javax.annotation.Generated(value = "io.swagger.codegen.v3.generators.java.JavaClientCodegen", date = "2020-03-12T12:27:26.755+05:30[Asia/Kolkata]")
public class MesosSeResources {
  @JsonProperty("attribute_key")
  private String attributeKey = null;

  @JsonProperty("attribute_value")
  private String attributeValue = null;

  @JsonProperty("cpu")
  private Float cpu = 2.0f;

  @JsonProperty("memory")
  private Integer memory = 4096;

  public MesosSeResources attributeKey(String attributeKey) {
    this.attributeKey = attributeKey;
    return this;
  }

   /**
   * Attribute (Fleet or Mesos) key of Hosts.
   * @return attributeKey
  **/
  @Schema(required = true, description = "Attribute (Fleet or Mesos) key of Hosts.")
  public String getAttributeKey() {
    return attributeKey;
  }

  public void setAttributeKey(String attributeKey) {
    this.attributeKey = attributeKey;
  }

  public MesosSeResources attributeValue(String attributeValue) {
    this.attributeValue = attributeValue;
    return this;
  }

   /**
   * Attribute (Fleet or Mesos) value of Hosts.
   * @return attributeValue
  **/
  @Schema(required = true, description = "Attribute (Fleet or Mesos) value of Hosts.")
  public String getAttributeValue() {
    return attributeValue;
  }

  public void setAttributeValue(String attributeValue) {
    this.attributeValue = attributeValue;
  }

  public MesosSeResources cpu(Float cpu) {
    this.cpu = cpu;
    return this;
  }

   /**
   * Obsolete - ignored.
   * @return cpu
  **/
  @Schema(description = "Obsolete - ignored.")
  public Float getCpu() {
    return cpu;
  }

  public void setCpu(Float cpu) {
    this.cpu = cpu;
  }

  public MesosSeResources memory(Integer memory) {
    this.memory = memory;
    return this;
  }

   /**
   * Obsolete - ignored.
   * @return memory
  **/
  @Schema(description = "Obsolete - ignored.")
  public Integer getMemory() {
    return memory;
  }

  public void setMemory(Integer memory) {
    this.memory = memory;
  }


  @Override
  public boolean equals(java.lang.Object o) {
    if (this == o) {
      return true;
    }
    if (o == null || getClass() != o.getClass()) {
      return false;
    }
    MesosSeResources mesosSeResources = (MesosSeResources) o;
    return Objects.equals(this.attributeKey, mesosSeResources.attributeKey) &&
        Objects.equals(this.attributeValue, mesosSeResources.attributeValue) &&
        Objects.equals(this.cpu, mesosSeResources.cpu) &&
        Objects.equals(this.memory, mesosSeResources.memory);
  }

  @Override
  public int hashCode() {
    return Objects.hash(attributeKey, attributeValue, cpu, memory);
  }


  @Override
  public String toString() {
    StringBuilder sb = new StringBuilder();
    sb.append("class MesosSeResources {\n");
    
    sb.append("    attributeKey: ").append(toIndentedString(attributeKey)).append("\n");
    sb.append("    attributeValue: ").append(toIndentedString(attributeValue)).append("\n");
    sb.append("    cpu: ").append(toIndentedString(cpu)).append("\n");
    sb.append("    memory: ").append(toIndentedString(memory)).append("\n");
    sb.append("}");
    return sb.toString();
  }

  /**
   * Convert the given object to string with each line indented by 4 spaces
   * (except the first line).
   */
  private String toIndentedString(java.lang.Object o) {
    if (o == null) {
      return "null";
    }
    return o.toString().replace("\n", "\n    ");
  }

}
