/*
 * Avi avi_global_spec Object API
 * No description provided (generated by Swagger Codegen https://github.com/swagger-api/swagger-codegen)
 *
 * OpenAPI spec version: 20.1.1
 * Contact: support@avinetworks.com
 *
 * NOTE: This class is auto generated by the swagger code generator program.
 * https://github.com/swagger-api/swagger-codegen.git
 * Do not edit the class manually.
 */

package com.vmware.avi.sdk.model;

import java.util.Objects;
import java.util.Arrays;
import com.fasterxml.jackson.annotation.JsonProperty;
import com.fasterxml.jackson.annotation.JsonCreator;
import com.fasterxml.jackson.annotation.JsonValue;
import com.vmware.avi.sdk.model.IPReputationTypeMatch;
import com.vmware.avi.sdk.model.IpAddrMatch;
import com.vmware.avi.sdk.model.MicroServiceMatch;
import com.vmware.avi.sdk.model.PortMatch;
import io.swagger.v3.oas.annotations.media.Schema;
/**
 * NetworkSecurityMatchTarget
 */

@javax.annotation.Generated(value = "io.swagger.codegen.v3.generators.java.JavaClientCodegen", date = "2020-03-12T12:27:26.755+05:30[Asia/Kolkata]")
public class NetworkSecurityMatchTarget {
  @JsonProperty("client_ip")
  private IpAddrMatch clientIp = null;

  @JsonProperty("ip_reputation_type")
  private IPReputationTypeMatch ipReputationType = null;

  @JsonProperty("microservice")
  private MicroServiceMatch microservice = null;

  @JsonProperty("vs_port")
  private PortMatch vsPort = null;

  public NetworkSecurityMatchTarget clientIp(IpAddrMatch clientIp) {
    this.clientIp = clientIp;
    return this;
  }

   /**
   * Get clientIp
   * @return clientIp
  **/
  @Schema(description = "")
  public IpAddrMatch getClientIp() {
    return clientIp;
  }

  public void setClientIp(IpAddrMatch clientIp) {
    this.clientIp = clientIp;
  }

  public NetworkSecurityMatchTarget ipReputationType(IPReputationTypeMatch ipReputationType) {
    this.ipReputationType = ipReputationType;
    return this;
  }

   /**
   * Get ipReputationType
   * @return ipReputationType
  **/
  @Schema(description = "")
  public IPReputationTypeMatch getIpReputationType() {
    return ipReputationType;
  }

  public void setIpReputationType(IPReputationTypeMatch ipReputationType) {
    this.ipReputationType = ipReputationType;
  }

  public NetworkSecurityMatchTarget microservice(MicroServiceMatch microservice) {
    this.microservice = microservice;
    return this;
  }

   /**
   * Get microservice
   * @return microservice
  **/
  @Schema(description = "")
  public MicroServiceMatch getMicroservice() {
    return microservice;
  }

  public void setMicroservice(MicroServiceMatch microservice) {
    this.microservice = microservice;
  }

  public NetworkSecurityMatchTarget vsPort(PortMatch vsPort) {
    this.vsPort = vsPort;
    return this;
  }

   /**
   * Get vsPort
   * @return vsPort
  **/
  @Schema(description = "")
  public PortMatch getVsPort() {
    return vsPort;
  }

  public void setVsPort(PortMatch vsPort) {
    this.vsPort = vsPort;
  }


  @Override
  public boolean equals(java.lang.Object o) {
    if (this == o) {
      return true;
    }
    if (o == null || getClass() != o.getClass()) {
      return false;
    }
    NetworkSecurityMatchTarget networkSecurityMatchTarget = (NetworkSecurityMatchTarget) o;
    return Objects.equals(this.clientIp, networkSecurityMatchTarget.clientIp) &&
        Objects.equals(this.ipReputationType, networkSecurityMatchTarget.ipReputationType) &&
        Objects.equals(this.microservice, networkSecurityMatchTarget.microservice) &&
        Objects.equals(this.vsPort, networkSecurityMatchTarget.vsPort);
  }

  @Override
  public int hashCode() {
    return Objects.hash(clientIp, ipReputationType, microservice, vsPort);
  }


  @Override
  public String toString() {
    StringBuilder sb = new StringBuilder();
    sb.append("class NetworkSecurityMatchTarget {\n");
    
    sb.append("    clientIp: ").append(toIndentedString(clientIp)).append("\n");
    sb.append("    ipReputationType: ").append(toIndentedString(ipReputationType)).append("\n");
    sb.append("    microservice: ").append(toIndentedString(microservice)).append("\n");
    sb.append("    vsPort: ").append(toIndentedString(vsPort)).append("\n");
    sb.append("}");
    return sb.toString();
  }

  /**
   * Convert the given object to string with each line indented by 4 spaces
   * (except the first line).
   */
  private String toIndentedString(java.lang.Object o) {
    if (o == null) {
      return "null";
    }
    return o.toString().replace("\n", "\n    ");
  }

}
