/*
 * Avi avi_global_spec Object API
 * No description provided (generated by Swagger Codegen https://github.com/swagger-api/swagger-codegen)
 *
 * OpenAPI spec version: 20.1.1
 * Contact: support@avinetworks.com
 *
 * NOTE: This class is auto generated by the swagger code generator program.
 * https://github.com/swagger-api/swagger-codegen.git
 * Do not edit the class manually.
 */

package com.vmware.avi.sdk.model;

import java.util.Objects;
import java.util.Arrays;
import com.fasterxml.jackson.annotation.JsonProperty;
import com.fasterxml.jackson.annotation.JsonCreator;
import com.fasterxml.jackson.annotation.JsonValue;
import com.vmware.avi.sdk.model.NetworkSecurityMatchTarget;
import com.vmware.avi.sdk.model.NetworkSecurityPolicyActionRLParam;
import io.swagger.v3.oas.annotations.media.Schema;
/**
 * NetworkSecurityRule
 */

@javax.annotation.Generated(value = "io.swagger.codegen.v3.generators.java.JavaClientCodegen", date = "2020-03-12T12:27:26.755+05:30[Asia/Kolkata]")
public class NetworkSecurityRule {
  @JsonProperty("action")
  private String action = null;

  @JsonProperty("age")
  private Integer age = null;

  @JsonProperty("created_by")
  private String createdBy = null;

  @JsonProperty("enable")
  private Boolean enable = null;

  @JsonProperty("index")
  private Integer index = null;

  @JsonProperty("log")
  private Boolean log = null;

  @JsonProperty("match")
  private NetworkSecurityMatchTarget match = null;

  @JsonProperty("name")
  private String name = null;

  @JsonProperty("rl_param")
  private NetworkSecurityPolicyActionRLParam rlParam = null;

  public NetworkSecurityRule action(String action) {
    this.action = action;
    return this;
  }

   /**
   *  Enum options - NETWORK_SECURITY_POLICY_ACTION_TYPE_ALLOW, NETWORK_SECURITY_POLICY_ACTION_TYPE_DENY, NETWORK_SECURITY_POLICY_ACTION_TYPE_RATE_LIMIT.
   * @return action
  **/
  @Schema(required = true, description = " Enum options - NETWORK_SECURITY_POLICY_ACTION_TYPE_ALLOW, NETWORK_SECURITY_POLICY_ACTION_TYPE_DENY, NETWORK_SECURITY_POLICY_ACTION_TYPE_RATE_LIMIT.")
  public String getAction() {
    return action;
  }

  public void setAction(String action) {
    this.action = action;
  }

  public NetworkSecurityRule age(Integer age) {
    this.age = age;
    return this;
  }

   /**
   * Time in minutes after which rule will be deleted. Allowed values are 1-4294967295. Special values are 0- &#x27;blocked for ever&#x27;.
   * @return age
  **/
  @Schema(description = "Time in minutes after which rule will be deleted. Allowed values are 1-4294967295. Special values are 0- 'blocked for ever'.")
  public Integer getAge() {
    return age;
  }

  public void setAge(Integer age) {
    this.age = age;
  }

  public NetworkSecurityRule createdBy(String createdBy) {
    this.createdBy = createdBy;
    return this;
  }

   /**
   * Creator name.
   * @return createdBy
  **/
  @Schema(description = "Creator name.")
  public String getCreatedBy() {
    return createdBy;
  }

  public void setCreatedBy(String createdBy) {
    this.createdBy = createdBy;
  }

  public NetworkSecurityRule enable(Boolean enable) {
    this.enable = enable;
    return this;
  }

   /**
   * Placeholder for description of property enable of obj type NetworkSecurityRule field type str  type boolean
   * @return enable
  **/
  @Schema(required = true, description = "Placeholder for description of property enable of obj type NetworkSecurityRule field type str  type boolean")
  public Boolean isEnable() {
    return enable;
  }

  public void setEnable(Boolean enable) {
    this.enable = enable;
  }

  public NetworkSecurityRule index(Integer index) {
    this.index = index;
    return this;
  }

   /**
   * Number of index.
   * @return index
  **/
  @Schema(required = true, description = "Number of index.")
  public Integer getIndex() {
    return index;
  }

  public void setIndex(Integer index) {
    this.index = index;
  }

  public NetworkSecurityRule log(Boolean log) {
    this.log = log;
    return this;
  }

   /**
   * Placeholder for description of property log of obj type NetworkSecurityRule field type str  type boolean
   * @return log
  **/
  @Schema(description = "Placeholder for description of property log of obj type NetworkSecurityRule field type str  type boolean")
  public Boolean isLog() {
    return log;
  }

  public void setLog(Boolean log) {
    this.log = log;
  }

  public NetworkSecurityRule match(NetworkSecurityMatchTarget match) {
    this.match = match;
    return this;
  }

   /**
   * Get match
   * @return match
  **/
  @Schema(required = true, description = "")
  public NetworkSecurityMatchTarget getMatch() {
    return match;
  }

  public void setMatch(NetworkSecurityMatchTarget match) {
    this.match = match;
  }

  public NetworkSecurityRule name(String name) {
    this.name = name;
    return this;
  }

   /**
   * Name of the object.
   * @return name
  **/
  @Schema(required = true, description = "Name of the object.")
  public String getName() {
    return name;
  }

  public void setName(String name) {
    this.name = name;
  }

  public NetworkSecurityRule rlParam(NetworkSecurityPolicyActionRLParam rlParam) {
    this.rlParam = rlParam;
    return this;
  }

   /**
   * Get rlParam
   * @return rlParam
  **/
  @Schema(description = "")
  public NetworkSecurityPolicyActionRLParam getRlParam() {
    return rlParam;
  }

  public void setRlParam(NetworkSecurityPolicyActionRLParam rlParam) {
    this.rlParam = rlParam;
  }


  @Override
  public boolean equals(java.lang.Object o) {
    if (this == o) {
      return true;
    }
    if (o == null || getClass() != o.getClass()) {
      return false;
    }
    NetworkSecurityRule networkSecurityRule = (NetworkSecurityRule) o;
    return Objects.equals(this.action, networkSecurityRule.action) &&
        Objects.equals(this.age, networkSecurityRule.age) &&
        Objects.equals(this.createdBy, networkSecurityRule.createdBy) &&
        Objects.equals(this.enable, networkSecurityRule.enable) &&
        Objects.equals(this.index, networkSecurityRule.index) &&
        Objects.equals(this.log, networkSecurityRule.log) &&
        Objects.equals(this.match, networkSecurityRule.match) &&
        Objects.equals(this.name, networkSecurityRule.name) &&
        Objects.equals(this.rlParam, networkSecurityRule.rlParam);
  }

  @Override
  public int hashCode() {
    return Objects.hash(action, age, createdBy, enable, index, log, match, name, rlParam);
  }


  @Override
  public String toString() {
    StringBuilder sb = new StringBuilder();
    sb.append("class NetworkSecurityRule {\n");
    
    sb.append("    action: ").append(toIndentedString(action)).append("\n");
    sb.append("    age: ").append(toIndentedString(age)).append("\n");
    sb.append("    createdBy: ").append(toIndentedString(createdBy)).append("\n");
    sb.append("    enable: ").append(toIndentedString(enable)).append("\n");
    sb.append("    index: ").append(toIndentedString(index)).append("\n");
    sb.append("    log: ").append(toIndentedString(log)).append("\n");
    sb.append("    match: ").append(toIndentedString(match)).append("\n");
    sb.append("    name: ").append(toIndentedString(name)).append("\n");
    sb.append("    rlParam: ").append(toIndentedString(rlParam)).append("\n");
    sb.append("}");
    return sb.toString();
  }

  /**
   * Convert the given object to string with each line indented by 4 spaces
   * (except the first line).
   */
  private String toIndentedString(java.lang.Object o) {
    if (o == null) {
      return "null";
    }
    return o.toString().replace("\n", "\n    ");
  }

}
