/*
 * Avi avi_global_spec Object API
 * No description provided (generated by Swagger Codegen https://github.com/swagger-api/swagger-codegen)
 *
 * OpenAPI spec version: 20.1.1
 * Contact: support@avinetworks.com
 *
 * NOTE: This class is auto generated by the swagger code generator program.
 * https://github.com/swagger-api/swagger-codegen.git
 * Do not edit the class manually.
 */

package com.vmware.avi.sdk.model;

import java.util.Objects;
import java.util.Arrays;
import com.fasterxml.jackson.annotation.JsonProperty;
import com.fasterxml.jackson.annotation.JsonCreator;
import com.fasterxml.jackson.annotation.JsonValue;
import io.swagger.v3.oas.annotations.media.Schema;
/**
 * OpenstackLogin
 */

@javax.annotation.Generated(value = "io.swagger.codegen.v3.generators.java.JavaClientCodegen", date = "2020-03-12T12:27:26.755+05:30[Asia/Kolkata]")
public class OpenstackLogin {
  @JsonProperty("admin_tenant")
  private String adminTenant = "admin";

  @JsonProperty("auth_url")
  private String authUrl = null;

  @JsonProperty("keystone_host")
  private String keystoneHost = null;

  @JsonProperty("password")
  private String password = null;

  @JsonProperty("region")
  private String region = null;

  @JsonProperty("username")
  private String username = null;

  public OpenstackLogin adminTenant(String adminTenant) {
    this.adminTenant = adminTenant;
    return this;
  }

   /**
   * admin_tenant of OpenstackLogin.
   * @return adminTenant
  **/
  @Schema(description = "admin_tenant of OpenstackLogin.")
  public String getAdminTenant() {
    return adminTenant;
  }

  public void setAdminTenant(String adminTenant) {
    this.adminTenant = adminTenant;
  }

  public OpenstackLogin authUrl(String authUrl) {
    this.authUrl = authUrl;
    return this;
  }

   /**
   * auth_url of OpenstackLogin.
   * @return authUrl
  **/
  @Schema(description = "auth_url of OpenstackLogin.")
  public String getAuthUrl() {
    return authUrl;
  }

  public void setAuthUrl(String authUrl) {
    this.authUrl = authUrl;
  }

  public OpenstackLogin keystoneHost(String keystoneHost) {
    this.keystoneHost = keystoneHost;
    return this;
  }

   /**
   * keystone_host of OpenstackLogin.
   * @return keystoneHost
  **/
  @Schema(description = "keystone_host of OpenstackLogin.")
  public String getKeystoneHost() {
    return keystoneHost;
  }

  public void setKeystoneHost(String keystoneHost) {
    this.keystoneHost = keystoneHost;
  }

  public OpenstackLogin password(String password) {
    this.password = password;
    return this;
  }

   /**
   * password of OpenstackLogin.
   * @return password
  **/
  @Schema(required = true, description = "password of OpenstackLogin.")
  public String getPassword() {
    return password;
  }

  public void setPassword(String password) {
    this.password = password;
  }

  public OpenstackLogin region(String region) {
    this.region = region;
    return this;
  }

   /**
   * region of OpenstackLogin.
   * @return region
  **/
  @Schema(description = "region of OpenstackLogin.")
  public String getRegion() {
    return region;
  }

  public void setRegion(String region) {
    this.region = region;
  }

  public OpenstackLogin username(String username) {
    this.username = username;
    return this;
  }

   /**
   * username of OpenstackLogin.
   * @return username
  **/
  @Schema(required = true, description = "username of OpenstackLogin.")
  public String getUsername() {
    return username;
  }

  public void setUsername(String username) {
    this.username = username;
  }


  @Override
  public boolean equals(java.lang.Object o) {
    if (this == o) {
      return true;
    }
    if (o == null || getClass() != o.getClass()) {
      return false;
    }
    OpenstackLogin openstackLogin = (OpenstackLogin) o;
    return Objects.equals(this.adminTenant, openstackLogin.adminTenant) &&
        Objects.equals(this.authUrl, openstackLogin.authUrl) &&
        Objects.equals(this.keystoneHost, openstackLogin.keystoneHost) &&
        Objects.equals(this.password, openstackLogin.password) &&
        Objects.equals(this.region, openstackLogin.region) &&
        Objects.equals(this.username, openstackLogin.username);
  }

  @Override
  public int hashCode() {
    return Objects.hash(adminTenant, authUrl, keystoneHost, password, region, username);
  }


  @Override
  public String toString() {
    StringBuilder sb = new StringBuilder();
    sb.append("class OpenstackLogin {\n");
    
    sb.append("    adminTenant: ").append(toIndentedString(adminTenant)).append("\n");
    sb.append("    authUrl: ").append(toIndentedString(authUrl)).append("\n");
    sb.append("    keystoneHost: ").append(toIndentedString(keystoneHost)).append("\n");
    sb.append("    password: ").append(toIndentedString(password)).append("\n");
    sb.append("    region: ").append(toIndentedString(region)).append("\n");
    sb.append("    username: ").append(toIndentedString(username)).append("\n");
    sb.append("}");
    return sb.toString();
  }

  /**
   * Convert the given object to string with each line indented by 4 spaces
   * (except the first line).
   */
  private String toIndentedString(java.lang.Object o) {
    if (o == null) {
      return "null";
    }
    return o.toString().replace("\n", "\n    ");
  }

}
