/*
 * Avi avi_global_spec Object API
 * No description provided (generated by Swagger Codegen https://github.com/swagger-api/swagger-codegen)
 *
 * OpenAPI spec version: 20.1.1
 * Contact: support@avinetworks.com
 *
 * NOTE: This class is auto generated by the swagger code generator program.
 * https://github.com/swagger-api/swagger-codegen.git
 * Do not edit the class manually.
 */

package com.vmware.avi.sdk.model;

import java.util.Objects;
import java.util.Arrays;
import com.fasterxml.jackson.annotation.JsonProperty;
import com.fasterxml.jackson.annotation.JsonCreator;
import com.fasterxml.jackson.annotation.JsonValue;
import com.vmware.avi.sdk.model.Property;
import io.swagger.v3.oas.annotations.media.Schema;
import java.util.ArrayList;
import java.util.List;
/**
 * OpenStackHypervisorProperties
 */

@javax.annotation.Generated(value = "io.swagger.codegen.v3.generators.java.JavaClientCodegen", date = "2020-03-12T12:27:26.755+05:30[Asia/Kolkata]")
public class OpenStackHypervisorProperties {
  @JsonProperty("hypervisor")
  private String hypervisor = null;

  @JsonProperty("image_properties")
  private List<Property> imageProperties = null;

  public OpenStackHypervisorProperties hypervisor(String hypervisor) {
    this.hypervisor = hypervisor;
    return this;
  }

   /**
   * Hypervisor type. Enum options - DEFAULT, VMWARE_ESX, KVM, VMWARE_VSAN, XEN. Field introduced in 17.2.1.
   * @return hypervisor
  **/
  @Schema(required = true, description = "Hypervisor type. Enum options - DEFAULT, VMWARE_ESX, KVM, VMWARE_VSAN, XEN. Field introduced in 17.2.1.")
  public String getHypervisor() {
    return hypervisor;
  }

  public void setHypervisor(String hypervisor) {
    this.hypervisor = hypervisor;
  }

  public OpenStackHypervisorProperties imageProperties(List<Property> imageProperties) {
    this.imageProperties = imageProperties;
    return this;
  }

  public OpenStackHypervisorProperties addImagePropertiesItem(Property imagePropertiesItem) {
    if (this.imageProperties == null) {
      this.imageProperties = new ArrayList<Property>();
    }
    this.imageProperties.add(imagePropertiesItem);
    return this;
  }

   /**
   * Custom properties to be associated with the SE image in Glance for this hypervisor type. Field introduced in 17.2.1.
   * @return imageProperties
  **/
  @Schema(description = "Custom properties to be associated with the SE image in Glance for this hypervisor type. Field introduced in 17.2.1.")
  public List<Property> getImageProperties() {
    return imageProperties;
  }

  public void setImageProperties(List<Property> imageProperties) {
    this.imageProperties = imageProperties;
  }


  @Override
  public boolean equals(java.lang.Object o) {
    if (this == o) {
      return true;
    }
    if (o == null || getClass() != o.getClass()) {
      return false;
    }
    OpenStackHypervisorProperties openStackHypervisorProperties = (OpenStackHypervisorProperties) o;
    return Objects.equals(this.hypervisor, openStackHypervisorProperties.hypervisor) &&
        Objects.equals(this.imageProperties, openStackHypervisorProperties.imageProperties);
  }

  @Override
  public int hashCode() {
    return Objects.hash(hypervisor, imageProperties);
  }


  @Override
  public String toString() {
    StringBuilder sb = new StringBuilder();
    sb.append("class OpenStackHypervisorProperties {\n");
    
    sb.append("    hypervisor: ").append(toIndentedString(hypervisor)).append("\n");
    sb.append("    imageProperties: ").append(toIndentedString(imageProperties)).append("\n");
    sb.append("}");
    return sb.toString();
  }

  /**
   * Convert the given object to string with each line indented by 4 spaces
   * (except the first line).
   */
  private String toIndentedString(java.lang.Object o) {
    if (o == null) {
      return "null";
    }
    return o.toString().replace("\n", "\n    ");
  }

}
