/*
 * Avi avi_global_spec Object API
 * No description provided (generated by Swagger Codegen https://github.com/swagger-api/swagger-codegen)
 *
 * OpenAPI spec version: 20.1.1
 * Contact: support@avinetworks.com
 *
 * NOTE: This class is auto generated by the swagger code generator program.
 * https://github.com/swagger-api/swagger-codegen.git
 * Do not edit the class manually.
 */

package com.vmware.avi.sdk.model;

import java.util.Objects;
import java.util.Arrays;
import com.fasterxml.jackson.annotation.JsonProperty;
import com.fasterxml.jackson.annotation.JsonCreator;
import com.fasterxml.jackson.annotation.JsonValue;
import com.vmware.avi.sdk.model.FailAction;
import com.vmware.avi.sdk.model.PoolGroupMember;
import io.swagger.v3.oas.annotations.media.Schema;
import java.util.ArrayList;
import java.util.List;
/**
 * PoolGroup
 */

@javax.annotation.Generated(value = "io.swagger.codegen.v3.generators.java.JavaClientCodegen", date = "2020-03-12T12:27:26.755+05:30[Asia/Kolkata]")
public class PoolGroup {
  @JsonProperty("_last_modified")
  private String _lastModified = null;

  @JsonProperty("cloud_config_cksum")
  private String cloudConfigCksum = null;

  @JsonProperty("cloud_ref")
  private String cloudRef = null;

  @JsonProperty("created_by")
  private String createdBy = null;

  @JsonProperty("deployment_policy_ref")
  private String deploymentPolicyRef = null;

  @JsonProperty("description")
  private String description = null;

  @JsonProperty("enable_http2")
  private Boolean enableHttp2 = null;

  @JsonProperty("fail_action")
  private FailAction failAction = null;

  @JsonProperty("implicit_priority_labels")
  private Boolean implicitPriorityLabels = null;

  @JsonProperty("members")
  private List<PoolGroupMember> members = null;

  @JsonProperty("min_servers")
  private Integer minServers = null;

  @JsonProperty("name")
  private String name = null;

  @JsonProperty("priority_labels_ref")
  private String priorityLabelsRef = null;

  @JsonProperty("service_metadata")
  private String serviceMetadata = null;

  @JsonProperty("tenant_ref")
  private String tenantRef = null;

  @JsonProperty("url")
  private String url = null;

  @JsonProperty("uuid")
  private String uuid = null;

   /**
   * UNIX time since epoch in microseconds. Units(MICROSECONDS).
   * @return _lastModified
  **/
  @Schema(description = "UNIX time since epoch in microseconds. Units(MICROSECONDS).")
  public String getLastModified() {
    return _lastModified;
  }

  public PoolGroup cloudConfigCksum(String cloudConfigCksum) {
    this.cloudConfigCksum = cloudConfigCksum;
    return this;
  }

   /**
   * Checksum of cloud configuration for PoolGroup. Internally set by cloud connector.
   * @return cloudConfigCksum
  **/
  @Schema(description = "Checksum of cloud configuration for PoolGroup. Internally set by cloud connector.")
  public String getCloudConfigCksum() {
    return cloudConfigCksum;
  }

  public void setCloudConfigCksum(String cloudConfigCksum) {
    this.cloudConfigCksum = cloudConfigCksum;
  }

  public PoolGroup cloudRef(String cloudRef) {
    this.cloudRef = cloudRef;
    return this;
  }

   /**
   *  It is a reference to an object of type Cloud.
   * @return cloudRef
  **/
  @Schema(description = " It is a reference to an object of type Cloud.")
  public String getCloudRef() {
    return cloudRef;
  }

  public void setCloudRef(String cloudRef) {
    this.cloudRef = cloudRef;
  }

  public PoolGroup createdBy(String createdBy) {
    this.createdBy = createdBy;
    return this;
  }

   /**
   * Name of the user who created the object.
   * @return createdBy
  **/
  @Schema(description = "Name of the user who created the object.")
  public String getCreatedBy() {
    return createdBy;
  }

  public void setCreatedBy(String createdBy) {
    this.createdBy = createdBy;
  }

  public PoolGroup deploymentPolicyRef(String deploymentPolicyRef) {
    this.deploymentPolicyRef = deploymentPolicyRef;
    return this;
  }

   /**
   * When setup autoscale manager will automatically promote new pools into production when deployment goals are met. It is a reference to an object of type PoolGroupDeploymentPolicy.
   * @return deploymentPolicyRef
  **/
  @Schema(description = "When setup autoscale manager will automatically promote new pools into production when deployment goals are met. It is a reference to an object of type PoolGroupDeploymentPolicy.")
  public String getDeploymentPolicyRef() {
    return deploymentPolicyRef;
  }

  public void setDeploymentPolicyRef(String deploymentPolicyRef) {
    this.deploymentPolicyRef = deploymentPolicyRef;
  }

  public PoolGroup description(String description) {
    this.description = description;
    return this;
  }

   /**
   * Description of Pool Group.
   * @return description
  **/
  @Schema(description = "Description of Pool Group.")
  public String getDescription() {
    return description;
  }

  public void setDescription(String description) {
    this.description = description;
  }

  public PoolGroup enableHttp2(Boolean enableHttp2) {
    this.enableHttp2 = enableHttp2;
    return this;
  }

   /**
   * Enable HTTP/2 for traffic from VirtualService to all the backend servers in all the pools configured under this PoolGroup. Field introduced in 20.1.1.
   * @return enableHttp2
  **/
  @Schema(description = "Enable HTTP/2 for traffic from VirtualService to all the backend servers in all the pools configured under this PoolGroup. Field introduced in 20.1.1.")
  public Boolean isEnableHttp2() {
    return enableHttp2;
  }

  public void setEnableHttp2(Boolean enableHttp2) {
    this.enableHttp2 = enableHttp2;
  }

  public PoolGroup failAction(FailAction failAction) {
    this.failAction = failAction;
    return this;
  }

   /**
   * Get failAction
   * @return failAction
  **/
  @Schema(description = "")
  public FailAction getFailAction() {
    return failAction;
  }

  public void setFailAction(FailAction failAction) {
    this.failAction = failAction;
  }

  public PoolGroup implicitPriorityLabels(Boolean implicitPriorityLabels) {
    this.implicitPriorityLabels = implicitPriorityLabels;
    return this;
  }

   /**
   * Whether an implicit set of priority labels is generated. Field introduced in 17.1.9,17.2.3.
   * @return implicitPriorityLabels
  **/
  @Schema(description = "Whether an implicit set of priority labels is generated. Field introduced in 17.1.9,17.2.3.")
  public Boolean isImplicitPriorityLabels() {
    return implicitPriorityLabels;
  }

  public void setImplicitPriorityLabels(Boolean implicitPriorityLabels) {
    this.implicitPriorityLabels = implicitPriorityLabels;
  }

  public PoolGroup members(List<PoolGroupMember> members) {
    this.members = members;
    return this;
  }

  public PoolGroup addMembersItem(PoolGroupMember membersItem) {
    if (this.members == null) {
      this.members = new ArrayList<PoolGroupMember>();
    }
    this.members.add(membersItem);
    return this;
  }

   /**
   * List of pool group members object of type PoolGroupMember.
   * @return members
  **/
  @Schema(description = "List of pool group members object of type PoolGroupMember.")
  public List<PoolGroupMember> getMembers() {
    return members;
  }

  public void setMembers(List<PoolGroupMember> members) {
    this.members = members;
  }

  public PoolGroup minServers(Integer minServers) {
    this.minServers = minServers;
    return this;
  }

   /**
   * The minimum number of servers to distribute traffic to. Allowed values are 1-65535. Special values are 0 - &#x27;Disable&#x27;.
   * @return minServers
  **/
  @Schema(description = "The minimum number of servers to distribute traffic to. Allowed values are 1-65535. Special values are 0 - 'Disable'.")
  public Integer getMinServers() {
    return minServers;
  }

  public void setMinServers(Integer minServers) {
    this.minServers = minServers;
  }

  public PoolGroup name(String name) {
    this.name = name;
    return this;
  }

   /**
   * The name of the pool group.
   * @return name
  **/
  @Schema(required = true, description = "The name of the pool group.")
  public String getName() {
    return name;
  }

  public void setName(String name) {
    this.name = name;
  }

  public PoolGroup priorityLabelsRef(String priorityLabelsRef) {
    this.priorityLabelsRef = priorityLabelsRef;
    return this;
  }

   /**
   * UUID of the priority labels. If not provided, pool group member priority label will be interpreted as a number with a larger number considered higher priority. It is a reference to an object of type PriorityLabels.
   * @return priorityLabelsRef
  **/
  @Schema(description = "UUID of the priority labels. If not provided, pool group member priority label will be interpreted as a number with a larger number considered higher priority. It is a reference to an object of type PriorityLabels.")
  public String getPriorityLabelsRef() {
    return priorityLabelsRef;
  }

  public void setPriorityLabelsRef(String priorityLabelsRef) {
    this.priorityLabelsRef = priorityLabelsRef;
  }

  public PoolGroup serviceMetadata(String serviceMetadata) {
    this.serviceMetadata = serviceMetadata;
    return this;
  }

   /**
   * Metadata pertaining to the service provided by this PoolGroup. In Openshift/Kubernetes environments, app metadata info is stored. Any user input to this field will be overwritten by Avi Vantage. Field introduced in 17.2.14,18.1.5,18.2.1.
   * @return serviceMetadata
  **/
  @Schema(description = "Metadata pertaining to the service provided by this PoolGroup. In Openshift/Kubernetes environments, app metadata info is stored. Any user input to this field will be overwritten by Avi Vantage. Field introduced in 17.2.14,18.1.5,18.2.1.")
  public String getServiceMetadata() {
    return serviceMetadata;
  }

  public void setServiceMetadata(String serviceMetadata) {
    this.serviceMetadata = serviceMetadata;
  }

  public PoolGroup tenantRef(String tenantRef) {
    this.tenantRef = tenantRef;
    return this;
  }

   /**
   *  It is a reference to an object of type Tenant.
   * @return tenantRef
  **/
  @Schema(description = " It is a reference to an object of type Tenant.")
  public String getTenantRef() {
    return tenantRef;
  }

  public void setTenantRef(String tenantRef) {
    this.tenantRef = tenantRef;
  }

   /**
   * url
   * @return url
  **/
  @Schema(description = "url")
  public String getUrl() {
    return url;
  }

  public PoolGroup uuid(String uuid) {
    this.uuid = uuid;
    return this;
  }

   /**
   * UUID of the pool group.
   * @return uuid
  **/
  @Schema(description = "UUID of the pool group.")
  public String getUuid() {
    return uuid;
  }

  public void setUuid(String uuid) {
    this.uuid = uuid;
  }


  @Override
  public boolean equals(java.lang.Object o) {
    if (this == o) {
      return true;
    }
    if (o == null || getClass() != o.getClass()) {
      return false;
    }
    PoolGroup poolGroup = (PoolGroup) o;
    return Objects.equals(this._lastModified, poolGroup._lastModified) &&
        Objects.equals(this.cloudConfigCksum, poolGroup.cloudConfigCksum) &&
        Objects.equals(this.cloudRef, poolGroup.cloudRef) &&
        Objects.equals(this.createdBy, poolGroup.createdBy) &&
        Objects.equals(this.deploymentPolicyRef, poolGroup.deploymentPolicyRef) &&
        Objects.equals(this.description, poolGroup.description) &&
        Objects.equals(this.enableHttp2, poolGroup.enableHttp2) &&
        Objects.equals(this.failAction, poolGroup.failAction) &&
        Objects.equals(this.implicitPriorityLabels, poolGroup.implicitPriorityLabels) &&
        Objects.equals(this.members, poolGroup.members) &&
        Objects.equals(this.minServers, poolGroup.minServers) &&
        Objects.equals(this.name, poolGroup.name) &&
        Objects.equals(this.priorityLabelsRef, poolGroup.priorityLabelsRef) &&
        Objects.equals(this.serviceMetadata, poolGroup.serviceMetadata) &&
        Objects.equals(this.tenantRef, poolGroup.tenantRef) &&
        Objects.equals(this.url, poolGroup.url) &&
        Objects.equals(this.uuid, poolGroup.uuid);
  }

  @Override
  public int hashCode() {
    return Objects.hash(_lastModified, cloudConfigCksum, cloudRef, createdBy, deploymentPolicyRef, description, enableHttp2, failAction, implicitPriorityLabels, members, minServers, name, priorityLabelsRef, serviceMetadata, tenantRef, url, uuid);
  }


  @Override
  public String toString() {
    StringBuilder sb = new StringBuilder();
    sb.append("class PoolGroup {\n");
    
    sb.append("    _lastModified: ").append(toIndentedString(_lastModified)).append("\n");
    sb.append("    cloudConfigCksum: ").append(toIndentedString(cloudConfigCksum)).append("\n");
    sb.append("    cloudRef: ").append(toIndentedString(cloudRef)).append("\n");
    sb.append("    createdBy: ").append(toIndentedString(createdBy)).append("\n");
    sb.append("    deploymentPolicyRef: ").append(toIndentedString(deploymentPolicyRef)).append("\n");
    sb.append("    description: ").append(toIndentedString(description)).append("\n");
    sb.append("    enableHttp2: ").append(toIndentedString(enableHttp2)).append("\n");
    sb.append("    failAction: ").append(toIndentedString(failAction)).append("\n");
    sb.append("    implicitPriorityLabels: ").append(toIndentedString(implicitPriorityLabels)).append("\n");
    sb.append("    members: ").append(toIndentedString(members)).append("\n");
    sb.append("    minServers: ").append(toIndentedString(minServers)).append("\n");
    sb.append("    name: ").append(toIndentedString(name)).append("\n");
    sb.append("    priorityLabelsRef: ").append(toIndentedString(priorityLabelsRef)).append("\n");
    sb.append("    serviceMetadata: ").append(toIndentedString(serviceMetadata)).append("\n");
    sb.append("    tenantRef: ").append(toIndentedString(tenantRef)).append("\n");
    sb.append("    url: ").append(toIndentedString(url)).append("\n");
    sb.append("    uuid: ").append(toIndentedString(uuid)).append("\n");
    sb.append("}");
    return sb.toString();
  }

  /**
   * Convert the given object to string with each line indented by 4 spaces
   * (except the first line).
   */
  private String toIndentedString(java.lang.Object o) {
    if (o == null) {
      return "null";
    }
    return o.toString().replace("\n", "\n    ");
  }

}
