/*
 * Avi avi_global_spec Object API
 * No description provided (generated by Swagger Codegen https://github.com/swagger-api/swagger-codegen)
 *
 * OpenAPI spec version: 20.1.1
 * Contact: support@avinetworks.com
 *
 * NOTE: This class is auto generated by the swagger code generator program.
 * https://github.com/swagger-api/swagger-codegen.git
 * Do not edit the class manually.
 */

package com.vmware.avi.sdk.model;

import java.util.Objects;
import java.util.Arrays;
import com.fasterxml.jackson.annotation.JsonProperty;
import com.fasterxml.jackson.annotation.JsonCreator;
import com.fasterxml.jackson.annotation.JsonValue;
import com.vmware.avi.sdk.model.SamlServiceProviderNode;
import io.swagger.v3.oas.annotations.media.Schema;
import java.util.ArrayList;
import java.util.List;
/**
 * SamlServiceProviderSettings
 */

@javax.annotation.Generated(value = "io.swagger.codegen.v3.generators.java.JavaClientCodegen", date = "2020-03-12T12:27:26.755+05:30[Asia/Kolkata]")
public class SamlServiceProviderSettings {
  @JsonProperty("fqdn")
  private String fqdn = null;

  @JsonProperty("org_display_name")
  private String orgDisplayName = null;

  @JsonProperty("org_name")
  private String orgName = null;

  @JsonProperty("org_url")
  private String orgUrl = null;

  @JsonProperty("saml_entity_type")
  private String samlEntityType = null;

  @JsonProperty("sp_nodes")
  private List<SamlServiceProviderNode> spNodes = null;

  @JsonProperty("tech_contact_email")
  private String techContactEmail = null;

  @JsonProperty("tech_contact_name")
  private String techContactName = null;

  public SamlServiceProviderSettings fqdn(String fqdn) {
    this.fqdn = fqdn;
    return this;
  }

   /**
   * FQDN if entity type is DNS_FQDN . Field introduced in 17.2.3.
   * @return fqdn
  **/
  @Schema(description = "FQDN if entity type is DNS_FQDN . Field introduced in 17.2.3.")
  public String getFqdn() {
    return fqdn;
  }

  public void setFqdn(String fqdn) {
    this.fqdn = fqdn;
  }

  public SamlServiceProviderSettings orgDisplayName(String orgDisplayName) {
    this.orgDisplayName = orgDisplayName;
    return this;
  }

   /**
   * Service Provider Organization Display Name. Field introduced in 17.2.3.
   * @return orgDisplayName
  **/
  @Schema(description = "Service Provider Organization Display Name. Field introduced in 17.2.3.")
  public String getOrgDisplayName() {
    return orgDisplayName;
  }

  public void setOrgDisplayName(String orgDisplayName) {
    this.orgDisplayName = orgDisplayName;
  }

  public SamlServiceProviderSettings orgName(String orgName) {
    this.orgName = orgName;
    return this;
  }

   /**
   * Service Provider Organization Name. Field introduced in 17.2.3.
   * @return orgName
  **/
  @Schema(description = "Service Provider Organization Name. Field introduced in 17.2.3.")
  public String getOrgName() {
    return orgName;
  }

  public void setOrgName(String orgName) {
    this.orgName = orgName;
  }

  public SamlServiceProviderSettings orgUrl(String orgUrl) {
    this.orgUrl = orgUrl;
    return this;
  }

   /**
   * Service Provider Organization URL. Field introduced in 17.2.3.
   * @return orgUrl
  **/
  @Schema(description = "Service Provider Organization URL. Field introduced in 17.2.3.")
  public String getOrgUrl() {
    return orgUrl;
  }

  public void setOrgUrl(String orgUrl) {
    this.orgUrl = orgUrl;
  }

  public SamlServiceProviderSettings samlEntityType(String samlEntityType) {
    this.samlEntityType = samlEntityType;
    return this;
  }

   /**
   * Type of SAML endpoint. Enum options - AUTH_SAML_CLUSTER_VIP, AUTH_SAML_DNS_FQDN, AUTH_SAML_APP_VS. Field introduced in 17.2.3.
   * @return samlEntityType
  **/
  @Schema(description = "Type of SAML endpoint. Enum options - AUTH_SAML_CLUSTER_VIP, AUTH_SAML_DNS_FQDN, AUTH_SAML_APP_VS. Field introduced in 17.2.3.")
  public String getSamlEntityType() {
    return samlEntityType;
  }

  public void setSamlEntityType(String samlEntityType) {
    this.samlEntityType = samlEntityType;
  }

  public SamlServiceProviderSettings spNodes(List<SamlServiceProviderNode> spNodes) {
    this.spNodes = spNodes;
    return this;
  }

  public SamlServiceProviderSettings addSpNodesItem(SamlServiceProviderNode spNodesItem) {
    if (this.spNodes == null) {
      this.spNodes = new ArrayList<SamlServiceProviderNode>();
    }
    this.spNodes.add(spNodesItem);
    return this;
  }

   /**
   * Service Provider node information. Field introduced in 17.2.3.
   * @return spNodes
  **/
  @Schema(description = "Service Provider node information. Field introduced in 17.2.3.")
  public List<SamlServiceProviderNode> getSpNodes() {
    return spNodes;
  }

  public void setSpNodes(List<SamlServiceProviderNode> spNodes) {
    this.spNodes = spNodes;
  }

  public SamlServiceProviderSettings techContactEmail(String techContactEmail) {
    this.techContactEmail = techContactEmail;
    return this;
  }

   /**
   * Service Provider technical contact email. Field introduced in 17.2.3.
   * @return techContactEmail
  **/
  @Schema(description = "Service Provider technical contact email. Field introduced in 17.2.3.")
  public String getTechContactEmail() {
    return techContactEmail;
  }

  public void setTechContactEmail(String techContactEmail) {
    this.techContactEmail = techContactEmail;
  }

  public SamlServiceProviderSettings techContactName(String techContactName) {
    this.techContactName = techContactName;
    return this;
  }

   /**
   * Service Provider technical contact name. Field introduced in 17.2.3.
   * @return techContactName
  **/
  @Schema(description = "Service Provider technical contact name. Field introduced in 17.2.3.")
  public String getTechContactName() {
    return techContactName;
  }

  public void setTechContactName(String techContactName) {
    this.techContactName = techContactName;
  }


  @Override
  public boolean equals(java.lang.Object o) {
    if (this == o) {
      return true;
    }
    if (o == null || getClass() != o.getClass()) {
      return false;
    }
    SamlServiceProviderSettings samlServiceProviderSettings = (SamlServiceProviderSettings) o;
    return Objects.equals(this.fqdn, samlServiceProviderSettings.fqdn) &&
        Objects.equals(this.orgDisplayName, samlServiceProviderSettings.orgDisplayName) &&
        Objects.equals(this.orgName, samlServiceProviderSettings.orgName) &&
        Objects.equals(this.orgUrl, samlServiceProviderSettings.orgUrl) &&
        Objects.equals(this.samlEntityType, samlServiceProviderSettings.samlEntityType) &&
        Objects.equals(this.spNodes, samlServiceProviderSettings.spNodes) &&
        Objects.equals(this.techContactEmail, samlServiceProviderSettings.techContactEmail) &&
        Objects.equals(this.techContactName, samlServiceProviderSettings.techContactName);
  }

  @Override
  public int hashCode() {
    return Objects.hash(fqdn, orgDisplayName, orgName, orgUrl, samlEntityType, spNodes, techContactEmail, techContactName);
  }


  @Override
  public String toString() {
    StringBuilder sb = new StringBuilder();
    sb.append("class SamlServiceProviderSettings {\n");
    
    sb.append("    fqdn: ").append(toIndentedString(fqdn)).append("\n");
    sb.append("    orgDisplayName: ").append(toIndentedString(orgDisplayName)).append("\n");
    sb.append("    orgName: ").append(toIndentedString(orgName)).append("\n");
    sb.append("    orgUrl: ").append(toIndentedString(orgUrl)).append("\n");
    sb.append("    samlEntityType: ").append(toIndentedString(samlEntityType)).append("\n");
    sb.append("    spNodes: ").append(toIndentedString(spNodes)).append("\n");
    sb.append("    techContactEmail: ").append(toIndentedString(techContactEmail)).append("\n");
    sb.append("    techContactName: ").append(toIndentedString(techContactName)).append("\n");
    sb.append("}");
    return sb.toString();
  }

  /**
   * Convert the given object to string with each line indented by 4 spaces
   * (except the first line).
   */
  private String toIndentedString(java.lang.Object o) {
    if (o == null) {
      return "null";
    }
    return o.toString().replace("\n", "\n    ");
  }

}
