/*
 * Avi avi_global_spec Object API
 * No description provided (generated by Swagger Codegen https://github.com/swagger-api/swagger-codegen)
 *
 * OpenAPI spec version: 20.1.1
 * Contact: support@avinetworks.com
 *
 * NOTE: This class is auto generated by the swagger code generator program.
 * https://github.com/swagger-api/swagger-codegen.git
 * Do not edit the class manually.
 */

package com.vmware.avi.sdk.model;

import java.util.Objects;
import java.util.Arrays;
import com.fasterxml.jackson.annotation.JsonProperty;
import com.fasterxml.jackson.annotation.JsonCreator;
import com.fasterxml.jackson.annotation.JsonValue;
import io.swagger.v3.oas.annotations.media.Schema;
/**
 * Scheduler
 */

@javax.annotation.Generated(value = "io.swagger.codegen.v3.generators.java.JavaClientCodegen", date = "2020-03-12T12:27:26.755+05:30[Asia/Kolkata]")
public class Scheduler {
  @JsonProperty("_last_modified")
  private String _lastModified = null;

  @JsonProperty("backup_config_ref")
  private String backupConfigRef = null;

  @JsonProperty("enabled")
  private Boolean enabled = true;

  @JsonProperty("end_date_time")
  private String endDateTime = null;

  @JsonProperty("frequency")
  private Integer frequency = null;

  @JsonProperty("frequency_unit")
  private String frequencyUnit = null;

  @JsonProperty("name")
  private String name = null;

  @JsonProperty("run_mode")
  private String runMode = null;

  @JsonProperty("run_script_ref")
  private String runScriptRef = null;

  @JsonProperty("scheduler_action")
  private String schedulerAction = "SCHEDULER_ACTION_BACKUP";

  @JsonProperty("start_date_time")
  private String startDateTime = null;

  @JsonProperty("tenant_ref")
  private String tenantRef = null;

  @JsonProperty("url")
  private String url = null;

  @JsonProperty("uuid")
  private String uuid = null;

   /**
   * UNIX time since epoch in microseconds. Units(MICROSECONDS).
   * @return _lastModified
  **/
  @Schema(description = "UNIX time since epoch in microseconds. Units(MICROSECONDS).")
  public String getLastModified() {
    return _lastModified;
  }

  public Scheduler backupConfigRef(String backupConfigRef) {
    this.backupConfigRef = backupConfigRef;
    return this;
  }

   /**
   * Backup Configuration to be executed by this scheduler. It is a reference to an object of type BackupConfiguration.
   * @return backupConfigRef
  **/
  @Schema(description = "Backup Configuration to be executed by this scheduler. It is a reference to an object of type BackupConfiguration.")
  public String getBackupConfigRef() {
    return backupConfigRef;
  }

  public void setBackupConfigRef(String backupConfigRef) {
    this.backupConfigRef = backupConfigRef;
  }

  public Scheduler enabled(Boolean enabled) {
    this.enabled = enabled;
    return this;
  }

   /**
   * Placeholder for description of property enabled of obj type Scheduler field type str  type boolean
   * @return enabled
  **/
  @Schema(description = "Placeholder for description of property enabled of obj type Scheduler field type str  type boolean")
  public Boolean isEnabled() {
    return enabled;
  }

  public void setEnabled(Boolean enabled) {
    this.enabled = enabled;
  }

  public Scheduler endDateTime(String endDateTime) {
    this.endDateTime = endDateTime;
    return this;
  }

   /**
   * Scheduler end date and time.
   * @return endDateTime
  **/
  @Schema(description = "Scheduler end date and time.")
  public String getEndDateTime() {
    return endDateTime;
  }

  public void setEndDateTime(String endDateTime) {
    this.endDateTime = endDateTime;
  }

  public Scheduler frequency(Integer frequency) {
    this.frequency = frequency;
    return this;
  }

   /**
   * Frequency at which CUSTOM scheduler will run. Allowed values are 0-60.
   * @return frequency
  **/
  @Schema(description = "Frequency at which CUSTOM scheduler will run. Allowed values are 0-60.")
  public Integer getFrequency() {
    return frequency;
  }

  public void setFrequency(Integer frequency) {
    this.frequency = frequency;
  }

  public Scheduler frequencyUnit(String frequencyUnit) {
    this.frequencyUnit = frequencyUnit;
    return this;
  }

   /**
   * Unit at which CUSTOM scheduler will run. Enum options - SCHEDULER_FREQUENCY_UNIT_MIN, SCHEDULER_FREQUENCY_UNIT_HOUR, SCHEDULER_FREQUENCY_UNIT_DAY, SCHEDULER_FREQUENCY_UNIT_WEEK, SCHEDULER_FREQUENCY_UNIT_MONTH.
   * @return frequencyUnit
  **/
  @Schema(description = "Unit at which CUSTOM scheduler will run. Enum options - SCHEDULER_FREQUENCY_UNIT_MIN, SCHEDULER_FREQUENCY_UNIT_HOUR, SCHEDULER_FREQUENCY_UNIT_DAY, SCHEDULER_FREQUENCY_UNIT_WEEK, SCHEDULER_FREQUENCY_UNIT_MONTH.")
  public String getFrequencyUnit() {
    return frequencyUnit;
  }

  public void setFrequencyUnit(String frequencyUnit) {
    this.frequencyUnit = frequencyUnit;
  }

  public Scheduler name(String name) {
    this.name = name;
    return this;
  }

   /**
   * Name of scheduler.
   * @return name
  **/
  @Schema(required = true, description = "Name of scheduler.")
  public String getName() {
    return name;
  }

  public void setName(String name) {
    this.name = name;
  }

  public Scheduler runMode(String runMode) {
    this.runMode = runMode;
    return this;
  }

   /**
   * Scheduler Run Mode. Enum options - RUN_MODE_PERIODIC, RUN_MODE_AT, RUN_MODE_NOW.
   * @return runMode
  **/
  @Schema(description = "Scheduler Run Mode. Enum options - RUN_MODE_PERIODIC, RUN_MODE_AT, RUN_MODE_NOW.")
  public String getRunMode() {
    return runMode;
  }

  public void setRunMode(String runMode) {
    this.runMode = runMode;
  }

  public Scheduler runScriptRef(String runScriptRef) {
    this.runScriptRef = runScriptRef;
    return this;
  }

   /**
   * Control script to be executed by this scheduler. It is a reference to an object of type AlertScriptConfig.
   * @return runScriptRef
  **/
  @Schema(description = "Control script to be executed by this scheduler. It is a reference to an object of type AlertScriptConfig.")
  public String getRunScriptRef() {
    return runScriptRef;
  }

  public void setRunScriptRef(String runScriptRef) {
    this.runScriptRef = runScriptRef;
  }

  public Scheduler schedulerAction(String schedulerAction) {
    this.schedulerAction = schedulerAction;
    return this;
  }

   /**
   * Define Scheduler Action. Enum options - SCHEDULER_ACTION_RUN_A_SCRIPT, SCHEDULER_ACTION_BACKUP.
   * @return schedulerAction
  **/
  @Schema(description = "Define Scheduler Action. Enum options - SCHEDULER_ACTION_RUN_A_SCRIPT, SCHEDULER_ACTION_BACKUP.")
  public String getSchedulerAction() {
    return schedulerAction;
  }

  public void setSchedulerAction(String schedulerAction) {
    this.schedulerAction = schedulerAction;
  }

  public Scheduler startDateTime(String startDateTime) {
    this.startDateTime = startDateTime;
    return this;
  }

   /**
   * Scheduler start date and time.
   * @return startDateTime
  **/
  @Schema(description = "Scheduler start date and time.")
  public String getStartDateTime() {
    return startDateTime;
  }

  public void setStartDateTime(String startDateTime) {
    this.startDateTime = startDateTime;
  }

  public Scheduler tenantRef(String tenantRef) {
    this.tenantRef = tenantRef;
    return this;
  }

   /**
   *  It is a reference to an object of type Tenant.
   * @return tenantRef
  **/
  @Schema(description = " It is a reference to an object of type Tenant.")
  public String getTenantRef() {
    return tenantRef;
  }

  public void setTenantRef(String tenantRef) {
    this.tenantRef = tenantRef;
  }

   /**
   * url
   * @return url
  **/
  @Schema(description = "url")
  public String getUrl() {
    return url;
  }

  public Scheduler uuid(String uuid) {
    this.uuid = uuid;
    return this;
  }

   /**
   * Unique object identifier of the object.
   * @return uuid
  **/
  @Schema(description = "Unique object identifier of the object.")
  public String getUuid() {
    return uuid;
  }

  public void setUuid(String uuid) {
    this.uuid = uuid;
  }


  @Override
  public boolean equals(java.lang.Object o) {
    if (this == o) {
      return true;
    }
    if (o == null || getClass() != o.getClass()) {
      return false;
    }
    Scheduler scheduler = (Scheduler) o;
    return Objects.equals(this._lastModified, scheduler._lastModified) &&
        Objects.equals(this.backupConfigRef, scheduler.backupConfigRef) &&
        Objects.equals(this.enabled, scheduler.enabled) &&
        Objects.equals(this.endDateTime, scheduler.endDateTime) &&
        Objects.equals(this.frequency, scheduler.frequency) &&
        Objects.equals(this.frequencyUnit, scheduler.frequencyUnit) &&
        Objects.equals(this.name, scheduler.name) &&
        Objects.equals(this.runMode, scheduler.runMode) &&
        Objects.equals(this.runScriptRef, scheduler.runScriptRef) &&
        Objects.equals(this.schedulerAction, scheduler.schedulerAction) &&
        Objects.equals(this.startDateTime, scheduler.startDateTime) &&
        Objects.equals(this.tenantRef, scheduler.tenantRef) &&
        Objects.equals(this.url, scheduler.url) &&
        Objects.equals(this.uuid, scheduler.uuid);
  }

  @Override
  public int hashCode() {
    return Objects.hash(_lastModified, backupConfigRef, enabled, endDateTime, frequency, frequencyUnit, name, runMode, runScriptRef, schedulerAction, startDateTime, tenantRef, url, uuid);
  }


  @Override
  public String toString() {
    StringBuilder sb = new StringBuilder();
    sb.append("class Scheduler {\n");
    
    sb.append("    _lastModified: ").append(toIndentedString(_lastModified)).append("\n");
    sb.append("    backupConfigRef: ").append(toIndentedString(backupConfigRef)).append("\n");
    sb.append("    enabled: ").append(toIndentedString(enabled)).append("\n");
    sb.append("    endDateTime: ").append(toIndentedString(endDateTime)).append("\n");
    sb.append("    frequency: ").append(toIndentedString(frequency)).append("\n");
    sb.append("    frequencyUnit: ").append(toIndentedString(frequencyUnit)).append("\n");
    sb.append("    name: ").append(toIndentedString(name)).append("\n");
    sb.append("    runMode: ").append(toIndentedString(runMode)).append("\n");
    sb.append("    runScriptRef: ").append(toIndentedString(runScriptRef)).append("\n");
    sb.append("    schedulerAction: ").append(toIndentedString(schedulerAction)).append("\n");
    sb.append("    startDateTime: ").append(toIndentedString(startDateTime)).append("\n");
    sb.append("    tenantRef: ").append(toIndentedString(tenantRef)).append("\n");
    sb.append("    url: ").append(toIndentedString(url)).append("\n");
    sb.append("    uuid: ").append(toIndentedString(uuid)).append("\n");
    sb.append("}");
    return sb.toString();
  }

  /**
   * Convert the given object to string with each line indented by 4 spaces
   * (except the first line).
   */
  private String toIndentedString(java.lang.Object o) {
    if (o == null) {
      return "null";
    }
    return o.toString().replace("\n", "\n    ");
  }

}
