/*
 * Avi avi_global_spec Object API
 * No description provided (generated by Swagger Codegen https://github.com/swagger-api/swagger-codegen)
 *
 * OpenAPI spec version: 20.1.1
 * Contact: support@avinetworks.com
 *
 * NOTE: This class is auto generated by the swagger code generator program.
 * https://github.com/swagger-api/swagger-codegen.git
 * Do not edit the class manually.
 */

package com.vmware.avi.sdk.model;

import java.util.Objects;
import java.util.Arrays;
import com.fasterxml.jackson.annotation.JsonProperty;
import com.fasterxml.jackson.annotation.JsonCreator;
import com.fasterxml.jackson.annotation.JsonValue;
import io.swagger.v3.oas.annotations.media.Schema;
/**
 * SecureChannelMetadata
 */

@javax.annotation.Generated(value = "io.swagger.codegen.v3.generators.java.JavaClientCodegen", date = "2020-03-12T12:27:26.755+05:30[Asia/Kolkata]")
public class SecureChannelMetadata {
  @JsonProperty("key")
  private String key = null;

  @JsonProperty("val")
  private String val = null;

  public SecureChannelMetadata key(String key) {
    this.key = key;
    return this;
  }

   /**
   * key of SecureChannelMetadata.
   * @return key
  **/
  @Schema(description = "key of SecureChannelMetadata.")
  public String getKey() {
    return key;
  }

  public void setKey(String key) {
    this.key = key;
  }

  public SecureChannelMetadata val(String val) {
    this.val = val;
    return this;
  }

   /**
   * val of SecureChannelMetadata.
   * @return val
  **/
  @Schema(description = "val of SecureChannelMetadata.")
  public String getVal() {
    return val;
  }

  public void setVal(String val) {
    this.val = val;
  }


  @Override
  public boolean equals(java.lang.Object o) {
    if (this == o) {
      return true;
    }
    if (o == null || getClass() != o.getClass()) {
      return false;
    }
    SecureChannelMetadata secureChannelMetadata = (SecureChannelMetadata) o;
    return Objects.equals(this.key, secureChannelMetadata.key) &&
        Objects.equals(this.val, secureChannelMetadata.val);
  }

  @Override
  public int hashCode() {
    return Objects.hash(key, val);
  }


  @Override
  public String toString() {
    StringBuilder sb = new StringBuilder();
    sb.append("class SecureChannelMetadata {\n");
    
    sb.append("    key: ").append(toIndentedString(key)).append("\n");
    sb.append("    val: ").append(toIndentedString(val)).append("\n");
    sb.append("}");
    return sb.toString();
  }

  /**
   * Convert the given object to string with each line indented by 4 spaces
   * (except the first line).
   */
  private String toIndentedString(java.lang.Object o) {
    if (o == null) {
      return "null";
    }
    return o.toString().replace("\n", "\n    ");
  }

}
