/*
 * Avi avi_global_spec Object API
 * No description provided (generated by Swagger Codegen https://github.com/swagger-api/swagger-codegen)
 *
 * OpenAPI spec version: 20.1.1
 * Contact: support@avinetworks.com
 *
 * NOTE: This class is auto generated by the swagger code generator program.
 * https://github.com/swagger-api/swagger-codegen.git
 * Do not edit the class manually.
 */

package com.vmware.avi.sdk.model;

import java.util.Objects;
import java.util.Arrays;
import com.fasterxml.jackson.annotation.JsonProperty;
import com.fasterxml.jackson.annotation.JsonCreator;
import com.fasterxml.jackson.annotation.JsonValue;
import io.swagger.v3.oas.annotations.media.Schema;
/**
 * SeRpcProxyDebugFilter
 */

@javax.annotation.Generated(value = "io.swagger.codegen.v3.generators.java.JavaClientCodegen", date = "2020-03-12T12:27:26.755+05:30[Asia/Kolkata]")
public class SeRpcProxyDebugFilter {
  @JsonProperty("method_name")
  private String methodName = null;

  @JsonProperty("queue")
  private String queue = null;

  @JsonProperty("se_uuid")
  private String seUuid = null;

  public SeRpcProxyDebugFilter methodName(String methodName) {
    this.methodName = methodName;
    return this;
  }

   /**
   * Method name of RPC. Field introduced in 18.1.5, 18.2.1.
   * @return methodName
  **/
  @Schema(description = "Method name of RPC. Field introduced in 18.1.5, 18.2.1.")
  public String getMethodName() {
    return methodName;
  }

  public void setMethodName(String methodName) {
    this.methodName = methodName;
  }

  public SeRpcProxyDebugFilter queue(String queue) {
    this.queue = queue;
    return this;
  }

   /**
   * Queue name of RPC. Field introduced in 18.1.5, 18.2.1.
   * @return queue
  **/
  @Schema(description = "Queue name of RPC. Field introduced in 18.1.5, 18.2.1.")
  public String getQueue() {
    return queue;
  }

  public void setQueue(String queue) {
    this.queue = queue;
  }

  public SeRpcProxyDebugFilter seUuid(String seUuid) {
    this.seUuid = seUuid;
    return this;
  }

   /**
   * UUID of Service Engine. Field introduced in 18.1.5, 18.2.1.
   * @return seUuid
  **/
  @Schema(description = "UUID of Service Engine. Field introduced in 18.1.5, 18.2.1.")
  public String getSeUuid() {
    return seUuid;
  }

  public void setSeUuid(String seUuid) {
    this.seUuid = seUuid;
  }


  @Override
  public boolean equals(java.lang.Object o) {
    if (this == o) {
      return true;
    }
    if (o == null || getClass() != o.getClass()) {
      return false;
    }
    SeRpcProxyDebugFilter seRpcProxyDebugFilter = (SeRpcProxyDebugFilter) o;
    return Objects.equals(this.methodName, seRpcProxyDebugFilter.methodName) &&
        Objects.equals(this.queue, seRpcProxyDebugFilter.queue) &&
        Objects.equals(this.seUuid, seRpcProxyDebugFilter.seUuid);
  }

  @Override
  public int hashCode() {
    return Objects.hash(methodName, queue, seUuid);
  }


  @Override
  public String toString() {
    StringBuilder sb = new StringBuilder();
    sb.append("class SeRpcProxyDebugFilter {\n");
    
    sb.append("    methodName: ").append(toIndentedString(methodName)).append("\n");
    sb.append("    queue: ").append(toIndentedString(queue)).append("\n");
    sb.append("    seUuid: ").append(toIndentedString(seUuid)).append("\n");
    sb.append("}");
    return sb.toString();
  }

  /**
   * Convert the given object to string with each line indented by 4 spaces
   * (except the first line).
   */
  private String toIndentedString(java.lang.Object o) {
    if (o == null) {
      return "null";
    }
    return o.toString().replace("\n", "\n    ");
  }

}
