/*
 * Avi avi_global_spec Object API
 * No description provided (generated by Swagger Codegen https://github.com/swagger-api/swagger-codegen)
 *
 * OpenAPI spec version: 20.1.1
 * Contact: support@avinetworks.com
 *
 * NOTE: This class is auto generated by the swagger code generator program.
 * https://github.com/swagger-api/swagger-codegen.git
 * Do not edit the class manually.
 */

package com.vmware.avi.sdk.model;

import java.util.Objects;
import java.util.Arrays;
import com.fasterxml.jackson.annotation.JsonProperty;
import com.fasterxml.jackson.annotation.JsonCreator;
import com.fasterxml.jackson.annotation.JsonValue;
import com.vmware.avi.sdk.model.ServerId;
import io.swagger.v3.oas.annotations.media.Schema;
import java.util.ArrayList;
import java.util.List;
/**
 * ServerScaleInParams
 */

@javax.annotation.Generated(value = "io.swagger.codegen.v3.generators.java.JavaClientCodegen", date = "2020-03-12T12:27:26.755+05:30[Asia/Kolkata]")
public class ServerScaleInParams {
  @JsonProperty("reason")
  private String reason = null;

  @JsonProperty("servers")
  private List<ServerId> servers = null;

  @JsonProperty("uuid")
  private String uuid = null;

  public ServerScaleInParams reason(String reason) {
    this.reason = reason;
    return this;
  }

   /**
   * Reason for the manual scalein.
   * @return reason
  **/
  @Schema(description = "Reason for the manual scalein.")
  public String getReason() {
    return reason;
  }

  public void setReason(String reason) {
    this.reason = reason;
  }

  public ServerScaleInParams servers(List<ServerId> servers) {
    this.servers = servers;
    return this;
  }

  public ServerScaleInParams addServersItem(ServerId serversItem) {
    if (this.servers == null) {
      this.servers = new ArrayList<ServerId>();
    }
    this.servers.add(serversItem);
    return this;
  }

   /**
   * List of server IDs that should be scaled in.
   * @return servers
  **/
  @Schema(description = "List of server IDs that should be scaled in.")
  public List<ServerId> getServers() {
    return servers;
  }

  public void setServers(List<ServerId> servers) {
    this.servers = servers;
  }

  public ServerScaleInParams uuid(String uuid) {
    this.uuid = uuid;
    return this;
  }

   /**
   * Unique object identifier of the object.
   * @return uuid
  **/
  @Schema(description = "Unique object identifier of the object.")
  public String getUuid() {
    return uuid;
  }

  public void setUuid(String uuid) {
    this.uuid = uuid;
  }


  @Override
  public boolean equals(java.lang.Object o) {
    if (this == o) {
      return true;
    }
    if (o == null || getClass() != o.getClass()) {
      return false;
    }
    ServerScaleInParams serverScaleInParams = (ServerScaleInParams) o;
    return Objects.equals(this.reason, serverScaleInParams.reason) &&
        Objects.equals(this.servers, serverScaleInParams.servers) &&
        Objects.equals(this.uuid, serverScaleInParams.uuid);
  }

  @Override
  public int hashCode() {
    return Objects.hash(reason, servers, uuid);
  }


  @Override
  public String toString() {
    StringBuilder sb = new StringBuilder();
    sb.append("class ServerScaleInParams {\n");
    
    sb.append("    reason: ").append(toIndentedString(reason)).append("\n");
    sb.append("    servers: ").append(toIndentedString(servers)).append("\n");
    sb.append("    uuid: ").append(toIndentedString(uuid)).append("\n");
    sb.append("}");
    return sb.toString();
  }

  /**
   * Convert the given object to string with each line indented by 4 spaces
   * (except the first line).
   */
  private String toIndentedString(java.lang.Object o) {
    if (o == null) {
      return "null";
    }
    return o.toString().replace("\n", "\n    ");
  }

}
