/*
 * Avi avi_global_spec Object API
 * No description provided (generated by Swagger Codegen https://github.com/swagger-api/swagger-codegen)
 *
 * OpenAPI spec version: 20.1.1
 * Contact: support@avinetworks.com
 *
 * NOTE: This class is auto generated by the swagger code generator program.
 * https://github.com/swagger-api/swagger-codegen.git
 * Do not edit the class manually.
 */

package com.vmware.avi.sdk.model;

import java.util.Objects;
import java.util.Arrays;
import com.fasterxml.jackson.annotation.JsonProperty;
import com.fasterxml.jackson.annotation.JsonCreator;
import com.fasterxml.jackson.annotation.JsonValue;
import com.vmware.avi.sdk.model.IpAddr;
import io.swagger.v3.oas.annotations.media.Schema;
/**
 * ServerId
 */

@javax.annotation.Generated(value = "io.swagger.codegen.v3.generators.java.JavaClientCodegen", date = "2020-03-12T12:27:26.755+05:30[Asia/Kolkata]")
public class ServerId {
  @JsonProperty("external_uuid")
  private String externalUuid = null;

  @JsonProperty("ip")
  private IpAddr ip = null;

  @JsonProperty("port")
  private Integer port = null;

  public ServerId externalUuid(String externalUuid) {
    this.externalUuid = externalUuid;
    return this;
  }

   /**
   * This is the external cloud uuid of the Pool server.
   * @return externalUuid
  **/
  @Schema(description = "This is the external cloud uuid of the Pool server.")
  public String getExternalUuid() {
    return externalUuid;
  }

  public void setExternalUuid(String externalUuid) {
    this.externalUuid = externalUuid;
  }

  public ServerId ip(IpAddr ip) {
    this.ip = ip;
    return this;
  }

   /**
   * Get ip
   * @return ip
  **/
  @Schema(required = true, description = "")
  public IpAddr getIp() {
    return ip;
  }

  public void setIp(IpAddr ip) {
    this.ip = ip;
  }

  public ServerId port(Integer port) {
    this.port = port;
    return this;
  }

   /**
   * Number of port.
   * @return port
  **/
  @Schema(required = true, description = "Number of port.")
  public Integer getPort() {
    return port;
  }

  public void setPort(Integer port) {
    this.port = port;
  }


  @Override
  public boolean equals(java.lang.Object o) {
    if (this == o) {
      return true;
    }
    if (o == null || getClass() != o.getClass()) {
      return false;
    }
    ServerId serverId = (ServerId) o;
    return Objects.equals(this.externalUuid, serverId.externalUuid) &&
        Objects.equals(this.ip, serverId.ip) &&
        Objects.equals(this.port, serverId.port);
  }

  @Override
  public int hashCode() {
    return Objects.hash(externalUuid, ip, port);
  }


  @Override
  public String toString() {
    StringBuilder sb = new StringBuilder();
    sb.append("class ServerId {\n");
    
    sb.append("    externalUuid: ").append(toIndentedString(externalUuid)).append("\n");
    sb.append("    ip: ").append(toIndentedString(ip)).append("\n");
    sb.append("    port: ").append(toIndentedString(port)).append("\n");
    sb.append("}");
    return sb.toString();
  }

  /**
   * Convert the given object to string with each line indented by 4 spaces
   * (except the first line).
   */
  private String toIndentedString(java.lang.Object o) {
    if (o == null) {
      return "null";
    }
    return o.toString().replace("\n", "\n    ");
  }

}
