/*
 * Avi avi_global_spec Object API
 * No description provided (generated by Swagger Codegen https://github.com/swagger-api/swagger-codegen)
 *
 * OpenAPI spec version: 20.1.1
 * Contact: support@avinetworks.com
 *
 * NOTE: This class is auto generated by the swagger code generator program.
 * https://github.com/swagger-api/swagger-codegen.git
 * Do not edit the class manually.
 */

package com.vmware.avi.sdk.model;

import java.util.Objects;
import java.util.Arrays;
import com.fasterxml.jackson.annotation.JsonProperty;
import com.fasterxml.jackson.annotation.JsonCreator;
import com.fasterxml.jackson.annotation.JsonValue;
import com.vmware.avi.sdk.model.IpAddr;
import com.vmware.avi.sdk.model.SnmpV3UserParams;
import io.swagger.v3.oas.annotations.media.Schema;
/**
 * SnmpTrapServer
 */

@javax.annotation.Generated(value = "io.swagger.codegen.v3.generators.java.JavaClientCodegen", date = "2020-03-12T12:27:26.755+05:30[Asia/Kolkata]")
public class SnmpTrapServer {
  @JsonProperty("community")
  private String community = null;

  @JsonProperty("ip_addr")
  private IpAddr ipAddr = null;

  @JsonProperty("port")
  private Integer port = 162;

  @JsonProperty("user")
  private SnmpV3UserParams user = null;

  @JsonProperty("version")
  private String version = "SNMP_VER2";

  public SnmpTrapServer community(String community) {
    this.community = community;
    return this;
  }

   /**
   * The community string to communicate with the trap server.
   * @return community
  **/
  @Schema(description = "The community string to communicate with the trap server.")
  public String getCommunity() {
    return community;
  }

  public void setCommunity(String community) {
    this.community = community;
  }

  public SnmpTrapServer ipAddr(IpAddr ipAddr) {
    this.ipAddr = ipAddr;
    return this;
  }

   /**
   * Get ipAddr
   * @return ipAddr
  **/
  @Schema(required = true, description = "")
  public IpAddr getIpAddr() {
    return ipAddr;
  }

  public void setIpAddr(IpAddr ipAddr) {
    this.ipAddr = ipAddr;
  }

  public SnmpTrapServer port(Integer port) {
    this.port = port;
    return this;
  }

   /**
   * The UDP port of the trap server. Field introduced in 16.5.4,17.2.5.
   * @return port
  **/
  @Schema(description = "The UDP port of the trap server. Field introduced in 16.5.4,17.2.5.")
  public Integer getPort() {
    return port;
  }

  public void setPort(Integer port) {
    this.port = port;
  }

  public SnmpTrapServer user(SnmpV3UserParams user) {
    this.user = user;
    return this;
  }

   /**
   * Get user
   * @return user
  **/
  @Schema(description = "")
  public SnmpV3UserParams getUser() {
    return user;
  }

  public void setUser(SnmpV3UserParams user) {
    this.user = user;
  }

  public SnmpTrapServer version(String version) {
    this.version = version;
    return this;
  }

   /**
   * SNMP version support. V2 or V3. Enum options - SNMP_VER2, SNMP_VER3. Field introduced in 17.2.3.
   * @return version
  **/
  @Schema(description = "SNMP version support. V2 or V3. Enum options - SNMP_VER2, SNMP_VER3. Field introduced in 17.2.3.")
  public String getVersion() {
    return version;
  }

  public void setVersion(String version) {
    this.version = version;
  }


  @Override
  public boolean equals(java.lang.Object o) {
    if (this == o) {
      return true;
    }
    if (o == null || getClass() != o.getClass()) {
      return false;
    }
    SnmpTrapServer snmpTrapServer = (SnmpTrapServer) o;
    return Objects.equals(this.community, snmpTrapServer.community) &&
        Objects.equals(this.ipAddr, snmpTrapServer.ipAddr) &&
        Objects.equals(this.port, snmpTrapServer.port) &&
        Objects.equals(this.user, snmpTrapServer.user) &&
        Objects.equals(this.version, snmpTrapServer.version);
  }

  @Override
  public int hashCode() {
    return Objects.hash(community, ipAddr, port, user, version);
  }


  @Override
  public String toString() {
    StringBuilder sb = new StringBuilder();
    sb.append("class SnmpTrapServer {\n");
    
    sb.append("    community: ").append(toIndentedString(community)).append("\n");
    sb.append("    ipAddr: ").append(toIndentedString(ipAddr)).append("\n");
    sb.append("    port: ").append(toIndentedString(port)).append("\n");
    sb.append("    user: ").append(toIndentedString(user)).append("\n");
    sb.append("    version: ").append(toIndentedString(version)).append("\n");
    sb.append("}");
    return sb.toString();
  }

  /**
   * Convert the given object to string with each line indented by 4 spaces
   * (except the first line).
   */
  private String toIndentedString(java.lang.Object o) {
    if (o == null) {
      return "null";
    }
    return o.toString().replace("\n", "\n    ");
  }

}
