/*
 * Avi avi_global_spec Object API
 * No description provided (generated by Swagger Codegen https://github.com/swagger-api/swagger-codegen)
 *
 * OpenAPI spec version: 20.1.1
 * Contact: support@avinetworks.com
 *
 * NOTE: This class is auto generated by the swagger code generator program.
 * https://github.com/swagger-api/swagger-codegen.git
 * Do not edit the class manually.
 */

package com.vmware.avi.sdk.model;

import java.util.Objects;
import java.util.Arrays;
import com.fasterxml.jackson.annotation.JsonProperty;
import com.fasterxml.jackson.annotation.JsonCreator;
import com.fasterxml.jackson.annotation.JsonValue;
import com.vmware.avi.sdk.model.URIParamToken;
import io.swagger.v3.oas.annotations.media.Schema;
import java.util.ArrayList;
import java.util.List;
/**
 * URIParam
 */

@javax.annotation.Generated(value = "io.swagger.codegen.v3.generators.java.JavaClientCodegen", date = "2020-03-12T12:27:26.755+05:30[Asia/Kolkata]")
public class URIParam {
  @JsonProperty("tokens")
  private List<URIParamToken> tokens = null;

  @JsonProperty("type")
  private String type = null;

  public URIParam tokens(List<URIParamToken> tokens) {
    this.tokens = tokens;
    return this;
  }

  public URIParam addTokensItem(URIParamToken tokensItem) {
    if (this.tokens == null) {
      this.tokens = new ArrayList<URIParamToken>();
    }
    this.tokens.add(tokensItem);
    return this;
  }

   /**
   * Token config either for the URI components or a constant string.
   * @return tokens
  **/
  @Schema(description = "Token config either for the URI components or a constant string.")
  public List<URIParamToken> getTokens() {
    return tokens;
  }

  public void setTokens(List<URIParamToken> tokens) {
    this.tokens = tokens;
  }

  public URIParam type(String type) {
    this.type = type;
    return this;
  }

   /**
   * URI param type. Enum options - URI_PARAM_TYPE_TOKENIZED.
   * @return type
  **/
  @Schema(required = true, description = "URI param type. Enum options - URI_PARAM_TYPE_TOKENIZED.")
  public String getType() {
    return type;
  }

  public void setType(String type) {
    this.type = type;
  }


  @Override
  public boolean equals(java.lang.Object o) {
    if (this == o) {
      return true;
    }
    if (o == null || getClass() != o.getClass()) {
      return false;
    }
    URIParam urIParam = (URIParam) o;
    return Objects.equals(this.tokens, urIParam.tokens) &&
        Objects.equals(this.type, urIParam.type);
  }

  @Override
  public int hashCode() {
    return Objects.hash(tokens, type);
  }


  @Override
  public String toString() {
    StringBuilder sb = new StringBuilder();
    sb.append("class URIParam {\n");
    
    sb.append("    tokens: ").append(toIndentedString(tokens)).append("\n");
    sb.append("    type: ").append(toIndentedString(type)).append("\n");
    sb.append("}");
    return sb.toString();
  }

  /**
   * Convert the given object to string with each line indented by 4 spaces
   * (except the first line).
   */
  private String toIndentedString(java.lang.Object o) {
    if (o == null) {
      return "null";
    }
    return o.toString().replace("\n", "\n    ");
  }

}
