/*
 * Avi avi_global_spec Object API
 * No description provided (generated by Swagger Codegen https://github.com/swagger-api/swagger-codegen)
 *
 * OpenAPI spec version: 20.1.1
 * Contact: support@avinetworks.com
 *
 * NOTE: This class is auto generated by the swagger code generator program.
 * https://github.com/swagger-api/swagger-codegen.git
 * Do not edit the class manually.
 */

package com.vmware.avi.sdk.model;

import java.util.Objects;
import java.util.Arrays;
import com.fasterxml.jackson.annotation.JsonProperty;
import com.fasterxml.jackson.annotation.JsonCreator;
import com.fasterxml.jackson.annotation.JsonValue;
import io.swagger.v3.oas.annotations.media.Schema;
/**
 * VIAdminCredentials
 */

@javax.annotation.Generated(value = "io.swagger.codegen.v3.generators.java.JavaClientCodegen", date = "2020-03-12T12:27:26.755+05:30[Asia/Kolkata]")
public class VIAdminCredentials {
  @JsonProperty("name")
  private String name = "root";

  @JsonProperty("password")
  private String password = "vmware";

  @JsonProperty("privilege")
  private String privilege = null;

  @JsonProperty("vcenter_url")
  private String vcenterUrl = null;

  @JsonProperty("vi_mgr_token")
  private String viMgrToken = null;

  public VIAdminCredentials name(String name) {
    this.name = name;
    return this;
  }

   /**
   * Name of the object.
   * @return name
  **/
  @Schema(description = "Name of the object.")
  public String getName() {
    return name;
  }

  public void setName(String name) {
    this.name = name;
  }

  public VIAdminCredentials password(String password) {
    this.password = password;
    return this;
  }

   /**
   * password of VIAdminCredentials.
   * @return password
  **/
  @Schema(description = "password of VIAdminCredentials.")
  public String getPassword() {
    return password;
  }

  public void setPassword(String password) {
    this.password = password;
  }

  public VIAdminCredentials privilege(String privilege) {
    this.privilege = privilege;
    return this;
  }

   /**
   *  Enum options - NO_ACCESS, READ_ACCESS, WRITE_ACCESS.
   * @return privilege
  **/
  @Schema(description = " Enum options - NO_ACCESS, READ_ACCESS, WRITE_ACCESS.")
  public String getPrivilege() {
    return privilege;
  }

  public void setPrivilege(String privilege) {
    this.privilege = privilege;
  }

  public VIAdminCredentials vcenterUrl(String vcenterUrl) {
    this.vcenterUrl = vcenterUrl;
    return this;
  }

   /**
   * vcenter_url of VIAdminCredentials.
   * @return vcenterUrl
  **/
  @Schema(required = true, description = "vcenter_url of VIAdminCredentials.")
  public String getVcenterUrl() {
    return vcenterUrl;
  }

  public void setVcenterUrl(String vcenterUrl) {
    this.vcenterUrl = vcenterUrl;
  }

  public VIAdminCredentials viMgrToken(String viMgrToken) {
    this.viMgrToken = viMgrToken;
    return this;
  }

   /**
   * vi_mgr_token of VIAdminCredentials.
   * @return viMgrToken
  **/
  @Schema(description = "vi_mgr_token of VIAdminCredentials.")
  public String getViMgrToken() {
    return viMgrToken;
  }

  public void setViMgrToken(String viMgrToken) {
    this.viMgrToken = viMgrToken;
  }


  @Override
  public boolean equals(java.lang.Object o) {
    if (this == o) {
      return true;
    }
    if (o == null || getClass() != o.getClass()) {
      return false;
    }
    VIAdminCredentials viAdminCredentials = (VIAdminCredentials) o;
    return Objects.equals(this.name, viAdminCredentials.name) &&
        Objects.equals(this.password, viAdminCredentials.password) &&
        Objects.equals(this.privilege, viAdminCredentials.privilege) &&
        Objects.equals(this.vcenterUrl, viAdminCredentials.vcenterUrl) &&
        Objects.equals(this.viMgrToken, viAdminCredentials.viMgrToken);
  }

  @Override
  public int hashCode() {
    return Objects.hash(name, password, privilege, vcenterUrl, viMgrToken);
  }


  @Override
  public String toString() {
    StringBuilder sb = new StringBuilder();
    sb.append("class VIAdminCredentials {\n");
    
    sb.append("    name: ").append(toIndentedString(name)).append("\n");
    sb.append("    password: ").append(toIndentedString(password)).append("\n");
    sb.append("    privilege: ").append(toIndentedString(privilege)).append("\n");
    sb.append("    vcenterUrl: ").append(toIndentedString(vcenterUrl)).append("\n");
    sb.append("    viMgrToken: ").append(toIndentedString(viMgrToken)).append("\n");
    sb.append("}");
    return sb.toString();
  }

  /**
   * Convert the given object to string with each line indented by 4 spaces
   * (except the first line).
   */
  private String toIndentedString(java.lang.Object o) {
    if (o == null) {
      return "null";
    }
    return o.toString().replace("\n", "\n    ");
  }

}
