/*
 * Avi avi_global_spec Object API
 * No description provided (generated by Swagger Codegen https://github.com/swagger-api/swagger-codegen)
 *
 * OpenAPI spec version: 20.1.1
 * Contact: support@avinetworks.com
 *
 * NOTE: This class is auto generated by the swagger code generator program.
 * https://github.com/swagger-api/swagger-codegen.git
 * Do not edit the class manually.
 */

package com.vmware.avi.sdk.model;

import java.util.Objects;
import java.util.Arrays;
import com.fasterxml.jackson.annotation.JsonProperty;
import com.fasterxml.jackson.annotation.JsonCreator;
import com.fasterxml.jackson.annotation.JsonValue;
import io.swagger.v3.oas.annotations.media.Schema;
import java.util.ArrayList;
import java.util.List;
/**
 * VIMgrClusterRuntime
 */

@javax.annotation.Generated(value = "io.swagger.codegen.v3.generators.java.JavaClientCodegen", date = "2020-03-12T12:27:26.755+05:30[Asia/Kolkata]")
public class VIMgrClusterRuntime {
  @JsonProperty("_last_modified")
  private String _lastModified = null;

  @JsonProperty("cloud_ref")
  private String cloudRef = null;

  @JsonProperty("datacenter_managed_object_id")
  private String datacenterManagedObjectId = null;

  @JsonProperty("datacenter_uuid")
  private String datacenterUuid = null;

  @JsonProperty("host_refs")
  private List<String> hostRefs = null;

  @JsonProperty("managed_object_id")
  private String managedObjectId = null;

  @JsonProperty("name")
  private String name = null;

  @JsonProperty("tenant_ref")
  private String tenantRef = null;

  @JsonProperty("type")
  private String type = null;

  @JsonProperty("url")
  private String url = null;

  @JsonProperty("uuid")
  private String uuid = null;

   /**
   * UNIX time since epoch in microseconds. Units(MICROSECONDS).
   * @return _lastModified
  **/
  @Schema(description = "UNIX time since epoch in microseconds. Units(MICROSECONDS).")
  public String getLastModified() {
    return _lastModified;
  }

  public VIMgrClusterRuntime cloudRef(String cloudRef) {
    this.cloudRef = cloudRef;
    return this;
  }

   /**
   *  It is a reference to an object of type Cloud.
   * @return cloudRef
  **/
  @Schema(description = " It is a reference to an object of type Cloud.")
  public String getCloudRef() {
    return cloudRef;
  }

  public void setCloudRef(String cloudRef) {
    this.cloudRef = cloudRef;
  }

  public VIMgrClusterRuntime datacenterManagedObjectId(String datacenterManagedObjectId) {
    this.datacenterManagedObjectId = datacenterManagedObjectId;
    return this;
  }

   /**
   * datacenter_managed_object_id of VIMgrClusterRuntime.
   * @return datacenterManagedObjectId
  **/
  @Schema(description = "datacenter_managed_object_id of VIMgrClusterRuntime.")
  public String getDatacenterManagedObjectId() {
    return datacenterManagedObjectId;
  }

  public void setDatacenterManagedObjectId(String datacenterManagedObjectId) {
    this.datacenterManagedObjectId = datacenterManagedObjectId;
  }

  public VIMgrClusterRuntime datacenterUuid(String datacenterUuid) {
    this.datacenterUuid = datacenterUuid;
    return this;
  }

   /**
   * Unique object identifier of datacenter.
   * @return datacenterUuid
  **/
  @Schema(description = "Unique object identifier of datacenter.")
  public String getDatacenterUuid() {
    return datacenterUuid;
  }

  public void setDatacenterUuid(String datacenterUuid) {
    this.datacenterUuid = datacenterUuid;
  }

  public VIMgrClusterRuntime hostRefs(List<String> hostRefs) {
    this.hostRefs = hostRefs;
    return this;
  }

  public VIMgrClusterRuntime addHostRefsItem(String hostRefsItem) {
    if (this.hostRefs == null) {
      this.hostRefs = new ArrayList<String>();
    }
    this.hostRefs.add(hostRefsItem);
    return this;
  }

   /**
   *  It is a reference to an object of type VIMgrHostRuntime.
   * @return hostRefs
  **/
  @Schema(description = " It is a reference to an object of type VIMgrHostRuntime.")
  public List<String> getHostRefs() {
    return hostRefs;
  }

  public void setHostRefs(List<String> hostRefs) {
    this.hostRefs = hostRefs;
  }

  public VIMgrClusterRuntime managedObjectId(String managedObjectId) {
    this.managedObjectId = managedObjectId;
    return this;
  }

   /**
   * managed_object_id of VIMgrClusterRuntime.
   * @return managedObjectId
  **/
  @Schema(required = true, description = "managed_object_id of VIMgrClusterRuntime.")
  public String getManagedObjectId() {
    return managedObjectId;
  }

  public void setManagedObjectId(String managedObjectId) {
    this.managedObjectId = managedObjectId;
  }

  public VIMgrClusterRuntime name(String name) {
    this.name = name;
    return this;
  }

   /**
   * Name of the object.
   * @return name
  **/
  @Schema(required = true, description = "Name of the object.")
  public String getName() {
    return name;
  }

  public void setName(String name) {
    this.name = name;
  }

  public VIMgrClusterRuntime tenantRef(String tenantRef) {
    this.tenantRef = tenantRef;
    return this;
  }

   /**
   *  It is a reference to an object of type Tenant.
   * @return tenantRef
  **/
  @Schema(description = " It is a reference to an object of type Tenant.")
  public String getTenantRef() {
    return tenantRef;
  }

  public void setTenantRef(String tenantRef) {
    this.tenantRef = tenantRef;
  }

  public VIMgrClusterRuntime type(String type) {
    this.type = type;
    return this;
  }

   /**
   *  Enum options - CLOUD_NONE, CLOUD_VCENTER, CLOUD_OPENSTACK, CLOUD_AWS, CLOUD_VCA, CLOUD_APIC, CLOUD_MESOS, CLOUD_LINUXSERVER, CLOUD_DOCKER_UCP, CLOUD_RANCHER, CLOUD_OSHIFT_K8S, CLOUD_AZURE, CLOUD_GCP.
   * @return type
  **/
  @Schema(required = true, description = " Enum options - CLOUD_NONE, CLOUD_VCENTER, CLOUD_OPENSTACK, CLOUD_AWS, CLOUD_VCA, CLOUD_APIC, CLOUD_MESOS, CLOUD_LINUXSERVER, CLOUD_DOCKER_UCP, CLOUD_RANCHER, CLOUD_OSHIFT_K8S, CLOUD_AZURE, CLOUD_GCP.")
  public String getType() {
    return type;
  }

  public void setType(String type) {
    this.type = type;
  }

   /**
   * url
   * @return url
  **/
  @Schema(description = "url")
  public String getUrl() {
    return url;
  }

  public VIMgrClusterRuntime uuid(String uuid) {
    this.uuid = uuid;
    return this;
  }

   /**
   * Unique object identifier of the object.
   * @return uuid
  **/
  @Schema(description = "Unique object identifier of the object.")
  public String getUuid() {
    return uuid;
  }

  public void setUuid(String uuid) {
    this.uuid = uuid;
  }


  @Override
  public boolean equals(java.lang.Object o) {
    if (this == o) {
      return true;
    }
    if (o == null || getClass() != o.getClass()) {
      return false;
    }
    VIMgrClusterRuntime viMgrClusterRuntime = (VIMgrClusterRuntime) o;
    return Objects.equals(this._lastModified, viMgrClusterRuntime._lastModified) &&
        Objects.equals(this.cloudRef, viMgrClusterRuntime.cloudRef) &&
        Objects.equals(this.datacenterManagedObjectId, viMgrClusterRuntime.datacenterManagedObjectId) &&
        Objects.equals(this.datacenterUuid, viMgrClusterRuntime.datacenterUuid) &&
        Objects.equals(this.hostRefs, viMgrClusterRuntime.hostRefs) &&
        Objects.equals(this.managedObjectId, viMgrClusterRuntime.managedObjectId) &&
        Objects.equals(this.name, viMgrClusterRuntime.name) &&
        Objects.equals(this.tenantRef, viMgrClusterRuntime.tenantRef) &&
        Objects.equals(this.type, viMgrClusterRuntime.type) &&
        Objects.equals(this.url, viMgrClusterRuntime.url) &&
        Objects.equals(this.uuid, viMgrClusterRuntime.uuid);
  }

  @Override
  public int hashCode() {
    return Objects.hash(_lastModified, cloudRef, datacenterManagedObjectId, datacenterUuid, hostRefs, managedObjectId, name, tenantRef, type, url, uuid);
  }


  @Override
  public String toString() {
    StringBuilder sb = new StringBuilder();
    sb.append("class VIMgrClusterRuntime {\n");
    
    sb.append("    _lastModified: ").append(toIndentedString(_lastModified)).append("\n");
    sb.append("    cloudRef: ").append(toIndentedString(cloudRef)).append("\n");
    sb.append("    datacenterManagedObjectId: ").append(toIndentedString(datacenterManagedObjectId)).append("\n");
    sb.append("    datacenterUuid: ").append(toIndentedString(datacenterUuid)).append("\n");
    sb.append("    hostRefs: ").append(toIndentedString(hostRefs)).append("\n");
    sb.append("    managedObjectId: ").append(toIndentedString(managedObjectId)).append("\n");
    sb.append("    name: ").append(toIndentedString(name)).append("\n");
    sb.append("    tenantRef: ").append(toIndentedString(tenantRef)).append("\n");
    sb.append("    type: ").append(toIndentedString(type)).append("\n");
    sb.append("    url: ").append(toIndentedString(url)).append("\n");
    sb.append("    uuid: ").append(toIndentedString(uuid)).append("\n");
    sb.append("}");
    return sb.toString();
  }

  /**
   * Convert the given object to string with each line indented by 4 spaces
   * (except the first line).
   */
  private String toIndentedString(java.lang.Object o) {
    if (o == null) {
      return "null";
    }
    return o.toString().replace("\n", "\n    ");
  }

}
