/*
 * Avi avi_global_spec Object API
 * No description provided (generated by Swagger Codegen https://github.com/swagger-api/swagger-codegen)
 *
 * OpenAPI spec version: 20.1.1
 * Contact: support@avinetworks.com
 *
 * NOTE: This class is auto generated by the swagger code generator program.
 * https://github.com/swagger-api/swagger-codegen.git
 * Do not edit the class manually.
 */

package com.vmware.avi.sdk.model;

import java.util.Objects;
import java.util.Arrays;
import com.fasterxml.jackson.annotation.JsonProperty;
import com.fasterxml.jackson.annotation.JsonCreator;
import com.fasterxml.jackson.annotation.JsonValue;
import com.vmware.avi.sdk.model.BfdProfile;
import com.vmware.avi.sdk.model.BgpProfile;
import com.vmware.avi.sdk.model.DebugVrfContext;
import com.vmware.avi.sdk.model.GatewayMonitor;
import com.vmware.avi.sdk.model.InternalGatewayMonitor;
import com.vmware.avi.sdk.model.KeyValue;
import com.vmware.avi.sdk.model.StaticRoute;
import io.swagger.v3.oas.annotations.media.Schema;
import java.util.ArrayList;
import java.util.List;
/**
 * VrfContext
 */

@javax.annotation.Generated(value = "io.swagger.codegen.v3.generators.java.JavaClientCodegen", date = "2020-03-12T12:27:26.755+05:30[Asia/Kolkata]")
public class VrfContext {
  @JsonProperty("_last_modified")
  private String _lastModified = null;

  @JsonProperty("bfd_profile")
  private BfdProfile bfdProfile = null;

  @JsonProperty("bgp_profile")
  private BgpProfile bgpProfile = null;

  @JsonProperty("cloud_ref")
  private String cloudRef = null;

  @JsonProperty("debugvrfcontext")
  private DebugVrfContext debugvrfcontext = null;

  @JsonProperty("description")
  private String description = null;

  @JsonProperty("gateway_mon")
  private List<GatewayMonitor> gatewayMon = null;

  @JsonProperty("internal_gateway_monitor")
  private InternalGatewayMonitor internalGatewayMonitor = null;

  @JsonProperty("labels")
  private List<KeyValue> labels = null;

  @JsonProperty("name")
  private String name = null;

  @JsonProperty("static_routes")
  private List<StaticRoute> staticRoutes = null;

  @JsonProperty("system_default")
  private Boolean systemDefault = null;

  @JsonProperty("tenant_ref")
  private String tenantRef = null;

  @JsonProperty("url")
  private String url = null;

  @JsonProperty("uuid")
  private String uuid = null;

   /**
   * UNIX time since epoch in microseconds. Units(MICROSECONDS).
   * @return _lastModified
  **/
  @Schema(description = "UNIX time since epoch in microseconds. Units(MICROSECONDS).")
  public String getLastModified() {
    return _lastModified;
  }

  public VrfContext bfdProfile(BfdProfile bfdProfile) {
    this.bfdProfile = bfdProfile;
    return this;
  }

   /**
   * Get bfdProfile
   * @return bfdProfile
  **/
  @Schema(description = "")
  public BfdProfile getBfdProfile() {
    return bfdProfile;
  }

  public void setBfdProfile(BfdProfile bfdProfile) {
    this.bfdProfile = bfdProfile;
  }

  public VrfContext bgpProfile(BgpProfile bgpProfile) {
    this.bgpProfile = bgpProfile;
    return this;
  }

   /**
   * Get bgpProfile
   * @return bgpProfile
  **/
  @Schema(description = "")
  public BgpProfile getBgpProfile() {
    return bgpProfile;
  }

  public void setBgpProfile(BgpProfile bgpProfile) {
    this.bgpProfile = bgpProfile;
  }

  public VrfContext cloudRef(String cloudRef) {
    this.cloudRef = cloudRef;
    return this;
  }

   /**
   *  It is a reference to an object of type Cloud.
   * @return cloudRef
  **/
  @Schema(description = " It is a reference to an object of type Cloud.")
  public String getCloudRef() {
    return cloudRef;
  }

  public void setCloudRef(String cloudRef) {
    this.cloudRef = cloudRef;
  }

  public VrfContext debugvrfcontext(DebugVrfContext debugvrfcontext) {
    this.debugvrfcontext = debugvrfcontext;
    return this;
  }

   /**
   * Get debugvrfcontext
   * @return debugvrfcontext
  **/
  @Schema(description = "")
  public DebugVrfContext getDebugvrfcontext() {
    return debugvrfcontext;
  }

  public void setDebugvrfcontext(DebugVrfContext debugvrfcontext) {
    this.debugvrfcontext = debugvrfcontext;
  }

  public VrfContext description(String description) {
    this.description = description;
    return this;
  }

   /**
   * User defined description for the object.
   * @return description
  **/
  @Schema(description = "User defined description for the object.")
  public String getDescription() {
    return description;
  }

  public void setDescription(String description) {
    this.description = description;
  }

  public VrfContext gatewayMon(List<GatewayMonitor> gatewayMon) {
    this.gatewayMon = gatewayMon;
    return this;
  }

  public VrfContext addGatewayMonItem(GatewayMonitor gatewayMonItem) {
    if (this.gatewayMon == null) {
      this.gatewayMon = new ArrayList<GatewayMonitor>();
    }
    this.gatewayMon.add(gatewayMonItem);
    return this;
  }

   /**
   * Configure ping based heartbeat check for gateway in service engines of vrf.
   * @return gatewayMon
  **/
  @Schema(description = "Configure ping based heartbeat check for gateway in service engines of vrf.")
  public List<GatewayMonitor> getGatewayMon() {
    return gatewayMon;
  }

  public void setGatewayMon(List<GatewayMonitor> gatewayMon) {
    this.gatewayMon = gatewayMon;
  }

  public VrfContext internalGatewayMonitor(InternalGatewayMonitor internalGatewayMonitor) {
    this.internalGatewayMonitor = internalGatewayMonitor;
    return this;
  }

   /**
   * Get internalGatewayMonitor
   * @return internalGatewayMonitor
  **/
  @Schema(description = "")
  public InternalGatewayMonitor getInternalGatewayMonitor() {
    return internalGatewayMonitor;
  }

  public void setInternalGatewayMonitor(InternalGatewayMonitor internalGatewayMonitor) {
    this.internalGatewayMonitor = internalGatewayMonitor;
  }

  public VrfContext labels(List<KeyValue> labels) {
    this.labels = labels;
    return this;
  }

  public VrfContext addLabelsItem(KeyValue labelsItem) {
    if (this.labels == null) {
      this.labels = new ArrayList<KeyValue>();
    }
    this.labels.add(labelsItem);
    return this;
  }

   /**
   * Key/value labels which can be used for Object Access Policy permission scoping. Field introduced in 18.2.7, 20.1.1.
   * @return labels
  **/
  @Schema(description = "Key/value labels which can be used for Object Access Policy permission scoping. Field introduced in 18.2.7, 20.1.1.")
  public List<KeyValue> getLabels() {
    return labels;
  }

  public void setLabels(List<KeyValue> labels) {
    this.labels = labels;
  }

  public VrfContext name(String name) {
    this.name = name;
    return this;
  }

   /**
   * Name of the object.
   * @return name
  **/
  @Schema(required = true, description = "Name of the object.")
  public String getName() {
    return name;
  }

  public void setName(String name) {
    this.name = name;
  }

  public VrfContext staticRoutes(List<StaticRoute> staticRoutes) {
    this.staticRoutes = staticRoutes;
    return this;
  }

  public VrfContext addStaticRoutesItem(StaticRoute staticRoutesItem) {
    if (this.staticRoutes == null) {
      this.staticRoutes = new ArrayList<StaticRoute>();
    }
    this.staticRoutes.add(staticRoutesItem);
    return this;
  }

   /**
   * Placeholder for description of property static_routes of obj type VrfContext field type str  type object
   * @return staticRoutes
  **/
  @Schema(description = "Placeholder for description of property static_routes of obj type VrfContext field type str  type object")
  public List<StaticRoute> getStaticRoutes() {
    return staticRoutes;
  }

  public void setStaticRoutes(List<StaticRoute> staticRoutes) {
    this.staticRoutes = staticRoutes;
  }

  public VrfContext systemDefault(Boolean systemDefault) {
    this.systemDefault = systemDefault;
    return this;
  }

   /**
   * Placeholder for description of property system_default of obj type VrfContext field type str  type boolean
   * @return systemDefault
  **/
  @Schema(description = "Placeholder for description of property system_default of obj type VrfContext field type str  type boolean")
  public Boolean isSystemDefault() {
    return systemDefault;
  }

  public void setSystemDefault(Boolean systemDefault) {
    this.systemDefault = systemDefault;
  }

  public VrfContext tenantRef(String tenantRef) {
    this.tenantRef = tenantRef;
    return this;
  }

   /**
   *  It is a reference to an object of type Tenant.
   * @return tenantRef
  **/
  @Schema(description = " It is a reference to an object of type Tenant.")
  public String getTenantRef() {
    return tenantRef;
  }

  public void setTenantRef(String tenantRef) {
    this.tenantRef = tenantRef;
  }

   /**
   * url
   * @return url
  **/
  @Schema(description = "url")
  public String getUrl() {
    return url;
  }

  public VrfContext uuid(String uuid) {
    this.uuid = uuid;
    return this;
  }

   /**
   * Unique object identifier of the object.
   * @return uuid
  **/
  @Schema(description = "Unique object identifier of the object.")
  public String getUuid() {
    return uuid;
  }

  public void setUuid(String uuid) {
    this.uuid = uuid;
  }


  @Override
  public boolean equals(java.lang.Object o) {
    if (this == o) {
      return true;
    }
    if (o == null || getClass() != o.getClass()) {
      return false;
    }
    VrfContext vrfContext = (VrfContext) o;
    return Objects.equals(this._lastModified, vrfContext._lastModified) &&
        Objects.equals(this.bfdProfile, vrfContext.bfdProfile) &&
        Objects.equals(this.bgpProfile, vrfContext.bgpProfile) &&
        Objects.equals(this.cloudRef, vrfContext.cloudRef) &&
        Objects.equals(this.debugvrfcontext, vrfContext.debugvrfcontext) &&
        Objects.equals(this.description, vrfContext.description) &&
        Objects.equals(this.gatewayMon, vrfContext.gatewayMon) &&
        Objects.equals(this.internalGatewayMonitor, vrfContext.internalGatewayMonitor) &&
        Objects.equals(this.labels, vrfContext.labels) &&
        Objects.equals(this.name, vrfContext.name) &&
        Objects.equals(this.staticRoutes, vrfContext.staticRoutes) &&
        Objects.equals(this.systemDefault, vrfContext.systemDefault) &&
        Objects.equals(this.tenantRef, vrfContext.tenantRef) &&
        Objects.equals(this.url, vrfContext.url) &&
        Objects.equals(this.uuid, vrfContext.uuid);
  }

  @Override
  public int hashCode() {
    return Objects.hash(_lastModified, bfdProfile, bgpProfile, cloudRef, debugvrfcontext, description, gatewayMon, internalGatewayMonitor, labels, name, staticRoutes, systemDefault, tenantRef, url, uuid);
  }


  @Override
  public String toString() {
    StringBuilder sb = new StringBuilder();
    sb.append("class VrfContext {\n");
    
    sb.append("    _lastModified: ").append(toIndentedString(_lastModified)).append("\n");
    sb.append("    bfdProfile: ").append(toIndentedString(bfdProfile)).append("\n");
    sb.append("    bgpProfile: ").append(toIndentedString(bgpProfile)).append("\n");
    sb.append("    cloudRef: ").append(toIndentedString(cloudRef)).append("\n");
    sb.append("    debugvrfcontext: ").append(toIndentedString(debugvrfcontext)).append("\n");
    sb.append("    description: ").append(toIndentedString(description)).append("\n");
    sb.append("    gatewayMon: ").append(toIndentedString(gatewayMon)).append("\n");
    sb.append("    internalGatewayMonitor: ").append(toIndentedString(internalGatewayMonitor)).append("\n");
    sb.append("    labels: ").append(toIndentedString(labels)).append("\n");
    sb.append("    name: ").append(toIndentedString(name)).append("\n");
    sb.append("    staticRoutes: ").append(toIndentedString(staticRoutes)).append("\n");
    sb.append("    systemDefault: ").append(toIndentedString(systemDefault)).append("\n");
    sb.append("    tenantRef: ").append(toIndentedString(tenantRef)).append("\n");
    sb.append("    url: ").append(toIndentedString(url)).append("\n");
    sb.append("    uuid: ").append(toIndentedString(uuid)).append("\n");
    sb.append("}");
    return sb.toString();
  }

  /**
   * Convert the given object to string with each line indented by 4 spaces
   * (except the first line).
   */
  private String toIndentedString(java.lang.Object o) {
    if (o == null) {
      return "null";
    }
    return o.toString().replace("\n", "\n    ");
  }

}
