/*
 * Avi avi_global_spec Object API
 * No description provided (generated by Swagger Codegen https://github.com/swagger-api/swagger-codegen)
 *
 * OpenAPI spec version: 20.1.1
 * Contact: support@avinetworks.com
 *
 * NOTE: This class is auto generated by the swagger code generator program.
 * https://github.com/swagger-api/swagger-codegen.git
 * Do not edit the class manually.
 */

package com.vmware.avi.sdk.model;

import java.util.Objects;
import java.util.Arrays;
import com.fasterxml.jackson.annotation.JsonProperty;
import com.fasterxml.jackson.annotation.JsonCreator;
import com.fasterxml.jackson.annotation.JsonValue;
import io.swagger.v3.oas.annotations.media.Schema;
/**
 * WafLearning
 */

@javax.annotation.Generated(value = "io.swagger.codegen.v3.generators.java.JavaClientCodegen", date = "2020-03-12T12:27:26.755+05:30[Asia/Kolkata]")
public class WafLearning {
  @JsonProperty("arg_summarization_threshold")
  private Integer argSummarizationThreshold = null;

  @JsonProperty("confidence")
  private Integer confidence = null;

  @JsonProperty("enable")
  private Boolean enable = null;

  @JsonProperty("path_summarization_threshold")
  private Integer pathSummarizationThreshold = null;

  @JsonProperty("sampling_percent")
  private Integer samplingPercent = null;

  public WafLearning argSummarizationThreshold(Integer argSummarizationThreshold) {
    this.argSummarizationThreshold = argSummarizationThreshold;
    return this;
  }

   /**
   * Suffix Summarization threshold used to compress args. Allowed values are 3-255. Field deprecated in 18.2.3. Field introduced in 18.1.2.
   * @return argSummarizationThreshold
  **/
  @Schema(description = "Suffix Summarization threshold used to compress args. Allowed values are 3-255. Field deprecated in 18.2.3. Field introduced in 18.1.2.")
  public Integer getArgSummarizationThreshold() {
    return argSummarizationThreshold;
  }

  public void setArgSummarizationThreshold(Integer argSummarizationThreshold) {
    this.argSummarizationThreshold = argSummarizationThreshold;
  }

  public WafLearning confidence(Integer confidence) {
    this.confidence = confidence;
    return this;
  }

   /**
   * Confidence level used to derive rules from the WAF learning. Allowed values are 60-100. Field deprecated in 18.2.3. Field introduced in 18.1.2.
   * @return confidence
  **/
  @Schema(description = "Confidence level used to derive rules from the WAF learning. Allowed values are 60-100. Field deprecated in 18.2.3. Field introduced in 18.1.2.")
  public Integer getConfidence() {
    return confidence;
  }

  public void setConfidence(Integer confidence) {
    this.confidence = confidence;
  }

  public WafLearning enable(Boolean enable) {
    this.enable = enable;
    return this;
  }

   /**
   * Enable Learning for WAF policy. Field deprecated in 18.2.3. Field introduced in 18.1.2.
   * @return enable
  **/
  @Schema(description = "Enable Learning for WAF policy. Field deprecated in 18.2.3. Field introduced in 18.1.2.")
  public Boolean isEnable() {
    return enable;
  }

  public void setEnable(Boolean enable) {
    this.enable = enable;
  }

  public WafLearning pathSummarizationThreshold(Integer pathSummarizationThreshold) {
    this.pathSummarizationThreshold = pathSummarizationThreshold;
    return this;
  }

   /**
   * Suffix Summarization threshold used to compress paths. Allowed values are 3-255. Field deprecated in 18.2.3. Field introduced in 18.1.2.
   * @return pathSummarizationThreshold
  **/
  @Schema(description = "Suffix Summarization threshold used to compress paths. Allowed values are 3-255. Field deprecated in 18.2.3. Field introduced in 18.1.2.")
  public Integer getPathSummarizationThreshold() {
    return pathSummarizationThreshold;
  }

  public void setPathSummarizationThreshold(Integer pathSummarizationThreshold) {
    this.pathSummarizationThreshold = pathSummarizationThreshold;
  }

  public WafLearning samplingPercent(Integer samplingPercent) {
    this.samplingPercent = samplingPercent;
    return this;
  }

   /**
   * Sampling percent of the requests subjected to WAF learning. Allowed values are 1-100. Field deprecated in 18.2.3. Field introduced in 18.1.2.
   * @return samplingPercent
  **/
  @Schema(description = "Sampling percent of the requests subjected to WAF learning. Allowed values are 1-100. Field deprecated in 18.2.3. Field introduced in 18.1.2.")
  public Integer getSamplingPercent() {
    return samplingPercent;
  }

  public void setSamplingPercent(Integer samplingPercent) {
    this.samplingPercent = samplingPercent;
  }


  @Override
  public boolean equals(java.lang.Object o) {
    if (this == o) {
      return true;
    }
    if (o == null || getClass() != o.getClass()) {
      return false;
    }
    WafLearning wafLearning = (WafLearning) o;
    return Objects.equals(this.argSummarizationThreshold, wafLearning.argSummarizationThreshold) &&
        Objects.equals(this.confidence, wafLearning.confidence) &&
        Objects.equals(this.enable, wafLearning.enable) &&
        Objects.equals(this.pathSummarizationThreshold, wafLearning.pathSummarizationThreshold) &&
        Objects.equals(this.samplingPercent, wafLearning.samplingPercent);
  }

  @Override
  public int hashCode() {
    return Objects.hash(argSummarizationThreshold, confidence, enable, pathSummarizationThreshold, samplingPercent);
  }


  @Override
  public String toString() {
    StringBuilder sb = new StringBuilder();
    sb.append("class WafLearning {\n");
    
    sb.append("    argSummarizationThreshold: ").append(toIndentedString(argSummarizationThreshold)).append("\n");
    sb.append("    confidence: ").append(toIndentedString(confidence)).append("\n");
    sb.append("    enable: ").append(toIndentedString(enable)).append("\n");
    sb.append("    pathSummarizationThreshold: ").append(toIndentedString(pathSummarizationThreshold)).append("\n");
    sb.append("    samplingPercent: ").append(toIndentedString(samplingPercent)).append("\n");
    sb.append("}");
    return sb.toString();
  }

  /**
   * Convert the given object to string with each line indented by 4 spaces
   * (except the first line).
   */
  private String toIndentedString(java.lang.Object o) {
    if (o == null) {
      return "null";
    }
    return o.toString().replace("\n", "\n    ");
  }

}
