/*
 * Avi avi_global_spec Object API
 * No description provided (generated by Swagger Codegen https://github.com/swagger-api/swagger-codegen)
 *
 * OpenAPI spec version: 20.1.1
 * Contact: support@avinetworks.com
 *
 * NOTE: This class is auto generated by the swagger code generator program.
 * https://github.com/swagger-api/swagger-codegen.git
 * Do not edit the class manually.
 */

package com.vmware.avi.sdk.model;

import java.util.Objects;
import java.util.Arrays;
import com.fasterxml.jackson.annotation.JsonProperty;
import com.fasterxml.jackson.annotation.JsonCreator;
import com.fasterxml.jackson.annotation.JsonValue;
import com.vmware.avi.sdk.model.WafPolicyWhitelistRule;
import io.swagger.v3.oas.annotations.media.Schema;
import java.util.ArrayList;
import java.util.List;
/**
 * WafPolicyWhitelist
 */

@javax.annotation.Generated(value = "io.swagger.codegen.v3.generators.java.JavaClientCodegen", date = "2020-03-12T12:27:26.755+05:30[Asia/Kolkata]")
public class WafPolicyWhitelist {
  @JsonProperty("rules")
  private List<WafPolicyWhitelistRule> rules = null;

  public WafPolicyWhitelist rules(List<WafPolicyWhitelistRule> rules) {
    this.rules = rules;
    return this;
  }

  public WafPolicyWhitelist addRulesItem(WafPolicyWhitelistRule rulesItem) {
    if (this.rules == null) {
      this.rules = new ArrayList<WafPolicyWhitelistRule>();
    }
    this.rules.add(rulesItem);
    return this;
  }

   /**
   * Rules to bypass WAF. Field introduced in 18.2.3.
   * @return rules
  **/
  @Schema(description = "Rules to bypass WAF. Field introduced in 18.2.3.")
  public List<WafPolicyWhitelistRule> getRules() {
    return rules;
  }

  public void setRules(List<WafPolicyWhitelistRule> rules) {
    this.rules = rules;
  }


  @Override
  public boolean equals(java.lang.Object o) {
    if (this == o) {
      return true;
    }
    if (o == null || getClass() != o.getClass()) {
      return false;
    }
    WafPolicyWhitelist wafPolicyWhitelist = (WafPolicyWhitelist) o;
    return Objects.equals(this.rules, wafPolicyWhitelist.rules);
  }

  @Override
  public int hashCode() {
    return Objects.hash(rules);
  }


  @Override
  public String toString() {
    StringBuilder sb = new StringBuilder();
    sb.append("class WafPolicyWhitelist {\n");
    
    sb.append("    rules: ").append(toIndentedString(rules)).append("\n");
    sb.append("}");
    return sb.toString();
  }

  /**
   * Convert the given object to string with each line indented by 4 spaces
   * (except the first line).
   */
  private String toIndentedString(java.lang.Object o) {
    if (o == null) {
      return "null";
    }
    return o.toString().replace("\n", "\n    ");
  }

}
